js/battle.js

Fixes weather prediction inaccuracy bug when
- When weather is changed by ability on the first turn
- When weather is changed by ability on switch after a Pokemon faints

Fixes Zarel/Pokemon-Showdown-Client#278 (weather prediction bug)

---

js/client-chat.js

As per https://github.com/Zarel/Pokemon-Showdown-Client/pull/280#issuecomment-65842063

Move client command documentation to client

---

js/battle.js

Put bg-gen 1 for gens 1 and 2.
Eliminate needless and confusing line on js/battle.js
Make bg.jpg the bg for gens 3, 4 and 5.

Add in battle the background for Gens 1 & 2

---

js/client-chat.js
style/client.css

Seeing how nobody worked on #251 anymore, I've implemented what was asked.
It was a bit tricky because of the HTML sanitizing though, making this not the most elegant solution, I guess...

/rank format targeting

---

js/battle.js
js/battledata.js
js/client-battle.js
js/client-chat.js
js/client-mainmenu.js

Client-side part of <a>http://www.smogon.com/forums/threads/3524852/</a>

Add support for removal of messages from chats

---

js/client-chat.js

Only show the restore button if messages were removed from the current
room

Update |unlink|hide| message

---

githooks/update

- Its execution will be aborted if no relevant files have been modified since last index update.
- It will no longer require learnsets-g6.js to already exist.
- It will no longer error if entries of learnsets.js are deleted.
- It will no longer throw if there is an error, allowing the rest of the script to get executed.

Improve learnsets-g6 updater

---

js/client-battle.js
style/client.css

Moving the tooltip to a <code>span</code> allows it to be displayed for disabled buttons

Show tooltip for fainted pokemon

---

js/battle.js
js/client-battle.js
js/client-chat.js
style/client.css

- Prevent messages from being hidden in replays
- Improve wording on the reveal button
- Highlight revealed messages

Several improvements to |unlink|hide|

---

js/client-battle.js
js/client.js

Since no target was specified, it used to be parsed as ´use Conversion against the target in position 2´.

Fix button usage of Conversion 2 in Singles

---

data/graphics.js

Mostly just changed up Tailwind's animation and reverted Superpower's
animation until I can figure out a better one to use. Also changed up
Discharge to be different from Volt Switch.

Graphics Animation Updates

---

js/client-chat.js

Merge this before the server pullreq.

/accept with no userid accepts sole challenges

---

js/client.js

Add hover text showing battlers in battles

---

js/client-teambuilder.js

Endeavor is more of a support move and shouldn't trigger a change in suggested nature.
Also alphabetized the section

Endeavor is not a "physical attack"

---

data/pokedex-mini.js

Plasmanta model update

---

js/battledata.js

Add Plasmanta Icon

---

js/client-chat.js

Suggested on the forums with decent support: http://www.smogon.com/forums/threads/suggestions.3534365/page-2#post-6158958

Add /clearpms command

---

data/pokedex-mini-bw.js
js/battledata.js
js/client-chat-tournament.js
js/client-mainmenu.js
js/client-teambuilder.js
js/client.js

Reloading the BattePokemonSprites to bw for gen 5 battles.
This is by no means perfect (and I'm unsure what the correct location for this is) and require a bit of time for pokedex-mini / pokedex-mini-bw to load properly.

Fix gen 5 sprite sizes in battles

---

style/client.css

prevents this from happening: http://prntscr.com/736fcq

handle long team name overflow

---

js/battledata.js

linking to pullreqs

---

js/battle.js

Relavent server-side PR: https://github.com/Zarel/Pokemon-Showdown/pull/1896

Listen for -center messages

---

js/battle.js
js/client-battle.js

Places opponents on the ignore list and causes their Pokemon to display
species instead of nicknames

Add option to ignore opponents

---

data/pokedex-mini.js

Model render added for BMB's CAP creation.

Aurumoth model render added

---

testclient.html

- Add ``&eacute;`` Instead of "é".

Escape é in "Pokémon"

---

js/client-chat.js

(Also keeping /buttonkick as an alias) Makes the command much more understandable.

Change /buttonkick to /buttonwarn

---

js/client-battle.js

The actions were in the wrong order, you would be demoted then try to player the target; but would return `/addplayer - Access Denied`

Make replacePlayer player the target before leaving.

---

js/battle.js

Intended for parsing player battle choices and possibly doing something with that information in the future -doing nothing for now.

Support 'choice' battle messages

---

js/battle.js

Support `seed` battle messages

---

js/client-teambuilder.js

This is another pull request I am doing for the user: ukerab, they don't want to make a github account for only doing small fixes & additions like these.

Add title to Teambuilder var

---

js/battle.js

Also allow Forewarn to read the Pokemon giving the move in Gen5+.

Add -ability messages for Anticipate and Forewarn

---

js/battle.js

Since Irraquated hasn't been able to update pull request #431 and it was my patch in the first place I've taken the liberty of creating this updated pull request to replace it.

Consistently add and remove the hp colour classes

---

js/battle.js

Adding in the gen 3 bg, and fixing it so that gen 5 can use the rotating backgrounds that it could before.
Preview: http://i.imgur.com/qQB0mj5.png

Battle backgrounds gen 3 + 5

---

js/battle.js

-sethp would report the percentage of remaining HP as the difference. This would also always result in a positive delta, even if HP was lost.

Fix the reported HP difference for -sethp.

---

js/client-chat-tournament.js

Needed for Zarel/Pokemon-Showdown#1968.

Client side support for scouting protection

---

js/client.js

This is just a pet peeve of mine, as I'm so used to pressing the Escape key to cancel dialogs.

Close the popup when the Escape key is pressed

---

js/battle.js

https://github.com/Zarel/Pokemon-Showdown/pull/2148

Allow -transform message handler to check [from] tags for Abilities

---

js/client-battle.js

Move Type and Base Power are volatile and the information is often not accurate.
When a Plate is active, it will change the type of Judgment.
When a Drive is active, it will change the type of Techno Blast.
Other items that change move type and base power will also reflect their changes.
Moves that have a deterministic varying base power will show the current base power.
In doubles, moves that have different base powers depending on target will show all possibilities.
Display all of that on move selector and tooltip to help players know and remember what attack type and what move power they have available.

Make move types and base power match battle status

---

js/battledata.js
js/client-chat.js
js/client-mainmenu.js

Based on http://www.smogon.com/forums/posts/6269808 but adding support for Page Up and Page Down while I was there.
I also refactored the code into a separate method rather than copy-pasting it.

Support additional keys in PM chatboxes

---

js/client-chat.js
js/client-mainmenu.js

kota mentioned this when I was writing PR #477; kota also asked for a deduplication feature, although not exactly the same as the one I've actually implemented.
I made the chat history object global and split some of the key handling code out to it to reduce duplication.

Support chat history in PM chatboxes

---

js/client-battle.js

`getMoveBasePower` needs to know the volatiles and boosts for some moves and the stats and item for other moves. Unfortunately there is no single point of storage for this information; the volatiles and boosts are stored on the active Pokémon while the stats and item are sent by the server for each decision. (The only time this is not true is while spectating or animating in which case the client is still sometimes aware of an item (e.g. due to Frisk, Trick etc.) on an active Pokémon.) This means that, except in those specific cases, the moves Acrobatics, Fling and Natural Gift display incorrect information.
Fortunately there is a way of getting from the active Pokémon to the server-sent Pokémon, so we can pass the active Pokémon to `getMoveBasePower` and it can then look up the …

Fix base power preview for item-dependent moves

---

js/client-chat.js

For https://github.com/Zarel/Pokemon-Showdown/pull/2104

Implement |unlink|roomhide| for room-specific message suppression

---

js/battle.js

%urkerab: hmm, briefly saw a [[perish0]]
Good #500 pullreq...

Add perish0 status

---

js/client-chat.js
js/client.js

I've probably overengineered this, but whatever.
I've given each room an order, which dictates where it gets inserted into the room order array, but could possibly be used in future to simplify the tab creation code because you can group the rooms by the upper nibble of the order.
Someone should look at the autojoin code because I can't test that in the test client.

Allow tabs to be reordered with Shift+Arrow

---

js/client-teambuilder.js

The team builder doesn't properly calculate EV spreads for LC. There are two places where it doesn't take the set level into account.
The first is when calculating whether the HP should be odd or even, where it simply adds or removes 4 HP EVs.
The second is when assigning the remaining EVs; it might put them somewhere where they aren't useful.
For example, if you create an LC team, add Bronzor, give it a Berry Juice as an item and the moves Flash Cannon, Psyshock, Recycle and Stealth Rock, it will try to give it 4 HP EVs because it wants the HP to be odd. (As it happens there aren't enough EVs available to do this.) It then gives the remaining 32 EVs to Defence although it actually needs 68 EVs to make any difference.
In the case of the remaining EVs I wasn't sure how hard to try to put …

Properly calculate EV spreads for LC

---

js/battle.js

See https://github.com/Zarel/Pokemon-Showdown/pull/2234
Samples: [Weak Armor/Moody](http://i.imgur.com/1Oksbys.gif), [Motor Drive](http://i.imgur.com/RC3ANRt.gif), [Iron Barbs/Liquid Ooze](http://i.imgur.com/Ap1S7PH.gif)

Improve support for Ability activation

---

js/battle.js
js/client-battle.js

This was a request made to me in a PM. When an item is removed, the nature of the removal is saved and displayed with the item in the tooltip.
I also made some more items show up in the tooltip such as leftovers and mega stones.

Show items that have been consumed

---

js/battle.js
js/client-battle.js

I'm assuming this is what @Slayer95 wanted in PR #522.
I had to change the way itemEffect was set otherwise the display for Trick and Switcheroo was wrong.

Track the previous item in the battle tooltip

---

js/client-chat.js

Removes the possibility of adding duplicate highlights to your list.

Add a duplicate check for highlights

---

js/client-chat-tournament.js
js/client-mainmenu.js

Addresses [this issue](https://github.com/Zarel/Pokemon-Showdown-Client/pull/518#discussion_r43911754).

Pass roomid when adding TeamPopup from TournamentBox

---

style/client.css

When you looks for a battle you get this grey color which doesn't really suite the red button: http://prntscr.com/8z9e9g
So I changed it to the border's color (a bit darker): http://prntscr.com/8z9hx4

menugroup button - disabled state color change

---

js/client.js

(Updated)
Add options to use <code>/ignore</code> and <code>/rank</code> from the user popup. <code>/rank</code> would mostly be used in battles (I have a related commit planned for when this PR is finalized).
Screenshots: <a href="http://i.imgur.com/Zwgyp22.png" target="_blank">1</a>, <a href="http://i.imgur.com/b0EKXa3.png" target="_blank">2</a>, <a href="http://i.imgur.com/rTFBgeP.png" target="_blank">3</a>

Add /ignore to the user popup

---

data/pokedex-mini.js

To be included with the next sprite/model update.

Stratagem dimensions added

---

data/pokedex-mini.js

From before at https://github.com/Zarel/Pokemon-Showdown-Client/pull/526#issuecomment-156150836

Stratagem dimension fix

---

data/pokedex-mini.js

https://i.imgur.com/IoFY3Sz.png

Add gen 6 substitute graphic.

---

js/battle.js

+Ridaz: Oh. Electrify is still doing thie [[ electrify ]] thing

Add Electrify tag

---

js/client-chat.js
js/client-mainmenu.js

Instead it should be allowed to open a menu that begins with B (Bookmarks in my case).

Don't trigger bold or italic on Alt+B or Alt+I

---

js/client-teambuilder.js

Tighten up drag and drop code

---

data/graphics.js

New Close Combat animation

---

js/client-teambuilder.js

One of the loops to find the optimal EVs isn't bounded at zero. See http://www.smogon.com/forums/posts/6585895
I changed the style of all the relevant loops to be the same as I had accidentally introduced multiple styles in PR #514.

Properly calculate EV spreads for level 1

---

js/client-rooms.js

Currently it gets it wrong on medium-sized windows.
I tried this at all the zoom levels supported by my browser.

Properly close and hide the Rooms room when you click Hide

---

data/graphics.js

How it looks: http://i.imgur.com/Bu7qGyU.gif

New Dynamic Punch animation

---

.eslintrc.js
js/client-battle-tooltips.js
js/client-battle.js
testclient.html

Added gem-boosted powers to move description

---

js/client-rooms.js

For the users button, this adds the mouse-over message "Find an online user" and for the battle button, "Find an active battle".

Mouseovers for users/battle on joinroom page

---

crossdomain.php
crossprotocol.html
js/client-teambuilder.js
js/storage.js

Accessing localStorage when cookies are disabled throws a SecurityError in some browsers.

Avoid crashes from disabled cookies

---

js/client-battle-tooltips.js
js/client-battle.js

I've split this up into 11 parts otherwise it just looks like I rewrote the code, which was not the intention when I first started reading PR #594.

Tooltip item power fixes

---

data/graphics.js

Now with an example from both sides!

Update new Aura Sphere animation

---

js/client.js

This makes the user popups less generic and more unique imo

Make user popups use the usernames color for names

---

js/battle.js
js/client-teambuilder.js
js/search.js

Most messages seem to have been converted but I found a few remnants.

Use Pok&eacute;mon in messages instead of Pokemon.

---

data/graphics.js

Claw attack: 
Bubble Beam:
Water Pulse:
Fusion Flare:
Fusion Bolt:

Move Animations Update #2

---

data/graphics.js

Fix animations

---

js/client-chat-tournament.js

Don't notify for old tournament creation messages

---

data/graphics.js
js/battle.js

Now healing animates (Recover / Heal Order / Synthesis):
Morning Sun:
Moonlight:
Grass Knot:

Update Move Animations

---

data/graphics.js

No longer a "sword that claws"

Sacred & Secret Sword Animation Update

---

data/graphics.js

Scald:
Hydro Pump:
Sacred Sword:

Update Move Animations Round 4

---

style/client.css

This makes it much easier to read while in darkmode.

Make darkmode's .message-error orange colored

---

js/client-topbar.js
js/client.js

So that you can hover a notifying tab to see what the notification was.

Show the room's latest notifications in an HTML tooltip

---

js/client-teambuilder.js

Reference : https://github.com/Zarel/Pokemon-Showdown/pull/2413

Genders can be hacked - client changes

---

js/client-mainmenu.js
js/client-rooms.js

We've eliminated the old `<select>` everywhere else already.

Use format popup when searching for a battle to watch

---

data/graphics.js

Fix Earth Power animation

---

style/client.css

Add link visited to dark mode

---

js/battle.js

Fixes http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-259#post-6707692

Fix bug with spread move animations

---

js/client-chat.js

Add ignorelist command

---

js/battle.js

Similar case like Mummy, but marks opponent's ability instead.

Trace triggers opponent's ability

---

.eslintrc.js
data/graphics.js
js/battle.js

I assume this was what https://github.com/Zarel/Pokemon-Showdown-Client/pull/652 was working towards, but I saw nothing from this after the backgrounds were uploaded. 
@Zarel I recall you mentioning you didn't want some of them, but I don't think you specified which ones.

Add XY battle backgrounds

---

data/graphics.js

Fix bg-darkcity.jpg not loading

---

js/client.js

Support reporting private rooms in userdetails

---

js/client-teambuilder.js

Fixes Zarel/Pokemon-Showdown#2563 reported in the server repo.

Prevent min ATK IVs with Assist, Copycat and Me First

---

js/client-battle-tooltips.js

In normal play this only means Aurorus, since you can't get Nature Power with any of Aerilate, Pixilate or Normalize.

Show the effects of abilities on the type of the move called by Nature Power

---

js/client-battle-tooltips.js

- Use the correct accuracy override for past gens
- Show when Blizzard, Hurricane and Thunder have perfect accuracy due to weather
- Show when Hurricane and Thunder have 50% accuracy due to weather
- Show when No Guard ignores accuracy
- Show effect of accuracy modifiers
- Show effect of Hustle or Compound Eyes
- Show effect of ally's Victory Star
- Show effect of Wide Lens

Show effective accuracy of moves in their tooltips

---

js/client-teambuilder.js
js/search.js
style/client.css

Depends on https://github.com/Zarel/Pokemon-Showdown-Client/pull/702 and https://github.com/Zarel/Pokemon-Showdown/pull/2539
Looks like: http://imgur.com/a/yFd0C

Add UI support for alternate models

---

js/battle.js

Don't allow /ignore to block the messages of staff members.

Fix ignore behavior in battles

---

js/battle.js
style/battle.css

http://www.smogon.com/forums/threads/highlights-in-battles.3558793/

Add highlights to battles

---

js/battle.js

Reset sprite when hitting self in confusion

---

data/pokedex-mini.js

People apparently want this, and I had the models laying around anyway.
https://www.dropbox.com/s/vuhkw3gr42a2rj7/hippowdon.rar?dl=0

Add Hippowdown-F model

---

js/battle.js

Because all the other weather-related messages are.

Make the weather end message small too

---

js/client-battle-tooltips.js

As reported here: http://www.smogon.com/forums/posts/6851471

Don't -ate boost Judgment with Plate or Techno Blast with Drive

---

data/graphics.js

Preparing for Gen VII.
- New ability animation: Power Construct;
- New move animations: Mimic, Oblivion Wing, Roar of Time, Sheer Cold, Shock Wave, Spacial Rend, Supersonic, Thousand Arrows & Waves, Volt Switch;
- Updated move animations: Solar Beam, Surf, Muddy Water, Body Slam, Zen Headbutt;
- Hone Claws uses Rock Polish animation
All changes can be viewed [here](http://www.smogon.com/forums/threads/move-ability-animations-request-thread.3568451/).

Update move animations, round 12

---

data/graphics.js

Fix Volt Switch animation

---

data/graphics.js

- Expected indentation of 3 tab characters but found 4

Fix Travis Build Error

---

data/graphics.js

The other Z-Moves will come in slowly
Flame Charge:

Add Flame Charge and Inferno Overdrive animations

---

data/graphics.js

All changes can be seen [here](http://www.smogon.com/forums/threads/move-ability-animations-request-thread.3568451/page-7#post-6990160)

Update Tri-Attack move animation

---

js/battle.js

Seems like this is the only place left where an Ability doesn't get marked.

Mark the Natural Cure ability when it activates

---

js/battle.js
js/client-battle.js

A bunch of people have requested this, iirc, because they don't want to see their opponent's nicknames but aren't interested in ignoring them entirely.

Allow users to ignore nicknames

---

js/battle.js

If you prefer, I could instead pass -64 and tweak the tooltip code to display 0/ in such a case.

Show the effect of Grudge on a move's PP in the tooltip

---

js/battle.js
js/client-battle-tooltips.js

As mentioned in PR #786. Although, thinking about it, maybe NaN would be less arbitray?

Show the move affected by Grudge as having 0 PP

---

style/client.css

Darkmode: Change roomtab color scheme from default

---

js/client-battle.js

Proposal for showing the moves any player would make while their opponent to move. 
[Example](http://puu.sh/s9nyA.jpg)

Show player actions while waiting for opponent

---

js/client-battle-tooltips.js
style/battle.css

Add coloration to modified stats

---

js/client-battle.js

This might not be the best way of tracking whether the timer button exists...

Make the battle timer tick every second

---

js/battle.js

Also fixes marking Receiver as the base Ability.

Mark Power of Alchemy as the base Ability

---

js/battle.js

Also fixes a bug where the terrain counter decrements on turn 1 (for use with Surge Abilities).

Make Terrains display minimum and maximum turns

---

js/client-battle-tooltips.js

Fixes:
- Multiattack's type
- Liquid Voice's type
- Galvanize's type
- Water Bubble's power
- Steelworker's power
- -ates' power
- Normalize's power

Miscellaneous Gen7 tooltip updates

---

js/client-teambuilder.js
js/search.js

Because Type: Null has a colon in its name, it cant be added to teams. This is a fix to it. 
Sorry if i forgot something its my first time editing the client.

Fix issue with adding Type: Null to a team

---

js/battle.js

According to the preview video it uses the same message as Aftermath, unsurprisingly.

Use correct activation message for Innards Out

---

js/battle.js

As reported in https://www.smogon.com/forums/posts/7095922

Z-Baton-Pass should show copied volatiles

---

js/client-battle-tooltips.js

Sadly this messes up with the alphabetical ordering...

Power Trip has the same BP as Stored Power

---

js/battle.js

This corresponds to Zarel/Pokemon-Showdown#2947.

Add various Z-move messages (client part)

---

js/client-mainmenu.js

Display [Gen 6] and hide [Gen 7]

---

js/client-battle.js

This mostly affects the move "Return 102".

Show the underlying move name when reviewing a player's choice

---

js/battle.js

- Battle Bond
- Disguise
- Power Construct
I copied the use of `-formechange` from Shaymin-Sky's transformation.

Add some activation messages for the new Abilities

---

js/battle.js

As generated by Zarel/Pokemon-Showdown#3029.

Client-side messages for Z-Memento and Z-Parting Shot

---

js/client-teambuilder.js

Use gen 7 anything goes for default validation

---

js/client.js

Autojoin support for side servers

---

js/client-mainmenu.js

I just update "staff" and "retired staff", if there are things you want change in "major contributor" called me @Zarel

update credit button (in the team builder)

---

js/client-mainmenu.js

fix this <img src=http://image.prntscr.com/image/f761180f06964630949751c6f24c842a.png weight=423 height=530>

fix fail in credit button

---

js/client-battle-tooltips.js
js/client-battle.js

- Not sure how I should clone the move to change its name/category/type
- Not implemented showing Z effect of status moves yet
- Not implemented unusual Z moves such as Z-Weather Ball

Show power of generic Z moves in tooltips

---

js/battledata.js

Properly format Pokemon with event abilities in /data

---

js/client-mainmenu.js

Don't unspoil PMs when clicked

---

js/client-chat.js

- hardcode those avatars as potential values that will be written into localStorage.

Make hidden avatars last through into the next PS session

---

js/client-teambuilder.js

Greninja and Greninja-Ash now have separate analysis pages.

smogdexLink: Remove Greninja from exceptions list

---

js/battle.js
js/client-battle.js

[As per request](https://github.com/Zarel/Pokemon-Showdown-Client/pull/875#issuecomment-283262599)

Support old player rank in battle ignores as well

---

js/client-teambuilder.js

Teambuilder: Better support for mixed sets

---

js/client.js
testclient.html

And added a check so the client won't crash when the config fails to load.

Fix config file path in testclient

---

js/client-chat.js

This is mostly useful for people wanting to see their general standing but not wanting to see old ladders that they don't play any more.

Allow users to filter by gen in /rank

---

js/client-chat.js

Also trim targets before parsing so spaces around commas don't throw it off.

Fix format/gen specific /rank

---

js/storage.js

Fix object preferences (like chat formatting) not updating correctly

Storage: Ignore not updating preferences if value is an object

---

js/client-teambuilder.js

(or any format without the 510 EV limit)

Teambuilder: Don't invest in unused stats in BH

---

js/storage.js

Ability is already parsed at line 1043

Remove redundancy

---

package.json

Made package name lowercase #904

---

js/client-battle.js
js/client.js

I think this might be a useful option for people who would like having battles and PMs or the teambuilder open side by side.

Add option to open new battle rooms on the right

---

js/client-battle-tooltips.js

Except the ones dependent on things like turn order. Also not Battery for now.

Show the effects of all abilities on base power

---

js/client-chat.js
js/client-mainmenu.js

* skip own username when cycling through candidates
* allow cancelling tabcompletion with Esc
* allow cycling through candidates in reverse in PMs as well
* allow tabcompletion everywhere in a multi-line message

Expand tabcompletion functionality

---

js/battle.js

Mark Illusion when it wears off

---

js/client-battle.js

[Report](http://www.smogon.com/forums/posts/7347321).

Ignore opponent/nicknames should include move target decisions

---

js/client-battle-tooltips.js

Tooltips: improve wording when move is weakened by ability

---

js/client.js

Change group type name when determining default order

Client: fix default order

---

js/search.js

Updates the viability of moves in Gen 1
Edit: Had a couple mistakes, fixed, working on squashing commits.
Edit2: Informed squashing on my end isn't necessary, is that the case?

Updated Gen 1 Viability

---

js/client-mainmenu.js

Congratulations, bumbadadabum!

Include bumbadadabum in major contributors credits

---

js/client-chat-tournament.js
style/client.css

Requires https://github.com/Zarel/Pokemon-Showdown/pull/3593.
Screenshots: <a href="http://i.imgur.com/5pbzXZ5.png">Joining</a> | <a href="http://i.imgur.com/RwczKqk.png">Waiting for a challenge</a>

Tournaments: add validate button

---

js/battledata.js

I talked most of this through with Zarel, just leaving this here first as a sanity check. Usage of this feature will be added once this is merged.

Add <pokemonicon> and <itemicon>

---

.travis.yml
githooks/build-indexes
package.json
test/test.ts

Not meant to be merged, essentially I want to have this pull request so that I could run Travis tests (feature involves Travis), the feature is not finished. Comments welcome however.

Add testclient unit tests

---

js/client-teambuilder.js

Use navigator.storage.persist in Opera 46

---

js/client-teambuilder.js
js/client.js

Essentially client side version of https://github.com/Zarel/Pokemon-Showdown/pull/3735

Set teambuilder sets to level 50 when server says so

---

test/test.ts

This I believe was a regression that was fixed by 2fac7642f63.

Test if Trump Card has 5 PP

---

js/client-topbar.js

Volume button icon not updating after unmute

---

githooks/build-indexes

In tandem with https://github.com/Zarel/Pokemon-Showdown/pull/3821

Add CAP NFE

---

package-lock.json

The client repo did apparently not have one yet.

Add package lock file

---

js/battle.js

Status moves are a bit of a kludge but I don't have any better ideas.

Set the item when a Z move is used

---

js/battle.js

Will be used for a secret project (staff link: http://www.smogon.com/forums/threads/3613633/).

Handle level changes in detailschange

---

js/client-battle-tooltips.js

Things that I wasn't sure about adding:
- STAB and Adaptability
- Weather and Terrain

Tooltips: Add more BP and stat modifiers

---

js/client-battle-tooltips.js

This is the last of the BP modifiers until I think of something else that I inevitably forgot.

Tooltips: Show BP modifiers from STAB and field effects

---

js/client-topbar.js

Quickly mute by double-clicking the sound button

---

js/client-battle-tooltips.js

It has a space in newer generations.

Tooltips: Fix Twisted Spoon

---

js/client-teambuilder.js

Do not merge; The code for Dual Wielding is not ready yet
[OMotM October](http://www.smogon.com/forums/threads/om-of-the-month-october-winner-dual-wielding.3616125/#post-7527701)

Teambuilder Hack for Dual Wielding

---

js/battle.js
js/client-battle-tooltips.js

Doesn't cover gen 1 Toxic/Leech Seed interaction or Tox -> Psn in earlier gens, but should otherwise cover everything.
Sidenote: What is hardcoreMode?

Tooltips: Track sleep and toxic turns

---

js/client-mainmenu.js

I recalled Zarel speaking of this before

Credits: Add urkerab to credits

---

style/client.css

some screenshots
https://prnt.sc/fnbfn3
hover:
http://prntscr.com/fnbhfy
http://prntscr.com/fnbjam

CSS – update teambuilder folderlist in darkmode

---

style/client.css

I assume Darkmode CSS would be entirely updated with this pull request. All the elements available in Light mode seems to be modified for Dark mode.
Dark mode could potentially be out of beta and to my mind, it would be better like this. That being said, what are your thoughts?
Screenshot (after update):
Screenshot (before/after):

Dark mode CSS – Teambuilder (Fix Some Colors)

---

.editorconfig

Editorconfig: Increase indent size to 3 spaces

---

data/graphics.js
js/client-battle-tooltips.js
js/client.js

Remove unexpected trailing commas

---

style/client.css

Several users have been complaining that a horizontal scroll bar is getting in the way in chat rooms and PM boxes, this fixes that.

Fix issues with horizontal scroll bar in Chrome

---

js/client.js
js/storage.js

This seems to work although I don't know whether it's something you want the testclient to be able to do.

Proxy POST requests in the testclient too

---

data/graphics.js

Properly update Earthquake animation

---

js/client-rooms.js

Requires https://github.com/Zarel/Pokemon-Showdown/pull/4014

Display subrooms in the join room tab

---

js/battle.js

Should fix #1062.
Let me know how I should be testing this... I tested locally and everything seems to work well.

handle unfound pokemon in -curestatus

---

js/client-mainmenu.js

As suggested halfway down [this forum post](http://www.smogon.com/forums/posts/7649603).

Make /challenge work in PMs

---

build-tools/build-indexes

Classify EV boosting items as "usually useless"

---

js/battle.js
js/client-battle.js
style/client.css

Always shows in collapsed mode, like for side rooms. Also handles small layouts.

Show userlist widget in battles

---

js/client-battle.js
js/client-chat.js

Creates a forfiet popup if a user tries to leave a room where there is an ongoing room game, and they are a player in the game.

Prompt the user to forfeit before leaving a game room

---

js/client-battle.js

Improve titles of uploaded replays

---

build
build-tools/update

~~Also update package-lock while I'm at it~~

Fix build script on windows

---

js/client-chat.js
js/client-topbar.js
js/client.js
lib/dispatcher.lib.php

They look like this: http://prntscr.com/jgb81s
Also see the corresponding server PR: https://github.com/Zarel/Pokemon-Showdown/pull/4663

 Integrate replays into the client

---

js/client.js

Dunno how I missed this before.

Unjoin old battle rooms if no replay is found

---

src/battle.ts

and maybe some other things that numericid is for

Battles: set BG and BGM properly

---

src/battle.ts

Reported [here](https://www.smogon.com/forums/posts/7816393) and [here](https://www.smogon.com/forums/posts/7835147).

Copy HP bar colour when Illusion wears off

---

build-tools/build-indexes
js/search.js

This should in theory work, but it didnt apply when I tested it via testclient.html. PRed anyways in case its something that needs to be applied main's (build script for teambuilder probably).

Move Mythical pokemon down in VGC teambuilder

---

js/client-topbar.js

This isn't a really serious CAPTCHA, somebody specifically targetting Showdown will evade it. However, it is an obstacle for blind people, so an alternative text-only CAPTCHA was introduced.

Add alt text for CAPTCHA

---

build-tools/build-indexes
build-tools/build-minidex
js/client-battle-tooltips.js
js/client-teambuilder.js
js/search.js

Add more teambuilder support for Let's Go

---

data/text.js

Reported [here](https://www.smogon.com/forums/posts/7967185/).

Fix magnitude activation

---

build-tools/build-indexes
js/search.js

This is necessary for Mega Sableye (Gen 6 and Gen 7) and Mega Metagross (Gen 6)

Add more doubles tier support (client side)

---

src/battle.ts

Not using `Array#some`, as I believe this part of the code has to work in old web browsers.

Fix PP counting for Trick Room/Pressure interaction

---

build-tools/build-indexes
js/search.js

This would be so much easier if we could just allow ZU teambuilder support directly via ZUBL and ZU

Change (PU) to Untiered

---

.eslintignore
.eslintrc.js
.gitignore
data/text.js
index.template.html
js/client-battle.js
src/battle-animations.ts
src/battle-dex.ts
src/battle-tooltips.ts
src/battle.ts
style/battle.css
style/client.css
testclient.html
tsconfig.json
tslint.json

(I just wanted to try out draft pull requests.)
This is what I've been working on for the client refactor for the past entire month.
I honestly got _really_ burnt out by this.

Tooltip refactor

---

src/battle-text-parser.ts

Example replay: https://replay.pokemonshowdown.com/gen7partnersincrime-870162468

Fix Protean and Color Change for replays

---

js/client.js

It wasn't actually opening in a new tab, go figure!

Fix "Open replay in new tab" link in replays

---

src/battle-tooltips.ts

Tooltips: Fix Flower Gift

---

build-tools/build-indexes

This was breaking my headless build script.

Add server build step to client build

---

js/client.js

[Reported here](https://www.smogon.com/forums/posts/8107508). I'm not sure why updateuser has it's first  element empty when it's a guest? Maybe figuring that out is the best solution.

Fix guests not showing in options

---

js/client-battle.js

See this bug report https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/page-41#post-8123818

Fix typing for move buttons in older gens

---

src/battle-tooltips.ts

I got reports about tooltips becoming kind of wonky when abilities were being suppressed (during my tests, it didn't work at all when viewing the player's own mons). In the process of trying to figure out why, I extracted the "which ability does this have?" logic and the "how do we display this abilty?" logic into separate functions, and changed it to fall back to server pokemon data more readily in case we're missing some information. This fixes some of the issues with suppression not being displayed properly. 
Is declaring an interface like this the cleanest option? I just wanted some ad-hoc data structure so I could separate the logic.
`abilityObj` is also kind of a lame name, but I wanted something that isn't too long while making it clear that this isn't just "an ability" but some …

Refactor ability display in tooltips

---

js/client-chat.js
js/client-mainmenu.js
src/battle-log.ts

Required by Zarel/Pokemon-Showdown#5469 for #1271.

Add support for a '/nonotify' message type

---

src/battle-animations.ts
src/battle-dex.ts

This was the only feature that was not able to be bypassed

Digimon Showdown Crys for CSS Bypass

---

.htaccess
js/client.js

> make <<replay>> link to the replays.pokemonshowdown.com
_'More common Suggestions' from [Suggestions for Pokémon Showdown](https://www.smogon.com/forums/threads/suggestions-for-pok%C3%A9mon-showdown.3534365/)_

Make <<replay>> link to the replay.pokemonshowdown.com

---

src/panel-rooms.tsx

The Preact client code looks really clean and readable, I like it :)

Sort rooms in preact client

---

js/client-chat-tournament.js
js/client-topbar.js
js/client.js

**Context:** [Tour notification improvements](https://www.smogon.com/forums/threads/tour-notification-improvements.3650626/)

Allow users to ignore just the tournament notifications

---

src/battle-log.ts

Regression introduced by 8e9bc3fe1e739a92c8b25075a6a0479ffc56e0aa

Include user's group in battle join message

---

js/client-chat.js
js/client.js

Closes #1300
It's called `roomGroup`  because `group` would shadow the server's response in `/cmd userdetails`.

Fix userpopup not showing room rank

---

build-tools/update

Looks like:
```
var Config = Config || {};
/* version */ Config.version = "0.11.2 (48762a86)";
...
```

Include commit hash in client config version

---

js/client-mainmenu.js
js/client.js

I don't //think// that making passed data override the cache should be an issue.
I don't really like the amount of cache invalidation that goes on, but short of hardcoding roomGroup to not cache I'm not sure what else to do.

Fix roomgroup in user popup

---

.eslintrc.js
js/client-teambuilder.js
src/battle-dex.ts

\- Only run `this.updateTeamList` when the user has 'finished' typing
\- Fix searching when Pokemon have nicknames
\- Only focus the search box when a search has been made

Improve teambuilder searchbox

---

js/client-mainmenu.js

Currently, an incoming challenge replaces the a pending challenge, causing the 'Challenge' button to turn into an 'Accept', resulting in accidentally accepting the challenge with the wrong team.

Don't overwrite issuing a challenge with accepting one

---

js/client-chat-tournament.js

Server: Zarel/Pokemon-Showdown#5581

Support player count in |tournament|start

---

src/battle.ts

Client side of https://github.com/Zarel/Pokemon-Showdown/projects/3#card-23723574

Make -copyboost copy the appropriate volatiles for gen 6 and later

---

src/battle-text-parser.ts

Fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-24204979

Fix messages for Queenly Majesty, Dazzling, and Damp

---

js/client-teambuilder.js
src/battle-dex-data.ts
src/battle-dex.ts

Fixes https://github.com/Zarel/Pokemon-Showdown/issues/3073
Makes progress towards https://github.com/Zarel/Pokemon-Showdown/issues/1355 (still need team validation and ball protocol/messages/animation etc)

Implement HP Type and Pokeball selector in Teambuilder UI

---

js/client-chat.js

It would not return a response if it's empty due to the faulty if condition

Fix /hl (list/roomlist) not returning response

---

src/battle-text-parser.ts

Otherwise you just get "Rayquaza is reacting to the Key Stone!"

Use fervent wish message for Rayquaza

---

js/client.js

https://www.smogon.com/forums/threads/make-saved-replays-default-to-https.3653062/

Make saved replays default to https

---

js/client-chat.js

(only mark it from updateuser messages)
clientside half of Zarel/Pokemon-Showdown#5675

Don't mark afk from rename messages

---

js/client-mainmenu.js

Useful to be able to tell when someone got blocked from PMing you, I think.

Show timestamp in nonotify PMs

---

js/client-chat-tournament.js
js/client-mainmenu.js
js/client-rooms.js
style/client.css

It doesn't affect the regular selector at all, everything
functions normally. Changes only occur upon toggle on.
All the features are kept, including the current selected team.
No data formatting changes made.
UI can and should be improved upon, that's for a later date. This is simply a POC, and something my PS friends wanted to see, so I cranked out the idea.

Added FolderToggle to the team selector for battling.

---

js/client-teambuilder.js

For zarel/pokemon-showdown#5752

Add Teambuilder support for Battle Spot Special 17

---

src/battle.ts

As per DaWoblefets bug collection pastebin.

Don't Baton Pass Laser Focus clientside

---

data/text.js

As discussed in pr [#5746](https://github.com/Zarel/Pokemon-Showdown/pull/5746) on the sim

Add heal fail for fullHp healing

---

js/client.js

[02:42:41] peach: name never starts with a rank symbol on initialization
[02:42:50] peach: and it never starts with a rank symbol in userdetails
[02:43:10] peach: so i think you can just delete the line i linked as well as L2467 and be fine

Fix name in trainer card

---

.htaccess
build-tools/build-minidex
js/client-mainmenu.js
js/client-teambuilder.js
js/client-topbar.js
replays/turn-image.php
replays/warstory.php
src/battle-animations.ts
src/battle-dex.ts
src/panel-mainmenu.tsx
src/panel-rooms.tsx
src/panel-teambuilder-team.tsx

More important for #1369 which will add alternative sprites for these generations

Standardize file/directory names in `sprites/`

---

js/client.js

Clientside part of Zarel/Pokemon-Showdown#5761

Clientside support for reporting a specific user

---

src/battle-animations.ts
src/battle-dex.ts

This effectives reverts f8001f3 by making it so that the sprites are
no longer transformed by 2x.

Stop scaling BW sprites

---

src/battle-tooltips.ts

Tooltips: Properly round displayed factors

---

data/text-afd.js
data/text.js

https://www.smogon.com/forums/threads/fix-grassy-terrain-battle-text.3652044/

Fix grassy terrain battle text

---

.eslintrc.js
js/client-mainmenu.js
style/client.css
style/client2.css

Placed the username from the header of pm-window in a span with the class "header-username", added a click event for it that brings up the challenge/chat window.
Adds feature requested in issue #1384.

Add "Challenge" and "..." buttons to top of chat windows

---

js/client-mainmenu.js

Would appreciate this getting merged and updated ASAP as its causing problems for help tickets.

Make userid an ID in the PM bar

---

js/client-battle.js

Paired with https://github.com/smogon/pokemon-showdown/pull/5946
This is the client support for Dynamaxing. Please leave feedback on this so I can get this implemented ASAP.
Still lacks support for minor events (eg: `-dynamax`)

Client support for dynamax

---

build-tools/build-indexes
js/search.js

this fixes dexited Pokemon not having movesets and also fixes Pokemon that are in the banlist like Kyurem-B still showing up as OU

Teambuilder: Fix learnset and tier issues for National Dex metas

---

js/client-teambuilder.js

Not sure if I'm missing anything from here, please let me know if I am.

Change teambuilder default gen to 8

---

js/client-teambuilder.js

Follows up https://github.com/smogon/pokemon-showdown-client/pull/1388

Maximize Attack IVs if Transform is the sole move

---

src/battle-tooltips.ts

After testing @Zarel's suggestion on #1448, I removed the else statement to make the code cleaner

Removing unnecessary else statement

---

js/client.js

It was missing some features like updating title bar, autojoins, etc.
Server PR: smogon/pokemon-showdown#6295.

Fix App#renameRoom

---

js/client-teambuilder.js

Add link back to Smogon analysis for sample sets

---

src/battle-animations.ts

need to pass this.mod as argument in order for it to work

Update battle-animations.ts for battle crys in digimon mode

---

build-tools/build-indexes
src/battle-dex.ts
test/dex.full-test.js

Required for #890 in past gens. Verified by patching in #1476 and adding to the Dex test (please merge it already...).

Add getType to ModdedDex and populate correctly

---

build-tools/build-indexes

client-side part of https://github.com/smogon/pokemon-showdown/pull/6475

Add teambuilder support for (NU)

---

js/client-chat.js
js/client-mainmenu.js

Stop htmlboxes from notifying

---

js/client-battle.js
replays/converter.lib.php
src/battle-animations.ts
src/battle-choices.ts
src/battle-dex.ts
src/battle-tooltips.ts
src/battle.ts

discovered in https://replay.pokemonshowdown.com/gen8challengecup1v1-1086619961-ba1cz8csx1k0n5ytxa5opldq0h6eys5pw

Fix missed instances of renaming Pokemon#species

---

data/text-afd.js
src/battle-dex.ts

Tinymaxing support

---

js/search.js
src/battle-dex-data.ts

Client-side portion of https://github.com/smogon/pokemon-showdown/pull/6611

Change inheritsFrom to changesFrom

---

js/client-chat.js

from https://www.smogon.com/forums/threads/news-command.3653715/

Implement a /news command

---

build-tools/build-indexes
js/client-teambuilder.js
style/client.css

Implemented as per [this suggestion](https://www.smogon.com/forums/threads/create-option-for-a-team-to-be-pokepasted-from-the-teambuilder.3663121/). I opted to use a `<form>` to make the request since pokepast.es' CORS setup prevents jQuery POST requests from PS! 
I spread the html out over multiple lines because I feel it is more readable; if you want me to revert that let me know.

Teambuilder: implement exporting to PokePaste

---

build-tools/build-indexes
js/search.js
src/battle-dex-search.ts

Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8455568

Fix DPP Doubles teambuilder

---

style/client.css

.tablist .button "width" isn't good on mobile 
how it currently looks: http://prntscr.com/sdygem
how it should look: http://prntscr.com/sdygnr

fix css visual bug on mobile

---

js/client-teambuilder.js

Clipboard text is not sanatized

Sanatise teambuilder clipboard

---

js/client-teambuilder.js

This fixes issue #1526 for me.
(You might not need both calls but I just copied it from another place in the code to be sure.)

Prevent Enter from crashing during Pokémon level entry

---

js/client.js

With https://github.com/smogon/pokemon-showdown/pull/6728

Increase autojoin limit to 15

---

js/client.js

Requested [here](https://www.smogon.com/forums/threads/3659047/).

Don't require desktop notifications for disconnections

---

js/client-mainmenu.js

As I discussed with Zarel on Discord.

Use JSON API for addNews()

---

src/battle-tooltips.ts

This annoyed me while testing other changes, so I fixed it.

Fix linter warning in battle-tooltips.ts

---

js/client-chat.js
src/battle-log.ts

Implements [this suggestion](https://www.smogon.com/forums/threads/add-left-after-joined.3666495/#post-8518430).

Clean up join/leave messages

---

js/client-battle.js
src/battle.ts

Requested by @DaWoblefet: https://www.smogon.com/forums/threads/options-for-automatically-doing-ionext-timer-on-ignoring-spectators-etc.3652588/.

Add persistent ignore specs and auto timer toggles

---

js/client-battle.js

https://www.smogon.com/forums/threads/show-team-when-trapped.3666123/#post-8518274

Continue to show the player's team while trapped

---

config/config-example.inc.php

Add autolock_ip to the example configuration

---

js/client-battle.js
src/battle.ts

Users seem to want this as well /shrug

Add a persistent auto ignore opponent toggle

---

js/client.js

Client support for smogon/pokemon-showdown#7015.

Support renaming battles

---

js/client-chat.js
src/battle-log.ts

Client-side support for https://github.com/smogon/pokemon-showdown/pull/7065.

Support /cleartext

---

action.php
customcss.php
lib/ntbb-session.lib.php
replays/battle.php
website/index.php
website/interstice.php
website/intro.php
website/news/embed.php
website/pages/rng.md
website/resetpassword.php
website/servers.php
website/style/wrapper.inc.php
website/theme/wrapper.inc.php
website/usermodlog.php
website/users.php
website/usersearch.php

This is migrating the changes proposed in smogon/pokemonshowdown.com#2 to the new location of the website code.

Support configurable URLs in the website

---

js/client-chat.js

Client-side support for https://github.com/smogon/pokemon-showdown/pull/7082.

Correctly display reveal button for /cleartext

---

build-tools/build-indexes
js/client-teambuilder.js
js/storage.js
src/battle-dex-data.ts
src/battle-dex-search.ts
src/battle-dex.ts
src/battle-tooltips.ts
src/panel-teambuilder-team.tsx
src/panel-teamdropdown.tsx

i need help with sprites support before this or the server-side part of this (https://github.com/smogon/pokemon-showdown/pull/7001) gets merged @Zarel

Handle Gigantamaxing properly

---

src/battle-log.ts
src/battle.ts

Implements [this suggestion](https://www.smogon.com/forums/threads/turning-on-ignore-spectators-shouldnt-prevent-me-from-seeing-my-opponents-leave-join-messages.3667838/).

Don't ignore player joins/leaves

---

build-tools/build-indexes
src/battle-dex-search.ts

Improve berry search/Hidden Power search display for past gens. I know Zarel you wanted me to edit my original pull req initially, then said you could do it, but here it is done for you.

Improve past gen item and move viability

---

js/client.js

The way I did it is kind of hacky. Going with Zarel's preference to avoid new dependencies.

Add button to copy replay link to clipboard

---

js/client-battle.js
js/client-chat.js
js/client-ladder.js
src/client-main.ts

Client side solution in lieu of smogon/pokemon-showdown#7239.

Use /noreply for leaving rooms

---

website/pages/staff-de.md

I translated the staff faq site to german. GPed by asgdf.

Translate staff faq to german

---

js/client-topbar.js

According to Marcell this is the proper form

Language UI: Deutsche => Deutsch

---

website/pages/ladderhelp-de.md

I translated the faq ladder site to german.

Translate faq ladder to german

---

website/pages/staff-de.md
website/pages/staff.md

As per [this bug report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-27#post-8586989).

Website: Fix lock duration in the Staff FAQ

---

website/pages/faq.md

Changes courtesy of Zodiax and Iyarito.

Website: Update the FAQ page

---

website/usersearch.php

`$ip` isn't defined here - the correct behavior is to search by the userlist we just fetched.

Website: Fix bug in usersearch

---

js/client-topbar.js
src/panel-topbar.tsx

This was meant to be done with my original battle privacy PR but I forgot :/

Fix format display for hidden battles

---

js/client-mainmenu.js

Ideally we can refactor commands to specify whether they apply in PMs, rooms, or both. Is that something that Preact is doing?

Improve errors when using room commands in PMs

---

js/client.js

Persist blocking PMs by rank

---

js/client.js

https://www.smogon.com/forums/threads/dming-oneself.3671623/

Allow users to PM themselves with the Chat button

---

src/battle-log.ts

Pretty sure i did this right? Works in testing. Also not sure if the source should be `src` or just `name` - went with `src` for now.

Add a custom html tag for namecolors

---

js/client-chat.js

None of these commands support this, so instead of erroring or anything similar, the best solution seems to be this: let the text through to the server and let it handle the "this can't be broadcasted" error.

Don't allow ! for client commands

---

build-tools/build-indexes

This will be necessary for one of the November RoA spotlight ladders

Add support for Gen 3 Doubles formats

---

js/client-mainmenu.js
js/client-teambuilder.js
js/storage.js
style/client.css

http://prntscr.com/mbubum
Max box size is 24, the same as the maximum team size for custom game.

Teambuilder: Implement Box system

---

website/pages/faq.md

https://www.smogon.com/forums/threads/translating-more-commands-for-ps.3653753/page-4#post-8651047

Website: Clarify the FAQ

---

build-tools/build-indexes

client side part of https://github.com/smogon/pokemon-showdown/pull/7680

Adjust support for building text files

---

style/client.css
style/client2.css

client part of https://www.smogon.com/forums/threads/3642984/page-6#post-8648367

Add CSS for subtle notifying buttons

---

src/battle-tooltips.ts

Should fix [this bug](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8619891), if only from the perspective of the player controlling the affected Pokemon.

Tooltips: fix phantom Sticky Barbs for players

---

src/battle-dex-data.ts
src/battle-tooltips.ts

Looks like HJK's recoil property got renamed server-side, but not client-side.

Tooltips: Show Reckless boost for High Jump Kick

---

src/battle-log.ts

Adding a <spotify> tag to embed song from Spotify to ps.
Example: 
Just like <youtube> tag, it will play songs on ps.

Add <spotify> tag

---

js/storage.js

fixes https://github.com/smogon/pokemon-showdown/issues/7736

Downloadable client: Save boxes as boxes

---

src/battle-dex.ts

I also rearranged them alphabetically to organize them a bit. Here are the cries themselves (credit to dataminer mattyoukhana (@sora10pls), I just converted to mp3 and added the names of the mons): https://drive.google.com/drive/folders/1DWp3k2jsViSH64ivH-2y1EYQ5sqoPGwG

Update forme cries

---

src/battle-log.ts
website/pages/privacy.md
website/pages/rules.md

Comply with Google API ToS properly 

---

js/client-chat.js

I added the /battlerules for the help challenge and an alias for help (h) 
https://www.smogon.com/forums/threads/add-custom-rules-page-to-help-challenge.3674780/

Improve /help challenge for custom rules

---

website/pages/rng-de.md

I translated the rng faq to german.

Translate rng faq to german

---

js/client-chat.js

This removes the need for a comma after `add` and `delete` in `/hl add/delete` and makes error messages display as red.

Refactor /highlight

---

js/client-topbar.js

PR for this suggestion: https://www.smogon.com/forums/threads/option-to-view-password-upon-logging-in-registration.3674896/

Add "Show password" button

---

js/client-battle.js
js/client-mainmenu.js
js/client-teambuilder.js
js/client-topbar.js
js/client.js

Anywhere where there's a form with more than one button, I added `type="button"` to all the other buttons. (Unless I missed some...) In particular this should fix issue #1717.

Explicitly mark more non-submit buttons with their type

---

js/client-chat.js

:s
(currently attempting to broadcast !help mostly breaks.)

Fix broadcasting /help

---

js/client.js

This makes it so that if a server's name includes the name of a banned server, it's also treated as banned.
(reason for this explained elsewhere)

Improve banning servers

---

build-tools/build-indexes
src/client-main.ts
src/panel-mainmenu.tsx
src/panel-topbar.tsx
src/panels.tsx
testclient-beta.html

This is stalled at partially done so I guess I publish what I have so far.
Of note is that mini-windows (News, PMs) can now be dragged into the tabbar, where they'll become regular tabs.

(Preact) Partial drag/drop panel tab rearranging

---

src/battle-log.ts

I don't like the replace hack but i'm not sure how else to ensure it doesn't get escaped.

Support a twitch embed

---

replays/index.php

Removes replays with slurs, inappropriate usernames, permabanned users, and/or runMinor errors from the homepage

Remove objectionable replays from the homepage

---

website/js/ladder.js
website/users.php

Requested by aeonic.
Dumb hack, but there isn't really a better way to do this, is there?

Add a button to copy/paste password reset urls

---

js/client-chat.js
js/client-ladder.js
js/client.js
src/battle-log.ts

Might not be the best way to do this, but for some reason the global event listener on `app` didn't work, so i had to trickle it down into ConsoleRoom and HTMLRoom.

Support using form elements to send commands

---

src/battle-log.ts

@mia-pi-git can you check and make sure this doesn't break your changes?

Fix links not opening in a new tab

---

js/client.js
src/battle-dex-search.ts

Add more support for National Dex

---

src/battle-log.ts

Requested, fairly easy, and useful.

Battle-Log: Support custom start times in youtube tags

---

js/client-battle.js
js/client-teambuilder.js
js/search.js
js/storage.js
src/battle-animations.ts
src/battle-choices.ts
src/battle-dex-search.ts
src/battle-dex.ts
src/battle-searchresults.tsx
src/battle-tooltips.ts
src/battle.ts
src/panel-battle.tsx
src/panel-teamdropdown.tsx
src/panel-topbar.tsx

https://discord.com/channels/630837856075513856/630845310033330206/830661509264048158

Update Dex API to match server API

---

js/client-chat.js
js/client-mainmenu.js
js/client.js

https://www.smogon.com/forums/threads/ignore-improvements.3682273/

Improve /ignore

---

js/client-chat.js

Allow commands in battle when ignoring spectators

---

src/battle.ts

Sample replay: https://replay.pokemonshowdown.com/gen8anythinggoes-1323722693

Tooltips: Display Quick Claw after activation

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/show-grassy-terrains-effect-on-the-3-ground-moves.3683343/
No point in displaying for Magnitude since it doesn't a base power anyway, since it can't be known before the turn and all.

Tooltips: Halve Earthquake, Bulldoze BP in Grassy Terrain

---

build-tools/build-indexes

NatDex UUBL got changed to be placed in tags, and the client didn't update to reflect those changes. Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-54#post-8842754

Fix NatDex Teambuilder Table for UUBL

---

js/client-teambuilder.js

Adds level support for Doubles LC (and CAP LC if it starts existing)

Teambuilder: Add more LC level support

---

src/battle-log.ts

Regrets. Many, many, many regrets.

Battle log: Don't autoplay twitch tags

---

build-tools/build-indexes

Just had to move uubl above ou in the return order. Probably should've done this the first time

Fix nduubl again

---

build-tools/build-indexes
js/search.js
src/battle-dex-search.ts
src/battle-dex.ts
src/battle-tooltips.ts

Utilizes `Dex.getDescs` to get descriptions, since directly accessing `desc` or `shortDesc` doesn't seem to work.

Fix old gen teambuilder bugs

---

sprites/gallery-test.html
sprites/scene-test.html

They were still using `Dex.getSpecies`

Fix scene-test and gallery-test

---

src/battle-animations-moves.ts

for smogon/pokemon-showdown#8301

Add animation aliases for Shell Side Arm categories

---

js/client-teambuilder.js

Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8849061

Teambuilder: Fix Gen VII analysis links

---

src/battle-tooltips.ts

https://replay.pokemonshowdown.com/gen8doublescustomgame-1340141962-gvxpu552m9cuh6zkowlirceqgk7qisrpw
Before:
After:

Tooltips: Don't display Illusion hint on 4+ moves with Mimic

---

src/battle.ts

https://replay.pokemonshowdown.com/gen8doublescustomgame-1340122046-63pyh53drcuoeesx1okhx3gi9iseffppw
Before:
After:

Fix Transform's interaction with Gigantamax

---

js/client-mainmenu.js

Challenge : Fix notification sound

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8521042

Tooltips: Don't show sandstorm Sp. Def boost after type change

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-40#post-8716218

Tooltips: Don't show stat boosts from items if Magic Room is active or if the Pokemon is affected by Embargo

---

build-tools/build-indexes

so this works, read the proposal there for details: https://github.com/smogon/pokemon-showdown/pull/8336

Add OU by technicality to RBY

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8747482

Fix transformed Pokemon showing wrong speed range

---

src/battle-text-parser.ts

https://github.com/smogon/pokemon-showdown/projects/3#card-61195884

Fix Mummy showing duplicate messages on failure

---

js/client-teambuilder.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8871200

Fix AltFormPopup and setForm

---

src/battle-animations.ts
src/battle-dex-data.ts
src/battle-tooltips.ts
src/battle.ts

https://www.smogon.com/forums/threads/alter-don%E2%80%99t-show-weather-backgrounds-if-air-lock-cloud-nine-is-in-effect.3684932/
Works for the most part, except for the fact that it doesn't immediately update the weather once air lock leaves, and I don't know the right place to run `updateWeather` to fix that.

Show Air Lock/Cloud Nine activation in battle scene

---

website/ladder.php

Support specifying prefixes in ladder/*.json requests

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8890803

Tooltips: Check if user is grounded for Terrain Pulse

---

js/client-teambuilder.js

https://www.smogon.com/forums/threads/import-pokepaste-titles-as-the-title-of-a-given-team.3671574/

Set team name to pokepaste title when importing

---

src/battle-log.ts

More convenient and generally useful feature.

Support custom width/height attributes in twitch tags

---

src/battle-dex-data.ts
src/battle-tooltips.ts

Accounts for smogon/pokemon-showdown#8445

Update move flag names

---

js/client.js
src/client-main.ts

https://www.smogon.com/forums/threads/section-leader-updates-proposal.3687279/

Place Section Leaders appropriately in default groups

---

src/battle-animations.ts
src/battle-text-parser.ts
src/battle.ts

Server Side: smogon/pokemon-showdown#8472

Gen I-II: Fix Mist text

---

js/client-teambuilder.js
src/battle-dex-search.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8980765

Fix bug with Teambuilder button and small change to #1860

---

src/battle.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8986236

Tooltips: Fix Heal Bell getting affected by Pressure

---

src/battle-dex-search.ts

Super minor fix only relevant to dex.pokemonshowdown.com

PS Dex: Fix CAPs under Glitch category

---

js/client-teambuilder.js

I could've sworn I'd added this line; my bad
pasteNotes is a null, leading to the upload failing
Can someone merge this in

Teambuilder: Fix bug caused due to #1882

---

js/client-teambuilder.js

I thought this would be a cool thing to add to go along with #1882. Code will have to be updated once actual notes gets implemented, but I imagine it'll be a while before those come out.

Teambuilder: Set format when importing Pokepaste

---

sprites/scene-test.html
src/battle-animations.ts
src/battle-dex.ts
src/battle-tooltips.ts

In some cases `resourcePrefix` is used, but `fxPrefix` would be more appropriate.

Update fxPrefix for gender sprites

---

website/pages/faq-ja.md

Fix link on [faq-ja.md](https://github.com/Dirain1700/pokemon-showdown-client/commit/44036d43bf860f18585edb8b876bee1999fef6f9).
There is no more file changes so I'm ready to merge.

Fix link on faq-ja.md

---

build-tools/build-indexes
js/client-teambuilder.js
src/battle-dex-data.ts
src/battle-dex.ts

I also slightly refactored how the Let's Go and BDSP mods are handled by the dex and build-indexes, making it easier to add mods to the dex in the future.

Teambuilder: Set Arceus forme item to Plate in Gen 4-6 & BDSP

---

src/battle-dex-data.ts

Fixes a small oversight from my other pr about required items

Teambuilder: Fix automatically setting required items

---

src/battle-dex-search.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9048414

Teambuilder: Fix CAP LC & BDSP Hackmons

---

js/client-chat.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9040224

Fix /clearignore when run without a target

---

src/battle-dex-search.ts

Teambuilder: Show Restricted Legendaries for VGC 2022

---

build-tools/build-indexes

First time contributing to this repo! Let me know if there's anything else I need to do for this PR.

Write learnsets to JSON file

---

website/pages/rules-fr.md

Reported by Zoaw, approved by Teclis.

Rules: Correct French translation

---

js/client-teambuilder.js
src/panel-teambuilder.tsx

Suggestion from [this thread](https://www.smogon.com/forums/threads/team-counter.3696070/)

Add a team counter for folders

---

src/battle-dex.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9090255

Teambuilder: Show gen 5 sprites when old graphics are preferred

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9099699
Before
After

Tooltips: Fix small display issue in Gen 2

---

js/client-topbar.js

https://www.smogon.com/forums/threads/background-image-dragging-dropping.3695386/
Demo of how it works
https://user-images.githubusercontent.com/32044378/148441191-39a391f5-35da-4ca9-806e-c782e94b74bc.mp4

Add confirmation popup when dragging in image

---

js/search.js
src/battle-searchresults.tsx
src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9093024

Fix PP display for some moves in Gen 1-2

---

src/battle.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9096732
I may or may not have erroneously suggested to remove this hardcode in #1910

Tooltips: Fix Sticky Web from getting affected by Pressure

---

website/pages/rules-pt.md

Fixed a small grammar mistake that was oversighted when the translation was done

Change to the Portuguese translation of rules

---

js/client-topbar.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9078587

Fix visual bug with volume sliders

---

src/battle.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9143591

Don't remove type changes for Gmax forme changes

---

src/battle-dex.ts
src/battle.ts

Server Side: smogon/pokemon-showdown#8685
I thought of this as soon as my other pr got merged.
Should I get rid of the changes from my other pr? Or should I leave them in for old replays?

Support Gmax sprites without formechange

---

src/battle-dex-data.ts
src/battle-tooltips.ts
src/battle.ts

https://www.smogon.com/forums/threads/update-mouseover-speed-stat-for-scalemons.3679856/

Tooltips: Support Scalemons Mod

---

js/client-battle.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9170998

Fix Ultra Burst text after selecting a move

---

build-tools/build-indexes

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9191547

Teambuilder: Fix unsketchable moves in past gens

---

src/battle.ts

client side stuff for smogon/pokemon-showdown#8569

Tooltips: Properly Support Gen 3-4 Knock Off

---

js/client-mainmenu.js

https://www.smogon.com/forums/threads/dont-disable-accept-button-from-a-challenge-if-you-clicked-accept-without-a-team-for-the-format.3702601/

Change when accept challenge button gets disabled

---

build-tools/build-indexes

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9274741

Teambuilder: Fix Dragon Scale category in Gen 2

---

js/client.js

Useful feature that's already been requested a lot.

Add a friend/unfriend option to the UserOptions popup

---

src/battle-dex-search.ts

still struggling with how to make polteageist antique have celebrate in its learnset, might end up having to just hardcode its learnset 😢

Fix Sinistea's teambuilder learnset

---

js/client.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9330571

Stop caching user status

---

build-tools/build-indexes
src/battle-dex-search.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9353727

Teambuilder: Fix illegal moves showing in Nintendo formats

---

js/client-teambuilder.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9356151

Teambuilder: Fix incorrect stat label in gen 1 after clicking guessed spread

---

src/battle.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9371159

Reset Sleep/Toxic turns after Healing Wish

---

src/battle-text-parser.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9403459

Fix incorrect text for Armor Tail

---

src/battle.ts

For smogon/pokemon-showdown#9024

Ensure that only Psych Up copies volatiles with -copyboost

---

src/battle.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9404420

Check [from] effect for switches instead of lastMove

---

js/client-rooms.js

Requested by US. This PR makes it so there's a button at the bottom of the roomlist you can click to see rooms marked as hidden. Server-side changes to follow.

Add support for showing hidden rooms in their own room list category

---

src/battle-dex-data.ts
src/battle-tooltips.ts
src/battle.ts

Also added my changes from #2006 and #2008 here because I had some code from those that was needed here.

Tooltips: Add Gen 9 stuff

---

js/client-teambuilder.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9410533

Fix Happiness/HP type not being editable in Gen 9 natdex

---

js/client-battle.js
src/battle.ts

Client side portion of smogon/pokemon-showdown#9035
Needs a lot more testing, but it is worthwhile to review now.

Add support for Revival Blessing

---

js/client-chat-tournament.js

Pr for https://www.smogon.com/forums/threads/highlight-when-you-have-to-play-in-a-tournament.3710289/

Add tournament challenge notification sound

---

src/battle-tooltips.ts
src/battle.ts

Implementing: https://www.smogon.com/forums/threads/updating-the-power-of-moves-like-rage-fist-dynamically.3711423/
Hopefully I haven't missed any edge cases. I had to implement it differently than the server.

Rage fist tooltip

---

src/battle-dex-search.ts

Quality of life change for one of the only doubles based OMs.

Teambuilder: Use doubles tiers for Partners in Crime

---

build-tools/build-indexes
src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9422077

Fix Eviolite NFE check for past gens

---

js/client-battle.js
js/client-chat.js
js/client-topbar.js

Hi, i create this pull request for https://www.smogon.com/forums/threads/have-a-are-you-sure-you-want-to-exit-this-room-popup-when-you-click-the-x-to-leave-a-chat-room.3672414/

Confirmation before leaving a room

---

src/battle-animations-moves.ts
src/battle-animations.ts
src/battle-text-parser.ts
src/battle.ts

Some moves (namely tera blast) have dynamic move animations, but I wanted to at least get animations in for moves and then work on doing dynamic ones afterward.

Add Gen 9 move animations

---

js/client-teambuilder.js

PS seems to recognize Pokepaste data as an [object](https://user-images.githubusercontent.com/96159984/206826933-d3f94f50-5684-4bd4-9840-4fb74e1e72e5.png) now, so JSON.parse errors out when trying to import something.

Teambuilder: Fix import from Pokepaste

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9431252
I would rather just use IDs for everything instead of hardcoding this but I didn't feel like refactoring all that.

Fix Blizzard not showing 100% accuracy in Snow

---

src/battle.ts

Not super familiar with client code, but I think this should cover things like sub, belly drum, etc..
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-97#post-9431398

Fix rage fist counter triggering from substitute

---

js/client-ladder.js

Necessary to bring chatlog to parity with /roomlog. Supersedes https://github.com/smogon/pokemon-showdown-client/pull/1645 (Annika said it was fine to take this over).

Add a scroll message type for pages

---

src/battle-animations.ts
src/battle-tooltips.ts
src/battle.ts

Server Side: smogon/pokemon-showdown#9168

Support viewing Tera Types for inactive Pokemon

---

src/battle.ts

To be merged with [server#9204](https://github.com/smogon/pokemon-showdown/pull/9204)

Don't show revived active Pokemon immediately

---

build-tools/build-indexes
build-tools/build-learnsets
build-tools/build-minidex
test/check-filenames

Will get this merged when it's time for esbuild to go live.

Update to handle esbuild migration

---

src/battle.ts

Merge with [server#9229](https://github.com/smogon/pokemon-showdown/pull/9229)
~~TODO: Illusion shenanigans~~ Works fine already

Support Terastallization in switch details

---

src/battle-animations.ts
src/battle.ts

For smogon/pokemon-showdown#9245

Add formatted volatile tag for Glaive Rush

---

src/battle.ts

* Updates details to match the Pokemon no longer being Terastallized when it faints
* Fix Illusion Pokemon Terastallizing

Fix Terastallized Pokemon tracking

---

js/client-mainmenu.js

Client side for https://www.smogon.com/forums/threads/more-integration-with-smogon-tournaments.3711859/
Approved by US.

Add a tournaments button to the homepage

---

src/battle-tooltips.ts

Tooltips: Hide Tera Type for Terastal Clause

---

src/battle-tooltips.ts
style/battle.css

The current- and modified tooltips, from left to right, respectively:

Tooltips: Align tera reminders with types, Space

---

src/battle-tooltips.ts
src/battle.ts

Client support for smogon/pokemon-showdown#9328

Tooltips: Don't show drop for same ruin abilities

---

src/battle.ts

For smogon/pokemon-showdown#9461

Remove added type upon Terastallization

---

src/battle-dex.ts
src/battle.ts

Upon switching or fainting, the cry of hero palafin will now play, but still nothing plays during terastallization

Palafin Hero Cry on switch-in

---

index.template.html
src/battle-log.ts
website/pages/privacy.md

Three main issues have been resolved here.
1 - Now, only one YouTube player can ever be on screen at once. Old ones are removed when the new one is added. [relevant section - III.C 1](https://developers.google.com/youtube/terms/developer-policies#c.-implementing-youtube-features)
2 - We didn't properly disclose we were using YouTube API services [relevant sections - III.A 2 B](https://developers.google.com/youtube/terms/developer-policies#a.-api-client-terms-of-use-and-privacy-policies)
3- We didn't disclose it allowed third-party content/advertisements. [relevant sections - III.A 2 F](https://developers.google.com/youtube/terms/developer-policies#a.-api-client-terms-of-use-and-privacy-policies)
(re: index.template.html change, terms state the privacy policy must be prominently displayed …

Bring us into compliance with YouTube API terms

---

website/pages/staff.md

[very serious comment]
The text in the first paragraph says "A full staff list can be found below." but there was no staff list below lmao.

Add a link to the staff list

---

src/battle-text-parser.ts
src/battle.ts

For smogon/pokemon-showdown#9832

Populate Tooltips with information from OTS

---

src/battle-tooltips.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9692406

Tooltips: Fix Low Kick BP in Gen 1/2

---

js/client-mainmenu.js

well actually "No formats found" whatever. Maybe it shouldn't rely on `bufs` being empty?

Fix formats not found message not appearing

---

play.pokemonshowdown.com/js/client-mainmenu.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9849881

Fix unstyled buttons when "Group by Folders" is unchecked

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

Made the animations for the various types of Tera Blast various kinds of beam or blast moves (or in the case of Grass, the closest thing to that). Also changed base Tera Blast to Swift because its animation fits base Tera Blast better than Scald's does.

Modified Tera Blast animations

---

play.pokemonshowdown.com/src/battle-text-parser.ts

Server: smogon/pokemon-showdown#9967

Support Tera Shift message

---

build-tools/build-indexes

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9881091

Teambuilder: Fix National Dex item table

---

build-tools/build-indexes
play.pokemonshowdown.com/js/search.js
play.pokemonshowdown.com/src/battle-dex-search.ts

https://www.smogon.com/forums/threads/let-users-filter-by-tier-in-old-gens.3732059/
Also added ZU and ZUBL as filters.

Teambuilder: Allow Tier filters on old gens

---

play.pokemonshowdown.com/js/client.js

This fixes the button in `/chatlog` refreshing your browser if you click it too fast

Don't crash when spamming join

---

play.pokemonshowdown.com/src/battle-tooltips.ts

Fixes https://www.smogon.com/forums/threads/hadron-engine-oricalcum-pulse-show-wrong-modifier-in-tooltips.3733481/

Tooltips: Fix Hadron Engine/Orichalcum Pulse modifier

---

play.pokemonshowdown.com/js/client.js

Pr for https://www.smogon.com/forums/threads/bug-report-undefined-usernames-on-replays-viewed-through-the-simulator.3733700/

Client: Fix Undefined usernames on replays

---

play.pokemonshowdown.com/js/client-teambuilder.js

https://www.smogon.com/forums/threads/bug-report-teambuilder.3734292/
https://www.smogon.com/forums/threads/teambuilder-should-stop-you-from-creating-folders-that-contain.3657717

Teambuilder: Don't allow `|` in folder names

---

play.pokemonshowdown.com/js/client-battle.js

Server Side: smogon/pokemon-showdown#10221
https://www.smogon.com/forums/threads/rematching-with-custom-rules.3672547/
https://www.smogon.com/forums/threads/when-clicking-rematch-have-it-re-challenge-with-mods-if-there-are-any.3715507/

Support rematching with custom rules

---

play.pokemonshowdown.com/js/client-topbar.js

PR for: https://www.smogon.com/forums/threads/have-option-use-bw-sprites-instead-of-xy-models-say-use-2d-sprites-instead-of-3d-models.3741313/

Clarify 2D/3D Model Options

---

build-tools/build-indexes
play.pokemonshowdown.com/src/battle-dex.ts

https://www.smogon.com/forums/threads/ddp-natural-gift-shows-wrong-base-power-in-tooltip.3744325/

Override Fling and Natural Gift data for items in past gens

---

build-tools/build-indexes
play.pokemonshowdown.com/src/battle-dex-search.ts

https://www.smogon.com/forums/threads/bloodmoon-ursaluna-egg-moves.3745741/

Properly display legal egg moves in teambuilder

---

play.pokemonshowdown.com/src/battle-dex-data.ts
play.pokemonshowdown.com/src/battle-dex-search.ts

https://www.smogon.com/forums/threads/bug-report-teambuilder.3746541/ This bug was caused by my assumption that the client gets changesFrom the same way the server does.

Fix teambuilder move display for formes

---

play.pokemonshowdown.com/src/battle-dex-search.ts

No crash here, but a change made to sync the teambuilder after a server-side change to fix a validator crash.

Fix crash (client)

---

build-tools/build-indexes
play.pokemonshowdown.com/src/battle-dex-data.ts
play.pokemonshowdown.com/src/battle-dex-search.ts

Client-side for https://github.com/smogon/pokemon-showdown/pull/10407

Convert noSketch to move flag

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

Create Supercell Slam animation

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

Add animation for Fishious Rend

---

play.pokemonshowdown.com/js/client-chat.js

Self-explanatory. Will merge in a day or so if no one has any complaints, so please eyeball sooner rather than later.

Support tabcompleting commands

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

Stomping Tantrum:
https://github.com/user-attachments/assets/d8b512ca-b6a1-4697-ab68-61da7ad6b363
Temper Flare:
https://github.com/user-attachments/assets/44e5d76a-e88e-4f72-858c-57c12308034b

Modify animation for Stomping Tantrum, add one for Temper Flare

---

play.pokemonshowdown.com/js/client-teambuilder.js

No idea how this worked locally before; tested again and works about right now

Teambuilder: Pass `this` context correctly to updateTeamList

---

play.pokemonshowdown.com/js/client-teambuilder.js

Reopened #2283 after closing it due to a mistake on my part.

Fixed missing HTML sanitization (again)

---

play.pokemonshowdown.com/src/battle-dex-search.ts

https://www.smogon.com/forums/threads/bug-report-unsure.3752081/
See also https://github.com/smogon/pokemon-showdown/pull/10584

Fix searching for Ursaluna-Bloodmoon by moves

---

play.pokemonshowdown.com/src/battle.ts

https://www.smogon.com/forums/threads/bug-report-client.3745677/

Fix Quark Drive/Protosynthesis visual bug when losing ability

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/73861b60-72f4-473a-a3d2-1388696b462b

Add animation for Burning Bulwark

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/93a82edd-41a3-45e8-b5b7-6116fc4d7905

Add animation for Tera Starstorm

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/99f19198-2506-42ee-96dc-1f95c0b2b71b

Add animation for Thunderclap

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/4b23e36f-e0c9-418d-b3df-b4d46dcda029

Add animation for Mighty Cleave

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/9df8868a-0d92-4555-a1de-ca4834b7d7c0

Modify animation for Spirit Break

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/fe97090e-2bfe-4f0d-930e-4de6bb510344

Modify animation for Stone Axe

---

play.pokemonshowdown.com/js/client-mainmenu.js
pokemonshowdown.com/news/manage.php

I used the syntax of `[psicon thing="object"]` to somewhat mirror the html syntax and for ease of replace for regex

News: Add support for minisprites

---

play.pokemonshowdown.com/src/battle.ts

Fixes https://www.smogon.com/forums/threads/terastal-morpeko-wrongly-assumed-illusion.3755333/
The forme stays this time. No Illusion.

Fix Morpeko forme locking

---

play.pokemonshowdown.com/js/search.js

Abilities are not being overwritten by those of the mods. Also, Let's Go.

Fix the Abilities column for mods

---

build-tools/build-indexes
play.pokemonshowdown.com/src/battle-dex-search.ts

Requested by Teh in the Smogon Discord

Add teambuilder support for Gen 3 UUBL (and every other UUBL tier)

---

play.pokemonshowdown.com/src/panel-battle.tsx
play.pokemonshowdown.com/src/panel-chat.tsx

For the "Download Replay" button, instead of writing a separate function, I included the logic directly inside the onClick event, as I thought this button would be the only one needing it.

Preact: Add controls after battles

---

play.pokemonshowdown.com/src/battle-log.ts

Added `class="button"` to the button and fixed a small bug

Fix /invite styling

---

play.pokemonshowdown.com/preactalpha.template.html
play.pokemonshowdown.com/testclient-beta.html

I think I changed this in the right places

Preact: Add utilichart.css

---

play.pokemonshowdown.com/src/battle-log.ts
play.pokemonshowdown.com/src/client-main.ts
play.pokemonshowdown.com/src/panel-chat.tsx

Implements basic functionality of the ignore commands. I also added the ^ (prize winner) rank to the ignorable ranks since the inability for this rank to be ignored has been [reported as a bug](https://www.smogon.com/forums/threads/ignoring-prize-winners.3759839/).

Preact: Add /ignore and /unignore

---

play.pokemonshowdown.com/src/panels.tsx

this prevents popups opening twice

Preact: Fix popup bug in testclient

---

play.pokemonshowdown.com/src/client-main.ts
play.pokemonshowdown.com/src/panel-chat.tsx

for the /rank command, i mostly copy pasted the code from old client, it uses jquery ($) to request for the userrank details.
let me know if we dont want that

Preact: Add /showjoins and other client side commands

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/2735fe6f-2bc4-47bc-a7a8-fee6f6ce417d

Add animation for Malignant Chain

---

play.pokemonshowdown.com/src/panel-popups.tsx

Adds options to change avatar, status in options panel.

Preact: Add avatar and status options

---

play.pokemonshowdown.com/src/battle-log.ts
play.pokemonshowdown.com/src/client-main.ts
play.pokemonshowdown.com/src/panel-battle.tsx
play.pokemonshowdown.com/src/panel-mainmenu.tsx
play.pokemonshowdown.com/src/panel-popups.tsx

for the highlight stuff, i will redo it at the time of implementing the `/highlight `command.

Preact: Add more user preferences in options menu

---

play.pokemonshowdown.com/src/panel-popups.tsx
play.pokemonshowdown.com/src/panel-topbar.tsx

Re implements the dropdown that appears when your roomlist tabs overflow into preact.

Preact: Add roomlist overflow popup

---

play.pokemonshowdown.com/src/panel-teambuilder-team.tsx
play.pokemonshowdown.com/src/panel-teamdropdown.tsx

For parity with current builder.

Preact: Add format resource loading to teambuilder

---

play.pokemonshowdown.com/src/panel-chat.tsx

TODO
tabcomplete for commands, this is a tricky since it relies on the response of /crq server command.
i have something 'experimental' in my mind for this but thats really not the priority so ill keep that for later

Preact: Support tabcomplete

---

play.pokemonshowdown.com/src/battle-log.ts

Not wedded to where this is actually _done_, but battle-log made the most sense since it actually handles colors. Open to opinions otherwise.

Preact: Support custom colors

---

pokemonshowdown.com/ladder.php
pokemonshowdown.com/users.php

Make Reg I formats into Official ladder formats and available on the ladder page

---

build-tools/build-indexes
play.pokemonshowdown.com/src/battle-dex-search.ts

Preview of new teambuilder:
https://youtube.com/shorts/64FexoPgy9I

Add teambuilder support for [Gen 3] ADV 200

---

play.pokemonshowdown.com/src/battle-tooltips.ts

https://www.smogon.com/forums/threads/visual-indicator-for-rby-recover-failure.3677391/

Tooltips: Add RBY Recover failure indicator

---

play.pokemonshowdown.com/src/battle-animations.ts
play.pokemonshowdown.com/src/battle.ts

Skip animation during fainted forme regression

---

play.pokemonshowdown.com/js/client-teambuilder.js
play.pokemonshowdown.com/src/battle-dex-data.ts
play.pokemonshowdown.com/src/battle-dex.ts
play.pokemonshowdown.com/src/battle-searchresults.tsx
play.pokemonshowdown.com/src/battle-team-editor.tsx

I don't know if there is interest in changing this to a dropdownlist with
```
Default
Home sprites
3D sprites
2D sprites
```
@Zarel I think we could still create stills from the animated models, so we have 3D sprites for the Switch games and keep all options open.

Add Home sprites

---

play.pokemonshowdown.com/src/client-main.ts
play.pokemonshowdown.com/src/panel-chat-tournament.tsx
play.pokemonshowdown.com/src/panel-popups.tsx

forum approved
https://www.smogon.com/forums/threads/if-you-join-a-tournament-with-tour-notifications-turned-off-you-should-get-the-notifications-from-that-tournament.3675730/#post-10566479

Preact: Notify users for joined tours despite global setting

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/581c3da8-fca5-4061-8aec-13f162bf59af

Add animation for Dragon Cheer

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

https://github.com/user-attachments/assets/39b0d6d0-3095-4c20-9426-220297a1c565

Move Animations: Take Heart

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

**Work in progress**: animation has a thumbs up from kalaloki and tb0lt, but still needs dhelmise's review
_https://youtu.be/bk8l9NEld1g (file size too large, this test shows doubles and singles)
**this video is old ^^^ see my newest comment for the current animation**_

Move Animations: Lunar Blessing

---

play.pokemonshowdown.com/src/battle-tooltips.ts
play.pokemonshowdown.com/src/battle.ts

Server PR: https://github.com/smogon/pokemon-showdown/pull/11213

Fix HP bar colours

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

awaiting critique by Dhelmise (see the video in my most recent comment for implementing Kalalokki's advice)
https://github.com/user-attachments/assets/66eecd42-9c5c-4549-bb10-729968505f98

Move Animations: Rage Fist

---

play.pokemonshowdown.com/src/battle-animations-moves.ts
play.pokemonshowdown.com/src/battle-dex-data.ts
play.pokemonshowdown.com/src/battle-dex.ts

Added Ramnarok forms to battle dex.
Added animation for custom move (clone torch song).

Added data for CAP36 (Ramnarok)

---

play.pokemonshowdown.com/src/panel-battle.tsx

Search parameters
- minimum elo
- username prefix
Display total number of battles

Preact: Support filters on battles panel page

---

play.pokemonshowdown.com/src/panel-rooms.tsx

(also gz to Hindi Room for winning PSPL.)

Preact: Show spotlight rooms on rooms list

---

play.pokemonshowdown.com/src/battle-animations-moves.ts

[makeitrain-singles-revised-front-(2).webm](https://github.com/user-attachments/assets/a1d86be1-3865-41ff-a8d0-c7c18581de25)

Update Make it Rain animation

---

play.pokemonshowdown.com/src/panel-teambuilder.tsx
play.pokemonshowdown.com/src/panel-teamdropdown.tsx

Currently doesn't search across forms(i.e doesn't search for mega alakazam when just alakazam is typed in).
Should be an easy fix though

Preact: Re-add team search

---

play.pokemonshowdown.com/src/battle-team-editor.tsx

Allows users to apply a box set from the abilities pane.

Preact: Support box sets in teambuilder

---

play.pokemonshowdown.com/src/battle-tooltips.ts

Bug reported [here](https://www.smogon.com/forums/threads/ignore-nicknames-doesnt-ignore-in-tooltips.3747709/).

Hide nickname in battle tooltip
