smogon/pokemon-showdown-client

- js/client-battle.js
Didn't see this when doing https://github.com/Zarel/Pokemon-Showdown-Client/commit/1055c196fd93a991655cad9ef8d341465d69b311, noticed recently playing gen 1 randbats.
> Implement Special text for gen 1 on stats tooltip

- githooks/update
- Since it's mandatory that file hashes are only updated after the file contents themselves have been updated, the index update is now wrapped in a function to be called once no files are pending update.
- The original version logged every new move acquired, but it's probably too spammy for a not-dedicated command.
- Adds `sugar` as a dependency.
> Update learnsets-g6 in `update` githook

- js/battledata.js
Currently Pokémon Showdown doesn't auto-link URLs properly in the following form.
(Check out http://play.pokemonshowdown.com/)
In this case, it's obvious that `)` not part of an URL, but the current auto-linker believes that it is. Making `)` illegal character at end of URL doesn't solve the problem, as sometimes URLs actually do contain parenthesis. The new URL regex supports one level of parenthesis (regexes don't support recursion, but if you have more than one layer of parenthesis in an URL, you are doing something wrong). This is a case with URLs on Wikipedia.
https://en.wikipedia.org/wiki/Pokémon_(disambiguation)
(it also bothers me a lot, because I like writing less important stuff in parenthesis)
> Auto-link URLs without closing parenthesis at end

- js/battle.js
- js/client-chat.js
Display the reveal button based on each user's screen instead of the current room's chat for cases such as a user being locked/banned for a PM offense without having any messages in the room.
> Update |unlink|hide| message

- js/battle.js
- js/client-chat.js
Users should be able to judge whether or not they want locked/banned users' chat messages to be hidden by default or not. Allowing staff to leave PMs and recent chat history revealed by default would help them moderate more easily as well.
> Toggle hiding unlinked users' chat messages

- crossdomain.php
When attempting to go on an unregistered server when there is already another registered server sharing the same IP/Port pair (such as in virtual hosting), you get redirected to the registered server, which
is undesirable.
This is important for me particularily because due to the recent change in server registration policy (only one server to be registered to a single user, and no registering on the behalf of others), I can't get my clients to register servers themselves due to this issue. (I host multiple servers on a single IP, but all through port 80)
(Code untested for obvious reasons)
> Only check if an address is already registered by hostname, not by IP

- js/battledata.js
Regular expression is now written using new RegExp constructor to make a more readable regular expression (even if I admit it's not that great because of `+` everywhere, but this is JavaScript, so no neat `/x` flag for regular expressions).
This heavily changes behaviour of auto-linking, in particular.
-   URLs can be in parenthesis, see 6b8b68d for more details and justification of a change.
-   More top level domains are allowed in URLs without http:// prefix. Anything that is two letter is allowed, as long followed by slash or colon.
-   Allow auto-linking URLs starting with `www.`, even with unrecognized TLD. Chances are if a domain has this particular subdomain, it's a website address.
-   Removed qmark.tk special case, this site is dead anyway.
-   Added support for `.co` TLD. This …
> Rewrite URL parsing.

- js/client-chat.js
If the user attempts to add any regular expressions that throw a syntax
error on RegExp object construction, they can see the first pattern that
throws an error along with its error message without breaking their
entire highlight list.
> SyntaxError handling when adding regex highlights

- data/graphics.js
In which the Python script I was using to search for nonimplemented moves doesn't use regex and therefore doesn't notice the missing instance of "headbutt" because it's contained in "zenheadbutt"
> Add Headbutt Animation

- js/client-teambuilder.js
PO exports a Pokemon with no item as "POKEMON @ (No Item)", which is not
a valid item in this teambuilder.
> Improve teambuilder imports

- githooks/update
The updater was originally written under the assumption that pokémon wouldn't lose access to any move in the sim -assumption which has since been proven wrong, as the changelog associated to this commit reveals:
http://hastebin.com/upovukelim.sm
> Learnsets updater now supports removing moves

- js/battledata.js
Checking for preferences if bw or xy sprites should be loaded, even if the gen you're playing want something else. Fixes #372.
(This really should've been in the original pull req.)
> Sprite gen preferences should override battle gen

- data/pokedex-mini.js
In the Teambuilder - Add Pokemon page (and possibly other places), Diancie's sprite is shown instead of Volcanion.
> Fix pokedex number for volcanion

- index.template.html
- testclient.html
Chrome Frame is not supported for two years, which means removing support for it on Pokémon Showdown should be safe.
> Disable Chrome Frame

- js/client-mainmenu.js
- `|updatesearch|{searching}` now allows an array of formats as a `searching` value.
- Old gen sprite data will be loaded based on the data sent by the server rather than the current DOM state
> Improve support for searching battles in multiple formats

- js/battle.js
Simple fix for an open issue https://github.com/Zarel/Pokemon-Showdown/issues/1872 
`updateStatbar` is now called in `dragIn` same way as it is called in `switchIn`.
> Sidebar update for dragIn

- testclient.html
While i was getting both client and server to run on Cloud9 I found out that testclient won't connect to server if port 443 is used.
The issue was that the port was parsed as a string in `testclient.html` but then compared using triple equals operator with integer in `client.js` which would return false resulting in a use of `http` protocol instead and connection issues:
client.js:695		var protocol = (Config.server.port === 443) ? 'https' : 'http';
After this small fix it is now possible to develop and test both client and server in cloud :+1:  .
> Testclient was not working when custom server was using port 443

- js/battle.js
When player clicks on `Ignore Spectators` he won't see their join and left messages anymore.
During the CAP playtest an hour ago this seemed like a good idea to have as there were almost 1000 spectators and the whole chat was unreadable because of join/left messages.
> When ignoring spectators join/left messages won't be shown

- js/client.js
- testclient.html
When testclient is run over https browser loves to complain and block mixed content which includes:
* pokemonshowdown's `//play.pokemonshowdown.com/js/config.js`
* calls to `action.php` like `upkeep`
Fix consists of using protocol-relative URL for `config.js` and not hardcoding protocol to `http://` in test mode for `getActionPHP`.
> Remove crossdomain issues on load for testclient over https

- js/battledata.js
Previously, link like `"http://example.com/"` was changed into `"http://example.com/";` because of wrong parsing of entities.
> Improve parsing of HTML entities for URLs.

- js/battle.js
With Simple Beam and Worry Seed now using -endability as well to reveal
the old ability, it is more appropriate to use a new message. Parentheses
are traditionally used by the client to indicate messages that do not
actually appear as in-game text.
> Change -endability message structure

- js/client-rooms.js
This fixes the issue that the Join room popup couldn't be used to enter battle rooms.
> Don't use toId for room names while joining a room using popup

- js/client-teambuilder.js
U-turn and Volt Switch are unusual in an aspect that they are dual purpose moves. Sometimes they are used as damaging moves (main attacking move even, like with Mega Beedrill or Genesect). In other cases, they are used to preserve momentum, and the damage from them doesn't exactly matter (see Cobalion, Xatu, Mega Pidgeot or Hydreigon).
This change allows giving a negative attacking nature to an user of U-turn or Volt Switch if it appears to be used in a momentum-sort of way, as opposed to an usage as a damaging move.
> Allow negative attack nature for U-turn and Volt Switch

- js/client-chat.js
'|' is a valid regex character and highlight phrases can occasionally pass
18 characters. If they are mapped, it can become difficult to remove
specific entries on the list.
> Don't map highlights list to toName function

- js/battle.js
- style/battle.css
The idea is that `|-ability|POKEMON|ABILITY|[activate]` will trigger when abilities activate but don't need a further message; server-side will be updated once we figure out what's the best protocol.
> Add small animation when an Ability activates

- js/client-chat-tournament.js
Add "An" instead of "A" if the format name begins with a vowel.
> Remove article in tournament creation

- js/battle.js
I also removed a random blank line because it was awkwardly placed and made Delta Stream's activation message code placement inconsistent with the other abilities.
> Add punctuation onto Symbiosis' activation message

- js/client.js
In the formats list, each entry will now support a trailing mask -sent as hexadecimal- whose binary form encodes the data regarding its availability and team requirements
> Support hidden [non-searchable non-challengeable] formats

- js/battle.js
This PR fixes the bug seen here: http://replay.pokemonshowdown.com/1v1-257350134
Previously, by the time Castform is free to change formes, `sp` contains Aegislash-Blade's sprite data and Castform changes into Aegislash-Blade instead of Castform-Sunny.
Now, both Pokemon change into their correct formes.
> Localize SpriteData variables

- js/client.js
- testclient.html
By disabling pushState we can support fragments in the test client. I moved the comment about HTML5 based history from testclient.html to js/client.js too.
> Allow non-HTML5 based fragments in the test client

- js/client.js
Normally Firefox allows you to drag and drop text and links into text fields. Because of the code supporting dropping backgrounds, this doesn't work in the client. I added some code to early-return in the case of a text field although I don't really know jQuery so this may not be the best way of checking.
> Allow default text field drag and drop behaviour.

- style/battle.css
In pull request #415 Zarel commented that he didn't like the way long trainer names wrapped because they pushed the trainer sprites down.
Positioning the trainer a fixed amount above the bottom of the bar solves this by making the trainer names wrap up instead of down.
This will then remove the objection to merging that pull request.
Before:
After:
> Make long trainer names wrap up instead of down

- js/client-battle.js
- js/client-chat.js
- js/client.js
Currently the browser's history (both from the back button but also global history) just shows "Showdown!" for any page under http://play.pokemonshowdown.com/. On the other hand, all replays get nice titles e.g. "Challenge Cup 1-vs-1 replay: conbeef vs. urkerab - Pokémon Showdown". I've gone for a slightly simpler "conbeef vs. urkerab - Showdown!" to show up during an actual battle.
The title is refreshed when the fragment changes as this is what the browser stores in its history, so this not only includes the teambuilder and ladder rooms but also chat rooms if your window is small enough, or if you joined by loading a direct link.
The case of switching to a room whose title has not been read from the server yet is also handled.
> Update the window title as the fragment changes

- js/storage.js
This commit makes life easier for some growing Reddit communities based around competitive Pokémon by making the teams easier to paste there in a format that allows them to be pasted back into the teambuilder after being parsed by a Markdown parser, while having little to no effect on everyone else.
> Quality of Life addition for users of Markdown-based forums

- js/client-mainmenu.js
- js/client-teambuilder.js
When teambuilding or searching for a battle you are currently presented with a plain list, unlike when challenging or laddering. This improves the display of those lists to include all the same sections.
> Display battle formats in groups

- js/client-chat.js
- js/client.js
This fixes an issue where highlight regular expression like `:-?\)` couldn't match a smiley, unless it happened to have a word character on both of its sides.
> Don't require boundaries for non-word characters

- js/client.js
I'm sure I saw this requested in one of the forums somewhere but I can't find it now. (I may have even Liked the post but I don't know how to search the forums for my own Likes.) Basically the idea is that until you see the reconnect popup you might not realise that you've been disconnected, which is bad if you're doing something else in another tab or window while waiting for a tournament battle to become available.
To avoid annoying the user the desktop notification is not shown if the popup is visible to the user i.e. if the app is focused and no other popup is currently showing.
Clicking on the desktop notification will helpfully reload showdown for the user.
The desktop notification permission is also requested just in case the user has never opened any PMs.
> Display desktop notification on disconnect

- style/client.css
Changing the zoom level can disrupt the teambuilder display as shown in this screenshot that I [found on the Smogon forums](http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-217#post-6296053):
Notice how the Item is slightly larger than the Nickname, Pokemon (sic) or Ability fields. Removing this item-specific style allows the teambuilder to display naturally at other zoom levels.
I didn't remove the style block because there was a similar placeholder style block a few lines above for `.setchart-nickname` but if this is an error then I can simply remove both blocks.
> Make teambuilder more resistant to zoom changes

- index.template.html
- js/client-mainmenu.js
- testclient.html
This was inspired by another forum suggestion post that I can no longer find. The original poster noticed that having closed the Latest News there was no UI to recover it. This works around the problem by allowing the news to be minimised instead. While porting the change to the unused addNews function I also fixed a bug in its height calculations by displaying the news iframe as a block. I also added the Latest News to the test client; the DOM I used there is almost identical to that created by the addNews function, the differences being the lack of the news ID, the hardcoded news URL, and the white space formatting is that from the home page.
> Make it possible to minimise the Latest News box

- js/client-teambuilder.js
Quoting original forum post: http://www.smogon.com/forums/posts/6295960
> When you open up the Backup/Restore teams page (where you import/export all your teams) can we have everything automatically highlighted? Like how exported sets work on the dex? Most of the time you're never taking only half or anything, and the only use is to copy everything then paste it back after clearing your cookies. This would make that process slightly faster.
This fixes all three cases to focus and select the text. The workflow when importing team(s) is also more staightforward; after clicking Import you can immediately paste.
> Automatically select when exporting

- js/client-battle.js
Currently, clicking Rematch when in a different tier always brings up the dialog to challenge the opponent to randombattle.
> Rematch button: default to the same tier as previous battle

- js/battle.js
When instant replaying a doubles or triples battle any Pokémon that were still on the field (other than the first, which is currently cleared out by Battle.start()) are shown as coming back or being withdrawn. The game type setting block appears to be a convenient place to clear out the active Pokémon since we know how many there should be anyway, in much the same way as BattleSide works on the server.
> Instant replays should not withdraw

- js/battle.js
Gen 4 match before this pull: http://i.imgur.com/lKK4542.png
After: http://i.imgur.com/7mJa8om.png
The past gen backgrounds were never intended to be used with gen 5/6 animated sprites due to formatting with the popup textboxes. Plus it looks weird.
I have also removed bg.jpg as the only background that would appear for gen 5 matches and restored it to the variety of backgrounds that gen 5 matches used prior to gen 6 and custom past gen backgrounds.
In addition some gen 4 doubles changes
before pull: http://i.imgur.com/XTZbIAo.png
after: http://i.imgur.com/jS1vQCw.png
> Skip past gen backgrounds with modern sprites

- js/client-teambuilder.js
- style/client.css
The validate button sends the current team and a validation request to the
server. The server will respond with a positive acknowledgement for valid teams,
or else a list of problems (the same list as when seeking a battle).
NOTE: This PR is dependent on https://github.com/Zarel/Pokemon-Showdown/pull/2150 being pulled in first.
Screenshots: http://imgur.com/a/dVj3F
> Add a validate button to the teambuilder

- js/battle.js
So that the tooltips will be accurate in instant replays.
> Instant replay needs to reset move tracking

- js/client-battle.js
Improve the style for Nature Power called move.
Crashguard in doubles for weight moves check.
This crash happens when a battle is refreshed and one mon is just fainted.
> Improve variable moves tooltip

- style/client.css
Firefox has this deliberately weird behaviour in that its buttons have 2px of magic padding - the padding is only there if it can make room for it.
This means that long names in the user list don't get the padding, thus misaligning them as seen here (line added for clarity):
Maybe there was a time when these needed to be buttons but it doesn't seem to be necessary now so I just changed them to be div elements instead as that seemed simplest.
> Firefox has magic button overflow

- js/client-battle.js
During an instant replay the controls are not updated and therefore the tooltips don't work, unless you are lucky and the battle was forfeited with all the Pokémon still playing.
By setting up the tooltips prior to the start we can ensure that they will always work. I had to change the way the Pokémon is selected as `Battle.getPokemon` works on the logical rather than the visual sides and also if you give it a fainted Pokémon it will happily substitute another Pokémon for you. The new code will automatically ignore fainted Pokémon or Pokémon that are out of range (e.g. position 2 in singles).
The `thing` for the `'pokemon'` tooltip is now a concatenation of either `'my'` or `'your'` depending on the visual side and the integer offset in the active array, thus in doubles the possible …
> Make tooltips work in instant replays

- js/battle.js
- js/client-battle.js
Apparently it's been suggested before, and it's definitely been suggested since, but the suggestion I found was http://www.smogon.com/forums/posts/5343275
Note that if you switch side while the battle is animating it will skip to the end; I couldn't work out how to skip to the current turn without restarting the background music.
> Allow spectators to switch sides

- js/client-battle.js
The base power preview calculations for Punishment and Stored Power are incorrect:
- The multiplier should not consider any evasion or accuracy boosts
- The multiplier is the sum of the boosts, rather than the count
- Punishment is limited to 200 base power
> Fix base power preview for Punishment and Stored Power

- js/battle.js
The team as displayed at the end of the battle is currently retained for the instant replay. This makes no difference when team preview is active as the act of instant replaying the team preview resets the team display.
However a correctness issue therefore arises for formats without team preview as the team should be revealed during the course of the replay as they would have been during the battle.
Another aspect of the problem arises when one of the Pokémon mega-evolves; the instant replay does not replace it with its base form so the duplicate Mega form remains throughout the instant replay.
> Clear known Pokémon when resetting battle

- js/battle.js
- js/client-battle.js
`battle.reset` already has a `dontResetSound` flag so I thought I might as well give `battle.play` the flag too.
> Keep the sound playing when switching sides

- js/client.js
This implements the following forum suggestion http://www.smogon.com/forums/posts/6447708 so that tabs open just above the side room as normal but if they would overflow then they get pushed left until they hit the main room tabs, at which point the dropdown activates in the normal way.
The 309 comes from the 165 in the line before plus the 144 from eleven lines above.
> Make side rooms overflow left on the tab bar

- js/client.js
The client doesn't update the tab bar when the server sends it the rooms, so you don't see the rooms tab unless you do something else that causes the tab bar to update.
Since the client now updates the tab bar automatically, you don't need to manually support the rooms tab, but I can remove that hunk if you prefer.
> Show the Rooms tab in the test client

- style/client.css
If you're, for instance, watching an Anything Goes battle between allaboutthatpanda and Sammichinmyhead (I kid you not), you'll find that the text doesn't fit in the tablist popup.
> Don't let room names overflow the tablist popup

- js/client-chat.js
- js/client.js
The Left/Right room navigation was changed so that it always loops through all rooms (including the Rooms room) even when the window is wide enough to tab each set of rooms separately. This updates the chatbox focus text to match.
That code uses the roomList.concat(sideRoomList) trick to create a master list of all chat rooms. While I was there I let the scope creep and applied the trick to the focusNextRoom code too. And then for good measure I implemented a request that the rooms should wrap around so that Right on the Rooms room should focus the leftmost room and vice versa, because that actually ended up further simplifying the code.
> Update chatbox focus text to reflect reality

- js/client-battle.js
- The ability from the request should be used, rather than the one from the battle
- Technician wasn't working at all
- Technician and -ates were trying to affect the power of moves without a power
- Weather Ball was checking for Cloud Nine on opponent's fainted Pokémon
> Fix base power preview for ability modifiers

- js/client.js
Tabs for battles currently show the format id and the players. I thought it would look slightly nicer if we used the format name instead. Example:
_______________________
|      ounomega      X|
|junzheng5 vs. OVOOHKO|
_______________________
|    OU (no Mega)    X|
|junzheng5 vs. OVOOHKO|
> Show the pretty format name in the battle tab

- data/graphics.js
Those missing commas make battle joining crash in a lot of browsers.
> Add missing commas in data/graphics.js

- js/client-battle.js
An earlier version of PR #476 showed the client's idea of the item even while the animation was playing. When this feature was removed an erroneous `/` got left behind in the tooltip for Generation 2.
> Fix item display in Gen2 battles

- js/battle.js
Not sure why resetting the battle during team preview turns the sound off, but it does, and switching sides doesn't want that.
> Keep sound playing when switching sides during team preview

- style/client.css
Yeah, you could still drag the resizer down, but this make it less worse.
> Fix Team Import/Export barely visible > 640px width

- js/client-battle.js
Now that move tracker increases the height of tooltips, it's possible for them to overflow the top of the window. The worst case would be something like a Greninja with an item and four moves.
> Adjust the top of the tooltip to fit in the window

- js/client-chat-tournament.js
- style/client.css
The original idea was to draw a dashed border for the team but as it turns out you get it on the battles you win too.
> Highlight the current user in elimination tournaments

- js/client-chat-tournament.js
During signups in elimination tournaments, show the number of users who
have joined in place of the empty bracket
Screenshot: http://i.imgur.com/dg2xE1s.png
> Tournaments: support showing users who have joined

- js/battle.js
- js/client-battle.js
Console rooms know about autocompletion but only chat rooms maintain a user list. This makes the battle maintain a dummy user list (thus the necessity to prepend `' '` to the user before adding it to the list).
> Allow tab completion to work in battles

- js/battle.js
I was in a random triples battle today and noticed that one of my opponent's fainted Pokémon reappeared on screen for some reason. After the battle I instant replayed and then skipped to the end and it didn't appear, but if I then replayed it though at normal speed then it did. I'm assuming that this is because the element should have been removed after the Pokémon fainted, as happens during fast forward.
I tried adding my callback first but that seems to cancel the activity callback so I moved it to happen afterwards instead.
> Always remove the element when a sprite faints

- js/client-chat-tournament.js
- js/client-mainmenu.js
- js/client-teambuilder.js
Fixes #443.
Also: dragging and dropping teams did not update `showdown_teams` in localStorage. It does so now.
> Update teams on deletions, undeletions, and drops

- js/client-chat-tournament.js
If you have an outstanding notification then the challenge notification gets triggered whenever the bracket updates. This makes it so that you don't get notified again while a notification is still outstanding.
> Prevent duplicate challenge notifications

- js/battle.js
- js/client-battle.js
As requested in PR #527 this moves the onus for enabling user tracking from the battle to the room.
> Don't track users in replays

- js/client-battle.js
- js/client.js
When you use Shift+Arrow to move a battle to the right hand side of the screen the tooltips don't work as they are limited to 335 pixels horizontally. By keeping the `leftWidth` property up-to-date we can ensure that the tooltips are limited appropriately according to the position of the battle.
> Use correct tooltip limit for right hand battles

- js/client-battle.js
Unlike PR #525 this seeks to flip the tooltip to appear below the element being hovered thus preventing it from interfering with the element itself. Doesn't attempt to solve the problem of the tooltip for Substitute being larger than the screen on a mobile phone.
> Flip tooltips that don't fit above the element

- js/client-teambuilder.js
- js/utilichart.js
The following set of changes update several parts of the teambuilder to allow it to give a better experience to past generation players.
First, Teambuilder is now able to get the generation from the format name, given they must follow the genN scheme.
Then, we are going to hide irrelevant stats from past gens, hiding ability, hiding item in gen 1, and last but not least, we are going to not to show future Pokémon in past gens.
This is just the first step of a fully functional multi-generation teambuilder.
> Past generation adaptation for the teambuilder

- js/client-teambuilder.js
When choosing EVs for LC (or even VGC) this makes the sliders snap to those positions that actually change the resulting stat.
> Automatically drag EVs appropriately for LC

- js/client-teambuilder.js
I had to move the place where `ignoreEVLimits` was set so that it would pick up changes in the format correctly. I also fixed a bug whereby if you manually delete an EV value you can then slide any of the other EVs as much as you like.
> Teambuilder should ignore EV limits prior to Generation 3

- js/client-battle.js
When choosing an ally to switch to you get a tooltip for a fainted Pokémon which shows the HP as `NaN%`. This replaces that with `(fainted)`, which resembles the tooltip for the sidebar.
> Fix HP display for fainted Pokemon

- js/client-chat.js
- js/client.js
- System chat messages (|c|~|) no longer arise subtle notifications
- Do not notify again for the same chat messages on reload: last message date is stored in preferences for each room.
> Tone down excessive notifications

- style/client.css
I've noticed that when a tooltip gets very big then the mouse can get confused if it overlaps the trigger area. By using this slightly non-standard but apparently well supported style we can cause the tooltips to be ignored allowing you to mouse over (and indeed click through if necessary) the entire trigger area even if the tooltip overlaps it.
This may also improve the behaviour on touch screens but I don't have one to try it with.
> Tooltips should be ignored by the mouse

- style/client.css
Cosmetic issue whereby if you're not at 100% zoom then moving pixels from padding to border causes layout to get recalculated. In my case it causes the wastebasket icon for the "Delete" button (but not the text!) to move when the edit button is hovered at 90% zoom.
I noticed the problem with the teamlist button but I changed the other hover too just in case. (I didn't find any other hovers which changed the border or padding.)
> Avoid changing border width or padding on hover

- js/client-chat-tournament.js
Made to better match the change to setautostart in Zarel/Pokemon-Showdown#2326
Changed `timeout` to `timer` in the autodq message too to make it a bit clearer.
> Change the tournament autostart off message

- js/battle.js
The current code displays all the damage animations at once. Unfortunately damage messages come in two parts: actions for any effectiveness messages and hidden actions for the actual damage. This means that they now display out of order; first you see any effectiveness messages for all targets, then their damage messages.
The easiest way I could see to remedy this was to make the remaining hidden actions display immediately instead of collecting up for display at the end of the minor (most of them already do this). In the case of a damage minor, any previous effectiveness messages are also shown and then cleared for the next target of the spread move.
> Properly display effectiveness of spread moves

- style/client.css
Moved the pokemon down and the clear button up so that it better fits with the new folders.
Current clipboard looks like this:
https://i.gyazo.com/bcf2ab5e17da803fff25c76a27db641a.png
https://i.gyazo.com/7767f32bd25633761a56aff95e8d0470.png
The changed one looks like this:
https://i.gyazo.com/36b612d75826ad821c8f65576c8abb7d.png
https://i.gyazo.com/a8ad0f372a3ce024f7f7c7d240972fc6.png
> Change the teambuilder clipboard design

- js/client-chat-tournament.js
Several times I've selected a team during signups only to accidentally accept the challenge using my first team of the type of the tour. This is because the team selector is currently updated when anyone joins or leaves the tournament, or when the tournament starts, but it only needs to be updated when you yourself join or leave the tournament. (There are some other cases but those are already correct.)
> Don't unnecessarily update the tournament team selector

- js/client-teambuilder.js
The Teambuilder uses 31 IVs by default however this needs to map to 15 DVs rather than 15.5 as it currently does. For example, Zapdos should have a maximum speed of 298 in Gen2, but 299 in Gen3.
> Properly calculate DVs when calculating stats in Gen1/2

- js/client-chat.js
Didn't even know it was possible until I saw this in the Help room:
[20:10:19] Madisaur: How do you un-ignore someone?
[20:10:24] Combeenation: /unignore (username)
[20:10:42] Madisaur: Thanks. Accidently ignored myself. It's rather frustrating.
> Prevent users from ignoring themselves

- js/client-battle-tooltips.js
Commit 95c7c4a removed the limited targeting information that had been displayed previously.
> Display move target in Doubles and Triples battles

- js/battle.js
Although the main problem with slots in Doubles and Triples battles was fixed, I had noticed some cases where the slot may still be incorrect. I don't know whether these cases are significant but I thought I'd provide a patch for them anyway just in case.
> Fix some potential issues with pokemon.slot

- js/battle.js
If your browser supports exception stacks then we don't actually display the exception itself, which is a little annoying.
The exception stack length limit was removed but the stack becomes boring once you reach `run` so I trim the stack at this point.
> Improve stacks for exceptions in battles

- js/client.js
You'll now unignore your own alts on updateuser if you for some reason ignored them and ignore the new name of someone you've already ignored when they change it.
> Update ignore list on rename

- .eslintrc.js
So it doesn't try to read any ancestor directories' eslint configs
Made `npm test` very broken when it was inside another directory tree containing eslint configs (cough server cough)
> Mark root directory as root for eslint

- js/client-teambuilder.js
This really messes up teams if you use it :/
I have no idea about the appropriate message for this, but I tried making it similar to the slashes one.
> Disallow | in team names

- js/battledata.js
- toName is updated to deal with zalgo and LTR text.
- toId is now infinite-recursion-safe, and equivalent to toUserid.
- Tools.escapeHTML and Tools.sanitizeHTML no longer crash for some input.
- Tools.getString is made available as getString
(We actually need more inter-branch PRs)
> Bring string utility functions to parity with server counterparts

- githooks/build-indexes
At least, according to `ou-1500.json`. In fact, Power Herb is 46th, partly due to the number of Mega stones that are more popular. Top 15 items:
1. Leftovers
2. Life Orb (56% as popular)
3. Choice Scarf (33%)
4. Assault Vest (21%)
5. Rocky Helmet (20%)
6. Focus Sash (19%)
7. Choice Band (15%)
8. Choice Specs (13%)
9. Sitrus Berry (8.3%)
10. Toxic Orb (6.7%)
11. Lum Berry (6.7%)
12. Black Sludge (6.1%)
13. Eviolite (6.0%)
14. Charizardite X (5.5%)
15. Air Balloon (5.4%)
> Rocky Helmet is 20 times more popular than Power Herb

- js/battledata.js
e9ba086 fixed fxPrefix to be https://play.pokemonshowdown.com/fx/ in downloaded replays but resourcePrefix is still http://play.pokemonshowdown.com/
> Make resourcePrefix default to https: in replays to match fxPrefix

- data/graphics.js
- Rock Slide doesn't animate properly in Doubles / Triples, made a workaround animation;
- Cut wasn't animated. It uses Slash's animation now;
- Remove extra Jump Kick;
- High Jump Kick doesn't look like it's going to miss every time now (hopefully).
Rock Slide:
High Jump Kick currently:
High Jump Kick after:
> Fix animations

- js/battle.js
Currently spread moves in doubles / triples only animate one target and without doing something here, that won't change. Though, I don't know if this is the best way to accomplish this, or even if it's the best place to put it.
> Support animating several Pokemon in spread moves

- js/battle.js
- js/client-battle-tooltips.js
Created a new line in a pokemonToolTip which mirrors the line showing the pokemon's stats. However, this line contains stats multiplied by their respective boosts, following Pokemon's in-game formula.
Examples:
http://imgur.com/a/wsHam
Pictured: +5 Atk Hawlucha with Unburden boost
Slow Start Regigigas on the first turn after entering the battle
> Add stat boosts in tooltip

- data/graphics.js
The aftershadow would stay in place on the defender and attacker's side
> Fix Meteor Mash animation

- js/battle.js
When an item is stolen then the victim's tooltip doesn't update to reflect that, nor does it adjust for unburden.
> Update the victim when an item is stolen from it

- js/client-rooms.js
Prior to #647 the battle room had to repopulate its format selector when formats changed. Unfortunately it did this by reinitialising itself which not also sent a `/cmd roomlist` but also added another format change listener, thus doubling the number of `/cmd roomlist`s sent each time formats change. Worse, you didn't even need to leave the battle room open for this to happen, so after three format changes you would get three flood warnings, then eleven, then 27, and so on. (Eventually the server will flood you!)
Of course with the fix to #647 no repopulation is necessary so that line of code can simply be removed.
> Stop reinitialising the battles room when formats change

- js/client-battle-tooltips.js
- style/client.css
First of all, love the game, thanks for bringing Pokemon to the web!
Playing it at school, at work, even some before sleep for a long time!
One thing that bothered me for long is how it runs on mobile.
Works fast and all but buttons are a nightmare, tooltip stays until you click somewhere else, on iOS I find myself to click the button 20 times until it registers.
Not long ago I saw this on Github finally and decided to fix this today.
Anyway I changed the tooltip attributes from mouse events to touch events.
When you long press (more than 300ms) the tooltip shows, and when you short press (shorter than 300ms) the normal click event is called (which is kind of a hack, you are welcome to change).
Wished you made this more of a standalone project, pain to debug on release site.
Have a nice …
> Better touch handling on mobile devices

- js/client-chat.js
Hidejoins hides all joins. Showjoins shows all joins.
Using showjoins room adds that room as an exception to hidejoins.
Using hidejoins room removes the exception.
> Make show and hide joins configuration per-room

- js/battle.js
When watching a doubles battle on a small screen, you don't get to see the chat, but you do get to see the "It's super effective!" or "It's not very effective..." messages. However for a spread move it's unclear whom each effectiveness refers to. My understanding is that in the case of a spread move the cart identifies each effectiveness.
Before:
After:
> Show target of effectiveness of spread moves

- style/battle.css
Now it looks too bright, making the Pokémon look like they are out of place
> Increase opacity in battle background

- js/client-battle.js
If (for example) you forfeit, the notification lingers until you close the battle
> Close the choice notification when the battle ends

- style/battle.css
Make sure `.dark a:visited` doesn't apply to links in declares or colored
broadcast divs
> Make declared visited links readable in dark mode

- style/battle.css
- style/client.css
While this isn't a huge issue, the "(x lines from y hidden)" message can be pretty hard to read in front of a blueish background (e.g. http://i.imgur.com/yUxRvRY.png). I changed it to look like this: http://i.imgur.com/MlXvtq2.png
Something I'm not really sure about is where to place the new rule in the css file - I put it in the dark mode/chat section since that seemed the most fitting.
> Make subtle buttons more visible in dark mode

- js/battledata.js
- js/storage.js
Requires https://github.com/Zarel/Pokemon-Showdown/pull/2539 to work.
Looks like: http://imgur.com/a/yFd0C
Works for anything that currently has more than a single set of sprites uploaded (notably not Gastrodon-East's back) and an `otherForms` entry.
I'd love to hear another way to not break the import/pack, the current solution works, but hacky, assumes a bunch of things about what it got, and is slower...
> Support alternate cosmetic models

- js/battle.js
When the _Own Tempo_ Ability blocks confusion, the ability does not activate. This happens even if the server sends it (which it doesn't as yet, see Zarel/Pokemon-Showdown#2555). I moved the Ability activation block above the `switch`, and inlined that into the `else if` blocks.
> Show ability activation for confusion immunity

- js/client-battle-tooltips.js
The latest updates to the move tooltips regarding accuracy are using baseAbility, which can change with Skill Swap or similar skills, this change uses pokemon.ability instead, which tracks the current ability after such changes.
> Fix move accuracy text when modified by an ability

- js/client-battle-tooltips.js
Updated as recommended in #713  to show the current and base ability of the active pokemon, as a bonus it also works on the foe's active pokemon.
> Fix active pokemon ability text in tooltip

- js/client-battle-tooltips.js
Because it doesn't depend on the target, unlike all the other accuracy-changing effects that I could find.
> Include the effect of Gravity in accuracy calculation

- js/client-battle-tooltips.js
Currently OHKO moves show their accuracy as if they were affected by acc boosts/items/abilities (so for example, Hone Claws will increase the shown %).
This change also adds some text regarding how the true accuracy of the moves is calculated, the exact percentage can't be shown since there's no target data consistently available (target in double battles etc.).
> Tooltips: fix OHKO moves accuracy text

- js/client-teambuilder.js
- js/search.js
- style/client.css
- Visible changeform button in dark mode
Oversight on my part, I forgot to make an alternative for dark mode, and the current colour is practiacally invisible.
- Show all learned moves on alternate forms
The teambuilder right now only shows the pre-evolutions moveset if you pick an alternate form first.
- Stop the changeform click event from triggering when you click the Pokemon input box
Right now, if you click the input box to change pokemon and there's a Pokemon with an alternate sprite selected, the event triggers anyway.
> Fix teambuilder problems with alternate forms

- js/client-battle-tooltips.js
Looping through Victory Star and reassigning `myPokemon` removed the original reference to what it pointed to first.
> Tooltips: Fix Wide Lens

- js/client-chat.js
I.e. `/hl add,abc{1,2}def{2,3}` will no longer lead to the highlights `abc{1,2}def{2` and `3}` being set, instead counting as one.
> Allow use of multiple interval operators in hl regex

- js/client-chat.js
A command like `/highlight add, , , , , , , , , , , , , , , ` currently adds all of them as empty highlights, which means every message that is sent gets highlighted.
You could probably accomplish this by changing the regex too, but I don't know how to do that.
> Prevent empty highlights

- js/battledata.js
This makes it so the client can send /html [message] and it can parse it like a chat message with HTML.
This commit is especially helpful to side-servers that sometimes add custom formatting, such as emoticons.
> Rework /html as inline, old behavior kept as /raw

- js/battledata.js
Putting bold and italics parsing before the [[ ]] parsing prevents the issue that caused the seemingly empty post. At first I went with the lookaround for "&lt;/a&gt;" like it was done for italics, but reordering seems cleaner. As a bonus, all these similar formatting options are now in one place.
Also remove unneeded regex flag.
> Prevent blankposting with "[[**]]"

- js/battle.js
The lastmove check is there in case a levitating mon gets hit by No Guard Smack Down while using Dig or Dive. Considering how contrived that scenario is, I'm not sure if it's worth it. Seems cleaner this way though.
> Reset sprite when affected by Smack Down

- js/client.js
Only a situation where a battle is open in both the left and right room shouldn't use the hardcoding, since the right battle wouldn't get enough space otherwise.
See https://github.com/Zarel/Pokemon-Showdown-Client/commit/07a339f62c6d897f01ddeb539d28f05d49189d85#commitcomment-18000443
> Prevent roomtabs unnecessarily jumping to the side

- js/client.js
This is mostly to prevent expired groupchats from staying on your autojoins indefinetely unless you join/leave another room manually.
> Refresh autojoins after failed room join

- style/client.css
This helps to make this property more visible in darkmode
BEFORE:
AFTER:
> Add .dark .teambuilder-clipboard-data

- js/client-chat-tournament.js
Only show battle start, battle end, and disqualify messages to players
by default with an added option to always show these messages.
This was suggested in staff to allow users who don't join a tournament to continue their conversations and not be flooded with messages that don't directly affect them.
> Tournaments: reduce the number of battle messages

- js/client-teambuilder.js
- js/storage.js
I was sleep drunk when I slapped this together so it probably needs some cleaning up but it works...
not that I didn't add import to folder because you can just append it to restore all...
> Export folders

- js/battle.js
Once this is live, Aromatherapy and Heal Bell can be changed to `this.add('-cureteam', '[from] ' + move, '[of] ' + pokemon);` which I'll submit in a separate PR. This allows old replays to continue to display the whole team being cured which is slightly less incorrect than there not being anything cured.
> Allow the battle engine to manually cure status after -cureteam

- js/battle.js
Heal Bell can't cure soundproof allies in Generation 3 or 4, so we can't use `-cureteam`, but it doesn't list cured Pokémon, so we need to be able to make it `[silent]`.
> Allow status to be cured silently

- js/battle.js
- Trace doesn't mark the base ability
- Role Play doesn't mark the ability on the Pokémon it was copied from
> Mark abilities correctly for Trace and Role Play

- js/storage.js
Hello. :)
Currently, when a Pokémon's move is not set or set to be empty and the user exports the Pokémon/team, a line with a dash but no name appears in the obtained text. [Screenshot of an example](http://image.prntscr.com/image/3ea16e2a4f744e639ef42081ac0bead1.png).
This pull requests fixes this problem by not writing the line if the move is empty.
> Fix the exporting of empty moves

- js/battle.js
Damage-weakening berries send two berry events, but the second one clears the reason from the first, so we have to set it again.
> Mark damage-weakening berries as having been eaten

- js/client-battle.js
As mentioned in http://www.smogon.com/forums/posts/7050644 the pref to disable animations isn't honoured when you switch between battles. (Maybe there's an easy way to just let the battle play out in the background rather than waiting for the user to switch tabs, but I couldn't see it.)
> Switching battle tabs should honour the 'noanim' pref

- style/client.css
This affects:
- Overflow button
- Sound / Settings buttons
- Battle options button
- `+` button in overflow list
The first hunk serves to prevent it from affecting other buttons.
> Change dark topbar button colour scheme from default

- style/client.css
This makes it so that if you were to get highlighted in two rooms next to each other, so that they will be separated better - more light lightmode.
BEFORE:
AFTER:
> Darkmode: Change HL roomtab border color

- js/battle.js
- js/client-battle.js
- style/battle.css
Continuation from the suggestion in https://github.com/Zarel/Pokemon-Showdown-Client/pull/783. Battle chat now updates when someone clicks Ignore Opponent / Spectators / Nicknames and hides what the user doesn't want to see.
Hiding nicknames is about as efficient as I can get it, I think. I've done my best to keep the html structure (and hover-over things) intact but I may have missed something. It's not the most elegant method but it seems to work fine...
> Update battle log when ignoring something

- js/client-battle.js
I am apparently very good at overlooking things when adding something :| Fixes http://www.smogon.com/forums/threads/ps-serious-bug-reports.3521891/page-10#post-7061792
Have to reimplment the old `Pokemon#getName` here since this is escaped at some point, and I don't think there's any other way to do it.
> Fix Pokemon name when trapped

- js/client.js
This fixes autojoin not working because of the window width being too narrow.
This was from before chatrooms besides Lobby were implemente, but nowadays it
depends on the window layout of a desktop giving the browser enough width,
isn't consistent with autojoining via routing or server-side autojoin, and for
mobile users makes the function dependent on the screen resolution and whether
or not the phone's in profile or landscape mode.
Fixes #742
> Autojoin regardless of window width

- js/client-battle.js
When making https://github.com/Zarel/Pokemon-Showdown-Client/pull/796 I forgot `move 2 mega` was a valid choice that could happen, so at its current it doesn't work since it'll try to index to `'mega' - 1` in those cases. Opps.
This fixes that, but for once merging was too fast for me to have time to fix it before :(
> Fix choice display with mega evolution

- js/battle.js
I think that Focus Energy is supposed to indicate if it was caused by an item. There was also a grammar error in the case of Confusion being cured by an item.
> Tweak a couple of messages

- js/client-battle.js
@Ridaz tells me that the timer doesn't appear during preview, and code inspection suggests that it doesn't appear for switches either.
I moved the call to `getTimerHTML` because I found it confusing to have to get `requestTitle` exactly right, instead I think the code is clearer this way.
> Show the timer when switching and during team preview

- js/battle.js
I assume the volatile start/end messages are best suppressed server-side using '[silent]'.
> Add message and volatile for Throat Chop

- js/client-teambuilder.js
Minior has 7 forms, which, once they're supported, will confuse the teambuilder. This changes the calculation for the height and width:
- The height is the smallest height needed to fit given a width of no more than 7
- The width is then reduced if this is possible without increasing the height
For example, in the case of Vivillon, which has 18 forms, 3 rows are needed, but then we find we only need 6 columns.
> Increase flexibility of alternate form popup size

- js/battle.js
If there are other minors, they are silenced and a specific message is substituted.
> Add specific message for when Z-Power boosts more than one stat

- style/client.css
It was partly being overwritten by the non-notifying hover style. Top left is the current situation for a notifying dark roomtab on mouseover, bottom left is the new one, right is how it looks without hover for comparison.
> Dark mode: Prettify notifying roomtab on hover

- js/battledata.js
Currently, animations for gen 7 mons fail to load with the default options, because it tries to get them from sprites/bwani. I assume this was meant to be some kinda workaround from when we didn't have the models, but the commit in question https://github.com/Zarel/Pokemon-Showdown-Client/commit/df7a96c4a7af915111eab1eb547ad14b97fccfce doesn't really explain.
Anyway, I tested this with all combinations of animation options, and none of them showed a broken image.
> Fix gen 7 mons' battle anims not showing

- js/battle.js
Rather conveniently from the client's point of view, weather upkeep data is explicitly sent to the client. This means that if a Pokémon faints and one with a weather Ability is switched in, the duration is set to 5 or 8 turns, and does not change at the end of the turn.
Unfortunately terrain Abilities do not have that luxury. PR #808 worked around this but for the first turn only; this means that terrain Abilities that activate on switching in for a fainted Pokémon will display the wrong turn count, as they are immediately changed at the end of the turn.
Of course you have to be careful to distinguish this case from that of a slow VoltTurn. As far as I can tell, there needs to be a message to inform the client that residual upkeep has taken place and it should update pseudo weather. This …
> Allow the server to update psuedo weather backwards compatibly

- js/client-chat.js
Currently, if I accidently hit tab one time too many, I have to either press tab again 10 times to cycle through all the names or backspace and re-write the name. I'd much prefer just using Shift+Tab once instead.
I wasn't entirely sure what to do if Shift+Tab is pressed when no tabcompletion has happened yet. It could 1) not do anything,
2) start a new completion, beginning with the most recent name (as if just Tab was pressed), or
3) start a new completion, beginning at the _end_ of the candidates array.
Currently it does 2), because the person to have talked the most recently is always the most useful first suggestion. On the other hand, this behavior might be unexpected to anyone experienced enough to use Shift+Tab in the first place, since it's usually option 3 elsewhere as far as I …
> Allow cycling through tabcomplete candidates in reverse

- js/client.js
I hope this would be the correct way to do this.
The main reason for this is that I want to be able to use popup-producing commands like /modlog or /roomauth without having to click the chat to refocus every time.
> Refocus on originally focused element on popup close

- js/battle.js
Currently things like screens or tailwind are showing in lower case in replays. The server is sending the correct name, but we're turning it into an id. This happens to work in battles because Tools.getMove turns it back into a name, but fails in replays. If we use the original name, we get the right behaviour in replays, and Tools.getMove becomes unnecessary. Example replay: http://replay.pokemonshowdown.com/gen7pokebankdoublesou-488415145
> Don't display side condition ids in replays

- js/client-teambuilder.js
- style/client.css
Since there will most likely always be a part of the users that doesn't know every mon's typing by heart, I think it is a good idea to display the typing right there in the set details, so that people won't have to return to the Pokemon selection menu every time they want to check which types they get STAB on or something. There's some free space there anyway.
I hope I'm not destroying the aesthetics with this, should the typing be centered above the ability box, or somewhere else entirely? Should there be a label, or is it self-explanatory enough?
> Teambuilder: Show typing in set details

- js/search.js
Smeragle should only be able to learn Non-Z moves from the gen selected and back.
Because `BattleMovedex[i]` does not contain a `.gen` property, I used `Tools.getMove(i);`
The `.isZ` check is for gen 7, because Smeargle cannot sketch a Z-move to learn it.
> Fix Smeargles learnsets

- style/client.css
Dark mode needs to override the background, but the grey colour works OK.
> Improve the appearance of disabled buttons in dark mode

- githooks/build-indexes
- js/search.js
Currently, whenever no format or a gen 7 format is selected in teambuilder, pokemon that are OU in gen 7 are incorrectly marked as banned. This is my attempt to fix this. I might be doing this wrong, If I am please do point it out. I was unable to test this as I cannot run the files in `./githooks`, but from what I've seen this should work.
> Dont mark Gen 7 OU pokemon as banned

- style/client.css
Its hard to read the info for a move / ability / item / pokemon when its selected in teambuilder, i changed the font color from `#999` to `#FFF` to resolve this.
> Dark Mode: Make it easier to read selected teambuilder options 

- style/client.css
To be specific, changed the "EV" here to match the color of the stat name labels:
> Fix small dark mode label color inconsistency

- js/client.js
Overlooked in #851 without this if you attempt to connect to a unregistered server (like a local test server) lobby wont load until you leave and rejoin it.
> Autojoin lobby on unregistered servers

- githooks/build-indexes
- js/search.js
Handles `UU`. If `RU` is going to get pokemon marked as `RU` shortly, this can wait and I can add them in.
> Update format slices

- js/client-chat-tournament.js
Regression from PR #726 - the battle result is already escaped so that it can be appended when the start message is not available to be updated.
Was observed when user `Complexities <.>` took part in a tour.
> Fix double-escaping of battle results

- js/client-battle-tooltips.js
In Gen 7, all formats with "Random" in its name will start using the same
EV calculation formula as Random Battle (singles).
Reliant on Zarel/Pokemon-Showdown#3199
> Update min/max speed calculations for Random Doubles/Triples Battles

- js/battle.js
From [this report](https://www.smogon.com/forums/posts7235125) it seems that commit b11409b changed the cry after any forme change, not just mega or primal. Unfortunately this included Transform/Imposter, so it needs to be reset in those cases. (Mega and primal transforms aren't removed when you switch out, so this doesn't affect them.)
> When clearing a transform, reset the cry too

- js/client-mainmenu.js
In response to [this suggestion that I find useful and interesting][1], I added /clear to the PM box.  This does:
- closes the pm box
- flushes out chat history and the inner HTML.
(PS: Please let me know if you want this as a regular chatroom based command as well, I can __totally__ try to add that too!)
[1]: http://www.smogon.com/forums/threads/suggestions.3534365/page-49#post-7230510
> Add /clear to PMs

- js/battle.js
- js/client-battle.js
This fixes two things:
1. the auth symbol change for players which caused player messages to always go through in battles, regardless of "ignore opponent" and /ignore
2. the automatic message hiding/unhiding when clicking "Ignore spectators", which used to hide _all_ chat messages. Now it only hides actual chat messages and joins/leaves, but not the details row of /dt or notes like "Spectatoers ignored.".
> Fix ignoring in battles

- style/battle.css
- style/client.css
This changes this: 
to this:
The color attribute is repeated in the :hover rule because otherwise `.dark .popupmenu button:hover` would overwrite it (with black). Not sure if there's a more elegant way to solve this.
It also changes this:
to this:
Lastly, this also changes subtle links to not be black in dark mode by inheriting the regular text color. Zarel mentioned fixing that in the dev room a while ago (and it is indeed fixed on the site), but apparently that change was never actually committed.
> Fix some dark mode visibility issues

- js/battledata.js
- stop redirecting to stuff such as ``https://docs.google.com/document/d/1HN-sTiW6Psm-Xa87ew4eS3WrLnH4k8rGcwqmbm-Glg0/edit</b>`` (sample mafia link that glitched up) when the entire link is done with formatting
I believe adding those ``<>`` in those places will fix it (tested using testclient.html locally)
> Fix linking with formatting

- js/client-teambuilder.js
Because there's no happiness input in gen 1 mode, it gets undefined, which it parses as NaN.
> Fix level changing in gen 1 teambuilder causing invalid happiness

- js/client-chat.js
By ghost "new message" notifications, I mean that sometimes, after refreshing, rooms will notify you of new messages, but there aren't any that you hadn't already read. This was caused by the time offset between server and client, which can change by a second every now and then. When it increased by a second on refresh, the latest message in the room will seem to have been sent a second after the latest recorded date, causing the notifcation.
This fixes that by using server timestamps for logtimes.
> Prevent ghost new message notifications after refreshing

- style/battle.css
PR Zarel/Pokemon-Showdown#3427 changed the HTML for modchat messages to use `<strong>` instead of `<b>`. This means that a rule for the battle messagebar now trips over modchat messages. I'm assuming that these rules were probably only meant to apply to the messagebar, which is why they're after the rule for the messagebar itself in the first place. (In fact, I'm not sure why the messagebar also has the message class; that could probably be removed if you want.)
> Modchat messages are not battle messages

- js/battledata.js
Currently, if you do [[]] on PS, it will link as if you had done [[undefined]].
> Fix linking undefined when not linking anything

- githooks/build-indexes
Also prepare for the lower tiers to come so they won't initially get displayed as banned when they come out.
Unless there's a specific reason to only add new formats when they come out?
> Teambuilder: don't display M-Garchomp as banned

- style/battle.css
- style/client.css
1. subtly notifying roomtab title turned white on mouseover (I accidently broke this in #879)
2. bold text in modchat/modjoin boxes [turned blue](https://cloud.githubusercontent.com/assets/5814184/25301690/fa23b102-272d-11e7-8414-37a9a3ea36c9.png) in the battle chat since they now use ``<strong>`` as well
> Fix dark mode style regressions

- js/client-chat.js
- js/client-mainmenu.js
- fix spelling mistake in client-chat man -> main
- use ``message`` instead of ``textContent`` for showing PMs in chat.  It goes through ``Tools.parseMessage()`` in addChat in client-chat anyways when generating the green message in chatroom, so no need to use the just text version of the PM.
> Allow formatting in PMs and fix spelling mistake

- js/client-teambuilder.js
Fix for #911. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist), StorageManager#persist() was introduced in Opera 42. It's crashing in 44, so I'm just gonna prevent all versions starting with 4 to executing that code, I don't want to rely on them fixing it in 45.
> Prevent teambuilder from crashing current versions of Opera

- js/client-chat.js
Discussed in staff, not decided on yet so shouldn't be merged.
Adds the ability to highlight a user through protocol. This is used for declares.
- `|notify|message to display when hovering room tab` Highlights the user normally in the room. http://imgur.com/a/wcj1k (note this image is from a global declare test, but global declares do not highlight in all rooms)
- `|globalnotify|message` Sends a PM box from `~` with the message, accepts HTML, also sends a notification sound.
EDIT: update information to match changes
Paired with server pull request: https://github.com/Zarel/Pokemon-Showdown/pull/3294
> Add |notify|

- js/battle.js
Completes https://github.com/Zarel/Pokemon-Showdown/pull/3512
Also backwards compatible for servers where this isn't sent.
> Show team size in generations without team preview

- js/client-mainmenu.js
Fixes this crash:
```
Uncaught TypeError: Cannot read property 'room' of undefined
at child.selectTeam (client-mainmenu.js?097feaf9:1069)
at child.dispatchClickButton (client.js?a487c6d5:2147)
at HTMLButtonElement.wrapper (lodash.core.js?66b6d754:1157)
at HTMLDivElement.dispatch (jquery-2.1.4.min.js:3)
at HTMLDivElement.r.handle (jquery-2.1.4.min.js:3)
```
Side note: did someone refactor out the `options` from `dispatchingPopup` at some point? This clearly worked before but doesn't anymore.
> Fix crash in team selection for tournaments

- js/client-battle-tooltips.js
Because the ability was not actually part of the main condition, non-status normal-type moves never got to the Iron Fist/Reckless/Normalize check.
> Tooltips: Don't skip 1.2x ability boosts for normal type moves

- js/battle.js
- js/client-battle-tooltips.js
- After Transform/Imposter, automatically add any known moves from the target with 5/5 PP
- When a Transformed Pokémon uses a move, note that the target also knows it
This is mostly useful for spectators of Balanced Hackmons battle I guess...
> Track moves from Transform more accurately

- githooks/build-indexes
- js/search.js
- actually builds a table for SM Doubles instead of just displaying everything
- does not display unreleased mons as legal in doubles formats
> Display only legal mons in SM Doubles teambuilder

- js/client-battle-tooltips.js
It boosts move base power, not atk, plus the bp boost is already being displayed separately as well so this was redundant anyway.
> Tooltips: don't report Toxic Boost as Atk boost

- js/client-chat.js
- js/client.js
- add a new ``|authconfig|`` message which will merge the new data with the default groups provided in ``groupDetails``
In tandem with https://github.com/Zarel/Pokemon-Showdown/pull/3529
> Client: support custom ranks

- js/client-battle.js
Even though the buttons were styled like they were disabled, the onclick events still fired. This caused invalid target locations to be added to the choice string, which basically broke the battle.
> Don't crash when clicking empty targetting buttons

- js/battle.js
- prevent infinite recursion
- prevent copies of tracked moves from stacking up
This isn't really relevant for current gens but transforming into each other is possible in older gens.
> Properly handle pokemon that transformed into each other

- js/battledata.js
"Oh, btw, this isn't standard PS notation." 
(this is the (late) update from that comment)
> Change tenary operators to or statements

- js/battledata.js
- style/battle.css
- style/client.css
Since real custom elements still have very limited availability, this is the most proper way to do it,
and results in a more predictable HTML parsing.
Adds support for custom styles and classes.
Example:
``<psicon pokemon="meloetta" class="pixelated" style="opacity:0.4" />``
Alternative to #944
> Refactor custom icons to a single element <psicon> and use Caja

- customcss.php
The sanitizer isn't able to execute within php's default max execution time for a css file that is a little bigger.
http://php.net/manual/en/function.ini-set.php
> Custom CSS: Increase max execution time

- js/client-teambuilder.js
Would it be a good idea to have some global "current gen" constant so we don't have to hunt down all the outdated gen numbers every time a new one comes out? Where would it go? battledata.js?
> Fix teambuilder showing current gen base stats for gen 6 teams

- js/battle.js
This makes for instance Ditto transformed into Clefairy appear as Normal type instead of Fairy type. The battle with a bug can be seen on http://replay.pokemonshowdown.com/gen1ou-593692946
Pretty sure there is a cleaner way of doing this, I'm not really used to contributing to client, feel free to point out improvements.
BattleTeambuilderTable is checked before use because there is no requirement it's loaded (it's not loaded in replays for instance). The old version didn't work in replays either, so it's probably not a big deal?
> Display correct type of transformed Pokemon in old gens

- js/battle.js
- js/client-battle-tooltips.js
- js/client-battle.js
- testclient.html
Fixes battle UI-related issues in #954
> Accessibility improvements to the battle UI

- js/battledata.js
It seems like forgetting spaces before links like `examplehttp://example.com` is common enough, and considering it's rather clear what this is supposed to do, no reason to force typing the link again for it to work. This only affects links having http, https or www at the start, no other links.
> Don't require boundary before http in links

- js/battle.js
https://github.com/Zarel/Pokemon-Showdown-Client/commit/76690a5001f8b2a7092938af7899c672f5a3c6d1 changed argument parsing behavior so that `args` will no longer get shifted. Due to this, `args[0]` in timer messages is no longer "You have x seconds left", but "inactive".
> Fix remaining timer not being displayed properly

- js/battledata.js
- js/client-chat.js
This is supposed to allow for locale aware implementation of /roomevents. Timezones are confusing, and can be misread causing some people coming for an event in wrong time. This is client-side part of locale aware /roomevents.
`<time>` element is part of HTML5 and is already parsed by Caja. Reusing already existing element doesn't appear to be a practical issue, as it's pretty much meant to do stuff like that.
> Parse HTML time

- js/client-teambuilder.js
- js/storage.js
- test/test.ts
The "uncategorized" folder is currently named "gen7", but uncategorized teams don't have any format, so the current approach wasn't finding the teams correctly.
> Allow export of the 'uncategorized' format folder

- js/client-battle-tooltips.js
This way, it's made sure that `basePower` actually reflects the power of the Z move (if applicable), not just always the base move.
Calling `this.getMoveBasePower(move, pokemon, activeTarget) || basePower` is usually enough for all moves, except for Extreme Evoboost, because its BP is both 0 and different from its base move's BP, so Last Resort's 140 were incorrectly shown.
> Tooltips: fix wrong base power being displayed for Extreme Evoboost

- js/battle.js
So for instance if a Tapu uses Guardian of Alola then the move track shows that they've lost 1PP from Nature's Madness. (Can't do anything about generic Z moves of course.)
> Track base move for Z moves that have one

- js/battle.js
- js/client-battle-tooltips.js
- js/client-battle.js
If Zoroark is KO'd while its Illusion is up, the following happens:
- The server updates the Illusion's condition to be `0 fnt`
- The server breaks the Illusion
- The server faints Zoroark
Unfortunately once the client has seen the Illusory Pokémon's condition as `0 fnt` it treats it as fainted and zero HP for the rest of the battle, so even when it switches in for real the client either says that it's fainted or a duplicate.
The `zerohp` flag seems to be a complete waste of time here as everything it does is already covered by the `fainted` flag except in the case of KO'ing Zoroark under Illusion, so removing that is the first step to a solution.
Note that it then remains to decide what to do with the `fainted` flag. There are two approaches here:
- Don't set the `fainted` flag when the …
> Don't be so confused when an Illusion faints

- js/battle.js
This relies on a pretty trivial fix server-side that I'll (or anyone else) will do if/when this gets approved (https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-170441910). 
I believe this would cover most of the bases for correctly matching the Pokemon as they were from Team Preview with an updated shiny version if the first switch-in reveal it to be shiny. Nothing else I've tried so far would cover Species Clause-less metagames like AG, so this was the best I've been able to do.
[Example](https://puu.sh/xrnOl.gif)
> Match a shiny Pokemon as their non-shiny Team Preview counterpart

- js/client-battle-tooltips.js
Server-side is Zarel/Pokemon-Showdown#3969.
In Gen7 battles, `pokemonData.ability` will (during a choice) now contain the true own Ability, even after Imposter/Transform. If that's not set, then we fall back to `pokemon.ability` and `pokemonData.baseAbility` as usual for previous Gens.
(Previous code is somewhat inconsistent as to whether it's using ids or names, so feel free to insist on one.)
> Reveal own Ability in Gen 7

- js/battle.js
PR #984 overwrote the `move` object with that of the base move, which meant that it stopped getting its animation, so I'm saving the name for move tracking separately.
Note that PR #978 isn't directly relevant since status Z-moves don't exist and the server overrides their animation anyway (although that might no longer be necessary?)
> Prevent base move tracking from disabling Z move animation

- .gitignore
- composer.json
- composer.lock
- index.template.html
- js/client-topbar.js
- js/client.js
- lib/ntbb-session.lib.php
This doesn't support setting accounts up for Google login: that still has to be manually done via the database by setting the email field to `username@gmail.com@`, where the second `@` denotes that it's using Gmail login.
If the email field does end in `@`, `getassertion` will note this by sending `;;@gmail`, to convey that the server is expecting a Google login token rather than a password.
Upon receiving `;;@gmail`, the client will replace the password box will with a Google login button, and then send the resulting Google login token to the server in the `password` field. The server will validate the "password" using the Google server libraries, and otherwise handle the login as normal.  Note that Google login requires various features that a paranoid person might disable; most notably …
> Support Google login (two-factor auth)

- js/client-chat.js
`e.setSelectionRange` is a typo, `setSelectionRange` is a method of the textbox element.
Results in `Uncaught TypeError: e.setSelectionRange is not a function` when the user types in ``"/r "``.
> Fix crash on browser console when typing "/r "

- js/battle.js
If you use e.g. Z-Cosmic Power, then you should get 'Clefable boosted its Special Defense using its Z-Power! Clefable's Defense rose! Clefable's Special Defense rose!'.
> Don't merge normal move boosts in with the Z boost

- js/client-battle.js
The assumption that a team has 6 Pokemon in it isn't really true in every situation, especially now that 24 Pokemon teams are supported.
> Team Preview: Don't hardcode team size for Illusion

- js/client.js
Currently fragment dispatching happens before autojoins. This means that if you're in a battle but need to reload (e.g. due to an interrupted connection) you rejoin the battle before attempting autojoins and they fail because they're now too late.
> Dispatch fragment after processing autojoins

- style/client.css
really hard to read and shouldn't be that white in darkmode, as a consequence it should be updated like this;
screenshot : before/after
> Dark mode CSS – Fix Teambuilder Results (hover)

- style/client.css
this color should be blue in darkmode 
screenshot : before/after
> Dark mode CSS – Fix Notifications' color

- js/battle.js
As seen in https://www.youtube.com/watch?v=YmLzeSB0xK0 the Protective Pads have an activation message when blocking the effects of the target's Ability, be it Iron Barbs, Aftermath, or Tangling Hair, but not for other effects such as Spiky Shield. At the very least we'll need a client-side message for this, and then we can think about implementing the server-side behaviour.
> Add activation message for the Protective Pads

- js/client-teambuilder.js
When trying to drag and drop teams in a user-created folder, the team would have "gen6" prepended to its folder name, which made it disappear (since it's in a different folder now). I assume this was originally meant for *format* folders, but even there the same problem remains - it would unexpectedly move to a different format folder.
I think that the proper way to deal with the issue is to do any renaming when loading the teams from storage (and importing). That already happens (``storage.js:574``), so I this should be fine.
On an unrelated note, the comment on line 822 seems unfinished. It works around an issue in what?
> Teambuilder: fix teams disappearing when dragging within folder

- js/client.js
The test client uses `location.search` to connect to private servers but it's not allowed to access history.
> Ignore location.search in the test client

- js/battle.js
DG9 had challenged Quantum Tesseract to a Balanced Hackmons battle. His team was two Rayquaza-Megas, a Gengar, a Palkia, a Mega Tyranitar, and a Registeel. On turn 11, he mega-evolved his Rayquaza-Mega, although it was really his Illusion Gengar. Then when he later switched his (now Mega) Gengar back in, the client started to get confused, because this was a Pokemon that it hadn't seen in the Team Preview. But this is just standard for Hackmons.
The problem arises when one of his Rayquaza-Megas fainted. Later, he wanted to bring in his other Rayquaza-Mega. The client duly started to created a second Rayquaza-Mega because it had seen two in the team preview. But, the client was still confused by Gengar's Illusion, so in order to reduce the team size, it looked for a random unfainted …
> Don't faint a newly created Pokemon to reduce the team size

- js/client-chat.js
`|uhtml|id|html`
If a uhtml element exists already, update it.
If not, add one to chat.
if "html" is blank, delete the uhtml element from chat (not just make it blank).
Breaks anything that needs to add multiple uhtml elements to chat (any suggestions for this? or just let them break.)
`|uhtmlchange|` deprecated
> Refactor |uhtml|

- js/battle.js
@Zarel I think I understand what you meant for the other comment: the real bug is that the Random Battle gametype checking failed, everything else works as normal.
Sorry, I wasn't sure how to handle updating a pull request, so I did a hard reset to upstream and recreated the commit.
> fix species clause checking for gen7randombattle

- js/client-chat.js
If the user list is maximised and then hidden (e.g. by switching rooms), it takes two clicks to maximise it again, because it hasn't been hidden properly.
> Properly hide maximised user list

- js/battle.js
The server sends the user's rank as the prefix. (I discovered this while trying to implement user lists for battle rooms.)
> Remove surplus space prefix from battle room users

- js/battle.js
Issue: If a Magic Guard/Poison Heal Pokemon is badly poisoned, the
tooltip will always say, "Next damage:/Would take if ability removed:
6%”. If the ability is removed, the forecasted poison damage will be
one turn behind. The reason for this is that currently, the Toxic
counter only increments if the client receives a message indicating
that the Pokemon has taken Poison damage.
Proposed fix: The Toxic counter is now handled under upkeep; at the end
of every turn, all active Pokemon are checked for Toxic status, and
their counters are each incremented accordingly.
> Fix toxicTurns counter for Magic Guard/Poison Heal

- js/search.js
* The additions to abilities lists certain abilities as recommended for the most viable Pokemon in AAA and BH
* The additions to the STABmons move checking fixes the move listing for alternate formes
* The tier addition fixes the bug that causes Mimikyu-Busted-Totem to be listed as "undefined" in the teambuilder without making an exception specifically for Mimikyu.
> Teambuilder: Adjust OM support and fix Mimikyu's tier

- js/client-battle-tooltips.js
Although the tooltips show the added type they don't show a changed type (e.g. Soak, Color Change).
> Use current type in tooltip calculations

- js/client-battle-tooltips.js
Right now, when using items such as Power Anklet, the speed is not shown as being halved.
> Power Lens and co should now correctly show Speed halved.

- js/battle.js
When Mummy activates but fails due to Protective Pads, it will send an -activate message, but not the old/new ability of the attacker. Previously, it would throw errors when trying to animate the ability change. Now it just shows this:
> Don't throw errors when trying to animate Mummy activating but failing

- js/client-chat.js
As described by Zarel.
However, currently the preference would not last beyond a refresh, which would be quite annoying if someone really doesn't like the afd sprites. We could add a setting, and then have the value of Config.server.afd be `!settingToDisable && valueSetByZarelDuringAfd`? That would stop people from enabling them when it's not AFD though. Otherwise we'd need 3 values - "always off", "always on" and "only on during AFD".
Also, currently this requires opening/closing the battle room to have it take effect. There is a `Site.updateSprites()`, but that will have all sprites hidden and not properly positioned. Is that intentional or can the method be modified to properly display the active mon?
> Add client command to disable AFD sprites

- js/client-chat.js
Previously, messages would still go through because locked/semilocked users were considered as having auth in the room.
> Fix ignoring for (semi)locked users

- js/battle.js
The weight would not get updated after transforming, so Grass Knot/Low Kick were based off (e.g.) Ditto's weight instead.
Not sure if getting the weight from BattlePokedex is the right approach? Should I make a "baseWeight" property instead or something like that?
> Battle tooltips: fix weight-dependant move BP against transformed targets

- js/battle.js
Something I noticed when setting trick room with `/editbattle`
I'm not sure if this is an issue in un-edited battles, so feel free to reject this if you don't care about protecting against this issue from `/editbattle` or `/evalbattle`.
> Suppress crash in trick room

- js/battle.js
- js/client-battle.js
Since removing the nicknames is done by adding a CSS class, add the same class to the messagebar.
(is there a better name for that temporary move/switch popup message thingie than "message(bar)"?)
> Fix Ignore Nicknames setting not applying to messagebar

- build-tools/build-indexes
- js/search.js
- make sure CAP uses the singles teambuilder table (since that's where the CAPmons are)
- reorder to CAP -> CAP NFE -> CAP LC (was CAP -> CAP LC -> CAP NFE)
> Teambuilder: Fix CAP LC list

- js/client.js
Most notably, testclient always had afd enabled. Not sure how it's disabled on main, as an unstaged change? or an unpushed commit?
> Disable AFD mode by default

- js/search.js
In particular, this is so that when you search "mega" in the teambuilder, you don't get Megazard/Mega Mewtwo twice. These have two aliases each (like megacharizardx/megax) which are not consecutive, so they were not caught by the previous duplicate check.
> Teambuilder: Prevent some instances of duplicate search results

- src/battle-animations.ts
previously set in the sprite constructor
> Set cryurl properly

- js/client.js
Usernames must contain at least one letter or the auth server will reject them; a number isn't enough.
> Fixed message when changing to invalid nick

- src/battle-dex.ts
- src/battle.ts
See this [replay](https://replay.pokemonshowdown.com/gen7hackmonscup-773575134) although given that this is Hackmons Cup it's actually a (female) Salandit that impostors Rotom, but I assume female Smeargle using Transform on Rotom would exhibit the same bug. Since Salandit is female, the client tries to look for a female Rotom sprite but actually finds the Rotom-Frost sprite instead.
I'm assuming here that Transform copies the visual appearance of any gender the target has, so apologies if that is in fact incorrect mechanics.
> Fix Transform of female Smeargle into Rotom

- src/battle.ts
`fastForwardOff()` calls `animationOn()`, which scrolls to the bottom based on a field set by `animationOff()`. During a normal, non-replay battle, this field is permanently set to true, because `animationOff ` is not called again after initialization (where it is called to fast forward to the start of the battle). `nextActivity` is called every turn and after every received message I think, hence the constant scolling.
This way, it only scrolls in replays when the user is actually fast forwarding to somewhere.
> Stop battles from scrolling to the bottom constantly

- src/battle.ts
Reported [here](https://www.smogon.com/forums/posts/7892468). This is caused by a floating-point error; `58 / 100` is slightly less than `0.58` so when you `* 100` the result is slightly less than `58` and gets floored to `57`; performing the multiplication first makes floating-point errors less likely. I also changed one other place that divides first although that then rounds the result so the problem may be less apparent there anyway.
> Avoid floating point error in health parse

- js/client-battle-tooltips.js
All this is basically just removing the `if (move.desc)` around the whole tooltip.
There are moves that don't have a desc, but all moves have a shortdesc. Both branches of the condition already support longdescless moves.
On a related note, is it supposed to be the case that the priority/flag/ability boost hints in the move tooltip are only shown in the current gen?
> Tooltips: Properly show shortdesc for moves without long desc

- src/battle.ts
Issue: #1154 
Fixed the toxicTurnCount to accurately represent toxic orb poisoning by making toxic orbs first turn's toxicTurnCount = 0
> Fix Toxic Orb and 'Next Damage' toolbox interaction

- src/battle.ts
From issue: https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-381371924
Removed Autotomize tag from pokemon who undergo formeChange in battle
Server side fix: https://github.com/Zarel/Pokemon-Showdown/pull/4893
Replay download showing it works on the server side: https://drive.google.com/file/d/1LdIgE0evOpPWvAbbGFrFL-GLa51XXWmQ/view?usp=sharing
> Fix Forme Change and Autotomize Interaction (Client Side)

- .gitignore
- package.json
- src/battle-animations.ts
- src/battle-dex.ts
- src/battle-scene-stub.ts
- src/battle.ts
- test/battle-test.mocha.js
Adds a way to instantiate a `Battle` object that works in non-browser environments (e.g. Node, V8) with minor modifications. Fixes #1148.
To do:
> Headless client

- src/battle-text-parser.ts
The number of hits is the 3rd argument rather than the 2nd which is the Pokemon that was hit.
> Fix multi-hitcount message

- js/client-battle-tooltips.js
Not sure if this is the cleanest way of doing it, but other sections of the file have tier.indexOf('Random Battle') so I figure it should be okay.
> Hide Abilities in Let's Go Tooltips

- src/battle-log.ts
Something to note: battle-log.ts uses both `this.escapeHTML` and `BattleLog.escapeHTML`. I assume which is used depends on where in the code its being called from.
In this case, `this` refered to `window` when parsing HTML from !events, and subsequently crashed.
Let me know if this isn't the correct fix.
> Fix escaping HTML in localized time

- src/battle.ts
The animation (and stat bar update) got lost as part of f6c03e0.
I happened to noticed this because I was watching [turn 6](https://replay.pokemonshowdown.com/gen7doublesou-824109348).
> Fix stat copying

- src/battle-text-parser.ts
At the very least this fixes Substitute when a Substitute is already up, but probably also fixes other cases such as reapplying status or as Sky Drop's too heavy to be lifted.
> Fix some specific failure text cases

- src/battle-text-parser.ts
At least with the current battle engine, partial trapping passes the effect as the second argument. I checked and all of the other users of `-end` have custom templates already.
> Fix message when partial trapping ends

- data/text.js
- src/battle-text-parser.ts
In Gen 1, partial trapping prevents you from moving. The old code used to check whether a move had been provided and if so display "can't move" instead of "can't use " + move. However I guess the right way to do this is to add a "partiallytrapped" effect template instead.
> Fix Gen 1 partial trapping message

- js/client-teambuilder.js
the stat value must be floored before being passed into the friendship boost calculations to avoid rounding inaccuracies.
> Correct rounding error in Lets Go stat calculation

- src/battle.ts
I'm not sure that Reflect Type ever animated the new types.
Example replay: [Turn 15](https://replay.pokemonshowdown.com/gen7hackmonscup-826853073).
> Fix Reflect Type copying types

- src/battle-text-parser.ts
It exists in `data/text.js` but there's no use of it yet.
> No message for use of Rest

- src/battle-text-parser.ts
Of the 29 (if I counted correctly) Abilities that use '-activate', 15 of them have a custom message, while the other 14 only use it for the "[Pokémon's ability]" and don't want a default message.
For instance, suppose Gligar uses Toxic against Mew, then the expected battle log is as follows:
Gligar used **Toxic**!
The opposing Mew was badly poisoned!
[The opposing Mew's Synchronize]
[Gligar's Immunity]
It doesn't affect Gligar...
Here, Gligar's Immunity activates on an '-immune' rather than on '-activate', but Mew's Synchronize has to be an '-activate', since there's nothing for it to attach to.
> Ability activations have no default message

- data/text.js
The old code actually used "because of [effect.name]" but I'm not sure how that would be implemented.
> Restore Mind Blown recoil message

- src/battle-text-parser.ts
`ability` is the weather setting ability in this case, and the primal weather blocking it is in `kwArgs.from`.
> Fix weather blocked by primal weather

- data/text.js
I saw this with Flower Veil myself; the Ability activated on the correct Pokémon but the protected Pokémon was not correctly identified, instead the message just said "[TARGET]". I assume the other two Abilities work in the same way.
> Fix some messages for abilities blocking effects

- src/battle-text-parser.ts
Reported [here](https://www.smogon.com/forums/posts/7977870). The message only appears to have one placeholder, which is fortunate since the server only sends the target anyway.
> Fix target of future sight message

- src/battle.ts
As part of commit fc603c0 the `useMove` code so that used to actually log the message got refactored out. As such, the `kwArgs.silent` guard was also removed. However, the `-anim` code was relying on the side effect of setting `kwArgs.silent` to suppress the other bookkeeping that `useMove` does, such as deducting PP. As such, `-anim` now causes a deduction of PP. This is particularly noticeable in Super Staff Bros Brawl but also anywhere `-anim` is used such as for Solar Beam in Sun.
To simplify the code, I've split the bookkeeping away from the animation so that `useMove` now calls both (and also the message logging) while `-anim` now just invokes the animation.
> -anim should only animate

- src/battle-text-parser.ts
Both currently send the target in `kwArgs.of`; `pokemon` is definitely not the target here! (The other effects listed don't use `[TARGET]` anyway so they don't care.)
> Fix Forewarn and Symbiosis

- data/text.js
- src/battle-text-parser.ts
Currently it's acting as if the victim of the damage was holding the berry.
I couldn't think of any other effects that should use that message.
> Fix message for Jaboca and Rowap Berry

- js/search.js
For formats without entries in the respective generation's formats-data.js file, such as DPP PU, there is no tier slice to display, so instead it displays every tier from CAP down to LC.
> Fix teambuilder tables for formats not in formats-data

- src/battle-text-parser.ts
Reported [here](https://www.smogon.com/forums/posts/8001912) with this [replay](https://replay.pokemonshowdown.com/gen7challengecup1v1-844240852).
I changed the template code because I liked the version used by `-boost`.
While I was there I changed `[EFFECT]` to use `effect` (!) as this makes it work for custom effects such as those in Super Staff Bros Brawl.
> Fix Attract message for Destiny Knot

- src/battle-dex-data.ts
Dex.getItem did not copy over these ``on[...]`` values so these moves would always appear as normal-typed in battle.
> Fix Judgment/Multi-Attack/Technoblast type display in battles

- src/battle-log.ts
Warning and muting unlink without hidetexting, so this makes the behavior consistent between chat and battle rooms.
> Re-implement unlinking in battle chat

- build-tools/build-indexes
As of gen 7, Aguav and friends are actually useful.
> Teambuilder: Properly label healing berry usefulness in gen 7

- src/battle.ts
The statbar wasn't actually being updated immediately, so the status marker only disappeared during the animations of the next turn.
> Clear statbar of lingering expired turn statuses

- data/text.js
The message gets templated correctly, it's just the string itself is missing.
> Restore missing Grudge activation message

- js/search.js
No moves were being displayed for stuff like Sawsbuck-Autumn or Gastrodon-East, since they don't have entries in pokedex.js, so we need to check the aliases as well.
> Teambuilder: Fix no moves displayed for visual formes

- js/search.js
"TR" is an alias of Trick Room, but it was being skipped because Trick Room itself starts with these letters and it wasn't included in the exceptions.
The second condition is apparently needed to prevent duplicate results, but move results don't get duplicated and that's why we can do this? I'm not sure I understand how it works exactly but this seems to work.
> Teambuilder: Make Trick Room first result for 'TR'

- js/client-battle-tooltips.js
- Trump Card now shows as having 5 PP in tooltips as it does on the simulator
- Pressure won't cause tooltips to show -1 PP anymore
> Fix PP in tooltips (Trump Card, Pressure)

- src/battle-tooltips.ts
Sucker Punch under Dark Aura has the not-very-beautiful base power of 93.10000000000001. With this, it only shows 2 digits past the decimal point. Casting back to Number gets rid of trailing zeroes from `toFixed()`.
> Tooltips: Only show 2 digits max after decimal point

- src/battle-tooltips.ts
Rivalry had the boosts switched, PT/SP used the target's boosts instead of the source's.
> Tooltips: Fix Rivalry and Power Trip/Stored Power

- src/battle-dex.ts
After being run through `overrideAbility `and `removeSecondAbility`, the updated abilities were never actually written back into the data.
> Fix Pokemon being shown as having their current abilities in older gens

- src/battle-tooltips.ts
`getItemBoost()` existed, but was never actually called.
> Tooltips: Fix item boosts not showing up

- data/text.js
Example reply: https://replay.pokemonshowdown.com/gen7balancedhackmons-867946763 (turn 10).
Commit 2b14006 seems to have accidentally completely removed the message for Queenly Majesty.
> Fix missing message for Queenly Majesty blocking a move

- src/battle-text-parser.ts
Report: https://www.smogon.com/forums/posts/8050534
As I understand it, the log should look as follows:
[POKEMON's Mummy]  
[TARGET's ABILITY]  
[TARGET's MUMMY]  
TARGET's Ability became Mummy!
However this never happens because Mummy doesn't have an activation message and so the code early returns before it can reach the special case for Mummy, and the code also activates the abilities on the wrong target anyway (because that's really for Skill Swap which works differently).
> Fix activation of Mummy

- js/client-chat.js
- js/client-topbar.js
One misleading thing is the 'Usable Formatting' information says to use `Cmd + <X>` because I'm on a Mac, but both `Cmd + <X>` and `Ctrl + <X>` (for `X = B or I`) work on my machine, but the 'grave accent' (I don't know how to escape it in GH markdown! :P) only works with `Ctrl`
> Add Ctrl+` as a keyboard shortcut for ``code``

- build-tools/build-indexes
The learnset table build script did not take into account that HMs cannot be transferred from gen 3 to 4 and 4 to 5. This led to, for example, Exploud having Rock Climb displayed as legal in gen 4-7 (it's only legal in gen 4) and Pikachu having Surf displayed as legal in gen 5.
(Yeah the condition could probably be made a bit prettier)
> Don't display illegal HMs as legal in Teambuilder

- js/client-chat.js
Resetting the battle also resets the playback state, so it needs to be extracted before that.
If the battle is finished, fast-forward directly to the end so it doesn't redo the last turn's animations needlessly.
> Fix battle playback state after using /afd

- src/battle-tooltips.ts
There's a mistake (?) in the toxic display that causes next damage to display as `6 * toxicTurns` instead of `1/16 * toxicTurns`.
This doesn't really affect gameplay at all, and actually keeps the display more in line with what the mon's toxic damage message, but it _is_ still a mistake and it annoyed me enough to spend 5 minutes fixing it
> fix toxic damage display

- src/battle-tooltips.ts
These ability checks were using the client pokemon, which won't contain ability information if the ability does not announce itself. This meant that Plus, Minus and Victory Star just didn't work in tooltips. I changed it to use the server pokemon instead.
I also applied that change to the Cherrim check, even though it currently works, because the boost is only active after the forme change which announces the ability. I don't know if this is worth it, but it feels so brittle to rely on the other behavior.
> Tooltips: Fix Plus/Minus/Victory Star

- build-tools/build-indexes
- src/battle-dex.ts
This is relevant for the Scolipede line (used to have Quick Feet instead of Speed Boost) and Aurumoth (used to have Illusion instead of Light Metal).
I don't know if just slapping new properties into the teambuilder tables like this is the best solution, but it works at least.
> Teambuilder: Fix changed hidden abilities in older gens

- .eslintrc.js
- js/client-chat.js
- js/client-topbar.js
- js/client.js
- src/battle-dex.ts
- src/battle-text-parser.ts
- style/client.css
Client changes for Zarel/Pokemon-Showdown#5002.
- make user names which are away show up in grey
- sort users who are away to the bottom
- add an 'Away' pill where approriate (not 100% on the styling)
This should be as backwards compatible as possible (it might interpret names ending in `@` as away when really they're just legacy, but thats an artifact of the protocol).
> Handle AFK '@-in-names' protocol

- .eslintrc.js
- js/client-chat.js
- js/client-topbar.js
- js/client.js
- src/battle-log.ts
- src/battle-text-parser.ts
- src/battle.ts
- style/client.css
Rollforward of #1265. **Currently this is unchanged from what was committed and then rolled back** (thus why this is a draft), but I will be going through everything in [`git grep users`](https://gist.github.com/scheibo/9b74f47f1299778b68b7075f9308b011) to avoid breaking things.
> Handle AFK '@-in-names' protocol (take 2)

- src/battle-log.ts
RIP dreams of `{pre: '#666'}`.
> Remove Config.customcolors 'color' options

- src/battle.ts
`Pokemon#isGrounded` was erroneously returning `false` in a lot of cases because of a flipped operator, which mostly showed itself in moves lacking their terrain boosts.
I suppose the choice between using `else if` and just chaining `if`s with early returns here is a matter of taste, I switched to the latter because that makes it consistent with the conditions immediately above, and the previous inconsistency was more confusing to read at a glance.
> Fix groundedness check

- js/client.js
- src/battle-log.ts
- src/battle-text-parser.ts
https://github.com/Zarel/Pokemon-Showdown/pull/5002/commits/e373c1d026ef4f70a3ee25c133dacfbf0333ef93 will cause the rank to sometimes be erroneously displayed in the UI: 
Zarel/Pokemon-Showdown#5002 will not _break_ the client when it lands, but to preserve the current display semantics **this PR should be committed and pushed in coordination with the server restart that  deploys the protocol change**. I've marked this change as 'DO NOT MERGE' because if deployed without the server change it will result in lopping off the first character of usernames, which is clearly undesirable.
> Don't include the ! in away status display

- js/client.js
Self explanitory. User's clients are crashing when they load up so this is high priority.
> Fix crash with tournament preferences

- js/search.js
This fixes a regression introduced by 9114cb98945a12b2de01319294a47335dda0fa66. This was a quick and dirty fix, so there is a possibility it breaks again.
Licensing is covered by: https://github.com/Zarel/Pokemon-Showdown/pull/2853#issue-90513765
> Teambuilder: Fix pokemon display for Doubles.

- src/battle-tooltips.ts
1. Use the battle's modded dex instead of the default gen 7 one
2. Change the conditions in `getPokemonAbilityData()` so it's no longer possible for ability and baseAbility to both be set to the same value (which was happening in oldgens randbats for some reason).
> Tooltips: Fix possible abilities display in old gens

- js/client-teambuilder.js
Really like this project and want to contribute so I took a shot at one of the items on the new develops issue. 
Please let me know if this is on the right track / feedback / what to add / is this still needed?
Supports search on / Pokémon / ability / item / move / anything in unpacked team:
> Advanced search in Teambuilder

- js/client-chat.js
Battle join/leave was fixed to include group in #1295, but apparently chat join/leave should show group as well.
> Include group in join/leave messages

- js/client-battle.js
- js/client-topbar.js
- js/client.js
It seems like the mute preference (or any preference really) should be a [User-level scoped Custom Dimension](https://support.google.com/analytics/answer/2709828?hl=en) that gets updated when the pref gets updated (ie. set in `Storage.whenPrefsLoaded()` and when it's toggled), only this doesn't accomplish much because we need an event for the custom dimension to be sent with. We can't send this dimension with the `ga('send', 'pageview')` metric because that happens on page load, before we have prefs available (and also doesnt cover changes in the pref's value over the session). 
Instead, I've created a 'join battle' event (event category `'Battle'`, event action `'join'`, [per the documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#event_fields)), …
> Add analytics to track battle sound preferences

- src/battle-animations.ts
- src/battle.ts
Server Pull Request: Zarel/Pokemon-Showdown#5595
Suggested and approved here: https://www.smogon.com/forums/threads/3651687/
I did not implement the "make `/rank` only display the tier of the battle you're playing in" suggestion because you can use `/rank [player], [format]` or with this change it's even easier because you can just scroll up.
> Display Elo in rated battles

- js/search.js
Since it has 90 acc in gen 1, it's a pretty commonly used on many mons that get it.
> List Blizzard as viable move by default in gen 1

- src/battle-tooltips.ts
It always compares the weather by name, not id. Unlike Rain Dance etc, these are not moves, so getting the name requires `getAbility`ing them.
> Tooltips: Fix weather checks for Primordial Sea/Desolate Land

- src/battle-dex-data.ts
Castform-Rainy's sprite is defined twice. Further, the second definition actually points to Castform-Snowy. This causes Castform-Rainy to appear as Castform-Snowy.
https://i.imgur.com/K9wS7K4.png
> Fix Castform-Rainy

- desktop/package.json
Restrict node-remote to https as per suggestion in https://github.com/Zarel/Pokemon-Showdown-Client/pull/1246#discussion_r290869251
no-edit-menu defaults to false since v0.7.3 (https://github.com/nwjs/nw.js/wiki/Manifest-format#no-edit-menu) to current (http://docs.nwjs.io/en/latest/References/Manifest%20Format/#no-edit-menu-mac)
> Desktop: Small package.json changes

- js/client-chat.js
I took inspiration from @submindraikou's Pull Request (Zarel/Pokemon-Showdown-Client#747), which unfortunately became inactive after some time.
Here's an example of the new format: `{global: ['jet'], localhost#development: ['.*']}`.
Old highlights are converted by moving all the highlights to the `global` array.
(I'm not very good at writing simple, concise English sentences, so I'd appreciate if someone looked over the help entries and messages sent.)
> Support room highlights

- js/client-rooms.js
(Server PR: Zarel/Pokemon-Showdown#5662)
Suggested and apporved here: https://www.smogon.com/forums/threads/3653073/
I made it run on button click instead of on input, because sending `/cmd roomlist` on every character is kind of ludicrous.
The button technically does have the same function as the refresh button, but it's less confusing to users.
> Allow filtering by userid prefix in battle search

- replays/replays.lib.php
- replays/search.php
This is a step towards #1307, where eventually we will support calling `search` with any combination of player username, opponent username and format.
> Unify username and format replay search internals

- replays/replays.lib.php
I'm pretty sure `ORDER BY` can't be parameterized in MySQL
`LIMIT` definitely can't be parameterized as seen in https://github.com/Zarel/Pokemon-Showdown-Client/commit/8ca9916bdcb35b9a7cfe1b6a56d4d3efacb4550b
(There was also a missing `ORDER BY` in the prepared statement.)
> Fix replays ordering

- src/battle-tooltips.ts
This is, again, for "Ability: Levitate (base ability: Levitate)".
The last time I thought I'd remove the duplication in the get-the-data code, but it turns out the ability data is sometimes an ID and sometimes a name, throwing everything off. I don't want to have to deal with having to toID all over the place, so I put the check in the display code after we got the proper name regardless so we can compare freely.
> Tooltips: Properly prevent duplicate ability display

- build
- build-tools/build-sets
Required for #1357. We're installing with `--no-save` because we pretty much always want the latest version and don't want to deal with the hassle of updating deps in `package.json`.
> Import @pokemon-showdown/sets during build

- js/client-chat.js
Most notable when you type a message that leaves idle state in a PM or left window, it'll steal your cursor to the right chat room.
> Don't steal focus from a textbox when updating user

- lib/dispatcher.lib.php
Relevant if someone accidentally prefixes / appends a character to an already long name.
> Don't error out incorrectly for ladder ranks with a long input name

- src/battle.ts
As far as I can tell, this comes from #1071, which was from a much, much older name format and isn't necessary anymore (rank isn't included as any part of the name string anymore)
> Stop prefixing battle names with a space

- src/battle.ts
Did not use `endsWith` since I'm pretty sure thats unsupported by older browsers.
> Support custom terrains being overwritten

- js/client-chat.js
- js/client-topbar.js
When changing your avatar with /avatar [number], or when using the popup menu to select one, the success message has a broken image:
because it sends the avatar number directly to the server, and avatars are organized by name instead of number now, so the server has no way to display the new avatar. This way we'd just always send the name.
> Fix broken avatar change messsage when using avatar numbers

- src/battle.ts
Currently if you fast-forward past a spread move then the log just says "A critical hit!" or "It's super-effective!" or "It's not very effective..." instead of naming the target like it does when playing at normal speed.
> Display spread move target even during fast forward

- js/client-battle.js
- src/battle-tooltips.ts
The first issue was that Z-Hidden Power wrongly displayed its type as that of the base Hidden Power instead of normal (in the move selection, not the tooltips). So I made it base the type of the actual Z move, if a separate object is available, and only fall back on the base move if there is none (like for Z status moves).
The second issue was that Z-Hidden Power did not have a base power displayed in the tooltips, because only the base HP has a zMovePower, the typed ones don't. Instead of adding that property to all hidden powers I opted to make it fall back on the base move here. I can do the former instead if you'd prefer.
> Tooltips: Fix type/base power of Z-Hidden Power

- src/battle-tooltips.ts
This way it will use the speed calculated clientside with all factors, including things like paralysis, which serverPokemon.stats does not include.
> Tooltips: Fix Gyro Ball/Electro Ball base power while paralyzed

- js/client-mainmenu.js
I see no reason for gvoices to be immune to /ignore, and someone brought it up to me as a weird thing they noticed, so might as well.
We could probably also turn it around and have a list of staff symbols that can't be blocked by ignore.
> Allow /ignore to block voices in PMs

- js/client-teambuilder.js
- src/battle-tooltips.ts
Changes gen7metronomebattle to gen8metronomebattle in relevant sections, affecting the suggested spreads and auto-adding 252 EVs to every stat features. Gen 7 Balanced Hackmons also has a mention in client-teambuilder.js, but I'm unsure about that so I'm keeping it simple for now.
> Make Gen 8 Metronome Battle ignore EV limits

- js/search.js
The event-only Gmax Pokemon (Eevee, Pikachu, Meowth) currently only have four moves in their movesets; this fixes that issue and also any potential future encounters with event-only Gmax Pokemon.
> Fix learnsets for Gmax formes

- js/client-teambuilder.js
This PR is based on https://github.com/smogon/pokemon-showdown-client/issues/1349, which is a feature I've wanted for some time myself. It only attempts to import if a valid-looking URL is the *only* thing in the team textbox, and it only looks for a single URL. I figure this meets 95% of actual use, and so is a good place to start.
I've attempted to match the style of the surrounding code, but please let me know if there's a different preferred style for anything.
I used $.ajax rather than $.get in order to bypass the testclient CORS helper - it doesn't play nicely with multiline return values. Due to the fact that pokepast.es insists on https, you'll also have to either host testclient.html on https localhost, or temporarily disable your browser's content security policy. This of …
> Teambuilder: Import teams from pokepast.es or gist urls

- js/client-teambuilder.js
I also added support for Hidden Power type in the details box
This handles https://www.smogon.com/forums/threads/remove-happiness-and-hp-type-from-teambuilder-in-real-generation-8-formats.3657922/
> Remove Happiness/HP Type from normal gen 8 teams

- js/client-teambuilder.js
Based on https://github.com/smogon/pokemon-showdown-client/issues/1357, this PR causes the teambuilder to import sets from smogon (based on team format) and provides buttons to easily fill them in on the "Import Pokemon" window.
It currently offers a button for all available sets, both official and "Showdown Usage". This has looked decent on the 'mons I've tested so far. It doesn't show any error on a failed import, because there aren't sets available for all formats (eg, gen8vgc2020), and it didn't end up feeling right to show anything visually.
> Import sample sets from smogondex for teambuilder

- js/client-teambuilder.js
The code comment should explain what went wrong and how it's fixed.
Basically, I forgot that jQuery - trying to be helpful - would parse the response into an object unless asked not to.  Inconsistency between the CORs helper and the actual implementation.
> Fix import of smogon sets

- src/battle-tooltips.ts
I also added tooltips for the defender-based Utility Umbrella changes
> Tooltips: Remove Choice item boost from Dynamaxed Pokemon

- js/client-teambuilder.js
This is an easy fix for https://github.com/Zarel/Pokemon-Showdown-Client/issues/1331. Note that it will still auto adjust the Speed IV, ie. if you have both Transform and Gyro Ball on Mew for example, so the behavior is not completely fixed. That should be easier to deal with once https://github.com/Zarel/Pokemon-Showdown-Client/pull/1333 is merged.
> Do not change attack IVs for Pokemon with Transform

- src/battle-tooltips.ts
Just a quick change to display Aura Wheel as Dark type when in Morpeko-Hangry form. It already calcs the move as Dark type, but in the move selection it showed as Electric type and that could confuse some players. 
If there's anything that needs to change or if this is not a valid feature let me know, this is my first time contributing to the repo =D
> Switch Aura Wheel display type when Morpeko-Hangry

- js/client-teambuilder.js
I noticed that #1442 did not seem to be working properly. This is because `moves` is always a length 4 array, ie. it's represented as `["Transform", "", "", ""]` rather than `["Transform"]`.
> (Really) maximize Attack IVs if Transform is the sole move

- js/search.js
- src/battle-dex.ts
This fixes the issue where Pokemon in past-gens doubles formats would have their tiers display as their gen 8 singles tiers (corsola in gen 4 doubles would display as unreleased) and also where Mega Pokemon in past gens would have their tiers appear as their base forme's
> Fix teambuilder tiers for previous generations

- build-tools/build-indexes
- js/search.js
- src/battle-dex-data.ts
Currently, Pokemon with no access to their hidden ability in gen 8 (such as clefable) can still use them in gen 7, etc; however, the teambuilder still crosses them out.
> Fix unreleased hidden abilities in past gens

- build-tools/build-indexes
Heavy Duty Boots should go in the Popular items section. I discussed this briefly on the Discord and the reception was unanimously positive.
I would like Expert Belt and Room Service to be added to the Popular items section as well.
> Add Heavy Duty Boots, Expert Belt, and Room Service to Popular items

- action.php
- crossprotocol.html
- desktop/index.html
- index.template.html
- preactalpha.template.html
- recoverteams.html
- style/hpbartest.html
- testclient-beta.html
- testclient.html
This adds the BOM to all HTTP pages as per the HTML5 spec and ensures
all pages use UTF-8 as their meta charset (which is still kept for
compatibility with older browsers).
If this PR is alright, main's client sets the encoding to ISO-8859-1 in the `Content-Type` header. This can mess with older browsers when combined with this, so it'd need to be changed as well.
> Properly set the encoding to UTF-8 on all HTML pages

- build-tools/build-indexes
- js/search.js
This removes redundant code and also fixes a bug where Pokemon that were LC/NFE would appear twice in the teambuilder
> Simplify the NFE teambuilder and fix bugs

- src/battle-animations.ts
The themes would not play because we were tracking what theme to set
to with BattleSound.bgmNum. When loading a new bgm, BattleSound.setBgm
will simply return if the existing bgm (BattleSound.bgm) is the same
as the one were trying to set the bgm to.
Been meaning to fix this for a while but didn't get to it till now.
> Fix Miror B Easter Egg Themes

- src/battle-dex-data.ts
The regular sprites can also be used for sinistea-antique and polteageist-antique
> Add Sinistea and Polteageist minisprite indexes

- js/client-chat.js
- js/client-mainmenu.js
(allowing for `|c|user|/raw` messages to be hidden, among other things)
clientside half of https://github.com/smogon/pokemon-showdown/pull/6444
> Attribute /raw messages, fix /uhtml in chat

- src/battle.ts
- `tsc` presumably covers us within `src`
- per `#sim-dev` I checked `replay.js`, `replay-embed.js` and `client-battle.js`
- the two replay files are short and I have high confidence that they are not relying on fields from `Template`
- I searched for `'okemon'` and looked at the 142 usages in `client-battle.js` and none appear to be using `Template` fields. no strong guarantee here given nothing is typed, but this is an easy enough change to rollback
> Remove getTemplate call from Pokemon constructor

- js/client-chat.js
- src/battle-log.ts
Reference: https://github.com/smogon/pokemon-showdown/pull/6471
This is a client-side patch that modifies hidetext messages to support an integer parameter of lines to hide. Default is still all lines, but now a supplied number of lines can be hidden as well.
> Support /hidetext linecount client-side

- js/client.js
- apply same "You are disconnected and cannot chat" message to battles upon disconnecting from a server.  Just a tiny pet peeve when testing code on localhost.
> Disable battle chat upon disconnection

- js/client-battle.js
Max Moves were previously displaying in doubles as regular attacks on any turn that wasn't the initial turn of Dynamax. This was because the conditions for showing the Max Move as the max move proper would only occur when the length of the array of parts for a user command was less than 2, which doesn't happen in doubles because doubles also sends the target of its attack.
This also sneaks in a capitalization for Dynamax; the game text capitalizes Dynamax, unlike mega evolve.
Before:
After:
> Fix display of Max Move used in doubles

- build-tools/build-indexes
Meltan and Melmetal should've had their tiers unhardcoded as soon as Pokemon HOME came out, I just forgot to remove it.
> Fix National Dex teambuilder

- index.template.html
- js/client-teambuilder.js
- js/search.js
- testclient.html
This will prevent us from needing to maintain two search engines in the future.
The new DexSearch doesn't have too much in the way of new features so far, but it does show filtered things in categories, and list illegal results in-filter even after sorting.
These are really minor differences, though; the main thing is just that its architecture should make it much easier to maintain, and in particular, to add more filters.
> Use DexSearch for the teambuilder search engine

- src/battle-dex-search.ts
This makes it that looking up moves now correctly filters in Battle Spot/Battle Stadium formats, and searching for moves that were dexited in Gen 8 will no longer work outside of National Dex formats.
> Fix `canLearn`'s filtering

- src/battle-dex-data.ts
- src/battle-dex-search.ts
Viable moves no longer use the `isViable` flag. Instead, we start by assuming moves with 75+ base power are not useless (and others are useless), and manually list exceptions in the relevant dexsearch function.
In general, the move viability system has been a bit too specific. I don't want to hardcode species because it's nearly always also hardcoding specific metagames. It may help to think of it as "would this move be useful in any metagame ever?" rather than "would it be useful in the current metagame".
We instead use a significantly lower bar of "not useless", although this hasn't been made clear until now. The word "viable" is now banished from the codebase as well as the teambuilder's actual text, which may also help.
Select changes:
- doubles moves now have separate viability lists …
> Update "not useless" moves

- js/client.js
Currently, when clicking on a replay link, this happens:
``The room "battle-battle-gen81v1-1115695859" does not exist.``
> Fix replay redirect

- js/client-teambuilder.js
`escapeHTML` doesn't work on numbers, so I ported the Happiness code instead.
> Fix display of Pokémon level in details form

- src/battle.ts
In RBY, Accuracy and Evasion use the same boost table as the other stats. For example, -1 Accuracy or Evasion = 0.66 instead of 0.75. This is implemented on Showdown, but it is incorrectly displayed using the Accuracy/Evasion table from Stadium and GSC onwards.
> Fix RBY accuracy/evasion tooltips

- src/battle-log.ts
Usernames are already escaped on line 104.
> Fix HTML escaping for battle joins/leaves

- js/client-mainmenu.js
- js/client.js
- style/battle-log.css
Client side portion of https://github.com/smogon/pokemon-showdown/issues/6950
- CSS for `.checkbox` was changed to make it optimally aligned on the latest Chrome
- Persisting `serversettings` appropriately was fixed by adding `_.clone` calls so Backbone's change detection will work. This is important for #1271 (though that also requires we send `/updatesettings` on setup and can be done in a followup PR)
- `/ionext` is used instead of `/hidenext` intil https://github.com/smogon/pokemon-showdown/issues/6950 is finished (ie. passwords get added to hidden battle rooms)
One 'gotcha' is that toggling the privacy checkbox in a challenge will not cause the ladder checkbox to update (meaning all of the privacy checkboxes in the UI do not always reflect the current state of the …
> Introduce a "Don't allow spectators" checkbox

- js/client-rooms.js
Turns out this is all it takes (though all of the groundwork was already laid)?
- the `serversettings` pref includes `hideNextBattle` and `inviteOnlyNextBattle`, but these are ignored `/updatesettings` (and I'm not sure its worth plucking them out to avoid roundtripping the ignored settings)
-  i'm not sure if its safe to access `Dex.prefs` in `RoomsRoom` (will it block if storage has'nt loaded etc), but it seems to work in my browser
- this needs to be done before the first message sent to the server (as opposed to before `/trn` as I originally thought) because the response of initial message is going to include the default `|updateuser|` for a Guest which would wipe out the settings otherwise.
*FINALLY* closes https://github.com/smogon/pokemon-showdown-client/issues/1271
> Implement persistent server settings

- js/replay-embed.js
- replays/theme/wrapper.inc.template.php
(mostly) fixes #1560.
`<psicon>` tags still don't work in replays -- there's some sort of odd bug there where the CSS for the image gets removed from the `<span>` tag, and fixing it is much more complicated (and not something I'm making a priority to work on right now). If you don't want to merge this until that's fixed, feel free to draft it -- I might work on this more some other time.
However, !details looks much nicer, as you can see below or at https://replays.ps.annika.codes/gen8randombattle-223.
> Replays: Display !details better

- js/client-chat.js
- js/client-mainmenu.js
Currently, when you do `/chall user, gen8ou@@@inversemod,scalemonsmod`, it only detects the first additional rule. This allows users to do the aforementioned command and actually challenge the target user to [Gen 8] OU + Inverse Mod + Scalemons Mod. This works correctly with `/chall user, gen8ou@@@customrule1,customrule2, customrule(n)` as well.
> Allow for challenging users with multiple rules

- js/client.js
Previously, you would only be able to tell that a user was locked through their usercard if you got that usercard from a room's user list. Now, along with the server PR (https://github.com/smogon/pokemon-showdown/pull/7041) to send groups for locked & namelocked users, locked status will show in all usercards.
> Show locked status in all trainer cards

- js/client.js
Previously, punishments would be shown as both a user's global rank and their room rank when getting a usercard from the room list. (An example is below.)
> Don't show punishments twice

- src/battle-tooltips.ts
Before, Weather Ball displayed as having 100 BP in Delta Stream, which it doesn't.
> Fix Weather Ball display with Delta Stream

- src/battle-tooltips.ts
Previously, Z-moves and Max Moves were not displaying the correct typing / base power in move tooltips; this PR fixes bugs such as https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8505457 or Pixilate Z-Hyper Voice being displayed as Fairy-type.
> Fix type/BP display of -ate abilities + Z/Max

- src/battle-dex-data.ts
Currently, Z-move BP is not displayed because of some additional check in the if statement. Removing it fixes the issue. @KrisXV do you know why it was originally added? 
Fixes bugs such as https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8460441
> Fix Z-move BP display in tooltips

- replays/battle.php
I restored the link's original destination, but I might suggest linking to `https://replay.pokemonshowdown.com/search?user=<user>` instead.
> Fix broken /users/ link

- config/config-example.js
Changes will need to be reflected in an update to config.js.
https://victoryroadvgc.com/ - very popular and influential VGC resource hub; manage streams, host team reports, provide samples / Speed tiers etc.
https://vgcstats.com/ - compiles IRL VGC stats. Not as useful with quarantine and all, but has been a good resource for IRL usage stats at a glance.
https://pikalytics.com/ - combines Battle Stadium and Showdown VGC usage stats. Supports a damage calculator and custom teambuilder.
> Clarify config whitelist settings

- src/battle-sound.ts
I don't claim to understand the old BGM code, but somehow the BGM would always restart when starting a new battle. This doesn't happen with the new BGM code from PR #1563.
- When starting a new battle, we don't have a sound yet. So although we ask to reset it, nothing happens.
- When stopping a sound instance, if it's never played, it won't get rewound.
This changes fixes the second part, and indirectly the first part by making new sound objects always rewind, but if you don't want that, I can fix the first by part instead by changing `src/battle-animations.ts` something like this:
```diff
resetBgm() {
-		if (this.bgm) this.bgm.stop();
+		if (!this.bgm) this.rollBgm();
+		this.bgm!.stop();
}
```
> Ensure that the BGM restarts when starting a new battle

- js/client-ladder.js
This fixes `|tempnotify|` by parsing rows the same way as in `client-chat`.
> Fix |tempnotify| in HTML rooms

- js/client-mainmenu.js
Not sure if this is the right way to do this, but doing it in mainmenu gave access to tools to make the popup easier, and made the most sense since similar initialization things are done there.
> Mainmenu: Show out-of-date app users an error

- src/battle-text-parser.ts
I tested using [this old replay](https://replay.pokemonshowdown.com/nu-593386897), and this appears to be fully backwards compatible. I'll also make a server PR to remove the extraneous side data from Unnerve activation messages, but that one won't be totally compatible with an outdated client, so this for sure has to be merged and public before that is.
> Simplify protocol for the Unnerve ability

- js/client-mainmenu.js
This particularly affected challenging user false, who would properly receive the challenge, but it would be canceled on the challenger's end later due to 'false' !== false in the later check on client-mainmenu:729. I'm not sure if there's a smarter way to do this.
We have more calls to data.('userid') - should I just go ahead and sanitize all of them?
Before:
After:
> Fix challenging "boolean" usernames

- src/battle-dex-data.ts
- src/battle-dex-search.ts
- Fixes a bug where every time you re-click on the ability box for a set in AAA/Hackmons/Metronome Battle, it continues to load the list of abilities until eventually none remain.
- Fixed moves from Alola/Galar formes showing up on the base species of a Pokemon (Dark moves showing on Kanto Moltres when they shouldn't)
- Properly shows moves for both Sketch and Balanced Hackmons
> Fix the teambuilders of various OMs

- src/battle.ts
~I think this should also fix a rare case where a Pokemon A's Sticky Barb is stolen by an opponent through an effect like Magician, then Pokemon A gets the Sticky Barb back via Sticky Barb's effect (which has no message), because it looks like the old code would not have set Pokemon A's item to be a Sticky Barb again after the damage effect since it's previously held item was also a Sticky Barb.~ Edit: nah, that wasn't a problem to begin with.
> Actually remove healing berries after they're eaten

- src/battle-tooltips.ts
I checked through again and didn't find any more hard-coded indexing of `battle.sides`, so hopefully this is the last holdover.
> Fix tooltips for switchables after rejoining

- js/client-battle.js
- src/battle-tooltips.ts
- src/battle.ts
This covers the rest of the missing cases where a tooltip should show the true max move. For example:
- Pixilate Sylveon's Max Strike from Hyper Voice will show Max Starfall
- Galvanize Toxtricity-Gmax's Max Strike from Hyper Voice will show G-Max Stun Shock
- Refrigerate Genesect's Max Strike from Techno Blast will show Max Hailstorm
- Normalize Bug Memory Silvally's Max Strike from Multi Attack will show Max Strike.
This also changes the type shown by the max move buttons themselves to match the true max move.
> Properly interpret Max Moves from base move type

- js/client-battle.js
Previously, if an uploaded replay was already open, trying to open a new one wouldn't replace it automatically.
> Close uploaded replay when opening a new one

- js/client-battle.js
When a `BattleRoom` is initialized, `this.users` is empty, so we can't check if we're the player. The `p1` trick may be a little hacky, but I don't know what a better place for the timer activation is.
> BattleRoom: Fix bug with autotimer

- style/battle-log.css
Ig infobox-limited class is in room intros and in the event box. On mobile phones, it is hard to check the whole room intro or event and you can't slide because overflow for the x axis is hidden. So just removing overflow-x: hidden.
> Add a horizontal scroll bar for "infobox-limited" class.

- website/pages/rng.md
Hey, as I translated the this site to german, I noticed that solely the 3Ds is referenced when describing the RNG used in pokemon games. Now that the switch is the main platform for console pokemon games, it would be fitting to reference it aswell; also I fixed a typo provably->probably.
> Improve RNG article phrasing

- js/client-battle.js
Before, despite having disabled move data, Max Guard would display as clickable, leading to a number of bug reports where users would try to click Max Guard and get confused, not realizing the server had properly rejected their request. I tested with a number of other situations like Disable, Choice locks etc. and everything else seems to be behaving nicely.
Before:
After:
> Disable Max Guard choice on Taunt / Assault Vest

- .babelrc
- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- build-tools/update
These are tooling changes that I made for another upcoming change. I want to get them reviewed in their own separate PR.
**Source maps:**
Unlike the server, these maps are stored alongside the transpired js. Browsers make requests for them when dev tools are in use.
**Launch configs:**
These require an already running HTTP server. You can launch the debugger from vscode and it will build and then launch Chrome.
> Add sourceMaps and vscode debug configurations

- js/lib/preact.d.ts
To support, for example:
(in loop):
`<preact.Fragment key={key}><h3>...</h3><ul>...</ul></preact.Fragment>`
This change also removes "\<undefined\>" tags from the DOM when Fragments are used.
I grabbed the latest from the CDN (2021/01/15):
https://cdn.jsdelivr.net/npm/preact/dist/preact.min.js
> Update Preact Lib for Fragments

- src/battle-dex-search.ts
Now that Zacian-C is AG, we can't use simple hardcodes like before to get Gmax Pokemon out, and we can't just filter them out in build-indexes because some formats _do_ use them.
> Add custom filters for Gmax formes

- .vscode/settings.json
- testclient-beta.html
These are tooling updates that I separated out from #1709
There are improvements that should be made here. Please discuss, and if we should move this PR to draft while they are taken care of, please do so:
1. `testclient-beta.html` should be brought up to parity with `testclient.html`
2. `tslint `is deprecated. Should it be converted to `eslint`?
> Tooling: Preact Client server by URL; tslint

- build-tools/build-indexes
This optimizes JavaScript parsing performance. V8 developers recommend applying this optimization for objects of 10 kB or larger, see <https://v8.dev/blog/cost-of-javascript-2019#json> for more details. Teambuilder tables are 3.5 MBs which is much more than 10 kB.
I have tested this optimization, albeit I don't know whether I have done this correctly. Over multiple attempts, with this change or not, in Firefox, this reduces parsing time from 600ms to 500ms. In Chrome, this reduces parsing time from 200ms to 100ms.
This was inspired by https://blog.guillaume-gomez.fr/articles/2021-01-22+Performance+improvement+on+front-end+generated+by+rustdoc blog post specifically which talks about optimization of rustdoc frontend code, and that was one of optimizations that was done (rustdoc PR: …
> Use JSON.parse for parsing teambuilder tables

- js/client-battle.js
- js/client-chat.js
- js/replay-embed.template.js
- replays/js/replay.js
- src/battle-animations.ts
- src/battle-log.ts
- src/battle.ts
- src/panel-battle.tsx
- test/battle.test.js
The client Battle class API has been pretty old and crusty, so this updates it to be saner.
The constructor now takes an options object. Any setting you'd want to initialize with is now a constructor option, instead of needing to call methods after the constructor.
(Deprecated settings `roomid` and `joinButtons` still need to be set separately.)
The old callback system is removed. It's replaced with a subscription system vaguely resembling `PSStreamModel`. Any callbacks only intended to be used by the warstory generator are removed (anyone who wants to write their own warstory generator should extend `BattleSceneStub` instead).
Battles no longer start paused. You can still start them paused by passing `paused: true` as an option.
Playback state tracking had a bunch of rearrangement:
- …
> Update Battle class API

- src/battle-text-parser.ts
Fixes [this behavior](https://replay.pokemonshowdown.com/gen8metronomebattle-1286627515) (turn 5):
Waggling a finger let it use Attract!
The opposing Ampharos fell in love!
(The opposing Ampharos used its Mental Herb!)
The opposing Ampharos cured its infatuation using its [ITEM]!
> Display Mental Herb cure text

- src/battle-dex-data.ts
- src/battle-dex-search.ts
this fixes the Pure Hackmons teambuilder to show AG first and properly divides gen6/7/8 moves so astral barrage and z moves dont show up in gen 6
> Fix support for OMs in the teambuilder

- src/battle-text-parser.ts
Compared to what it was like before:
The return cases should be returning the opposite of what they actually are.
> FIx BattleTextParser#team

- js/client-battle.js
I honestly do not know what this was doing before, but it won't enter the for loop because this.battle.myPokemon is an array. This restores the decision-making text, as seen below.
With changes:
> Fix display of move choices

- src/battle-tooltips.ts
This fixes a number of bugs with Speed:
- Tailwind and Pledge swamp now show their Speed changes in tooltips
- Paralysis is now calculated at the end of Speed changes, rather than near the beginning
- A quick and dirty Speed-chaining process to avoid rounding errors (it's not strictly necessary to do 4096s with proper chaining because it happens to be mathematically equivalent).
- Neutralizing Gas now properly removes abilities from stat tooltip calculations (this fixes a number of reported NGas client bugs independently from just Speed)
- Klutz no longer bypasses Power EV items
> Tooltips: Improve Speed calculation accuracy

- src/battle-animations.ts
In doubles, the tooltip for p2b (opponent's right) was mistakenly given the same values as p2c in https://github.com/smogon/pokemon-showdown-client/pull/1738. I assume this was a typo, but just to be sure, @pyuk-bot do you remember if this was necessary for Multi Battles? I tested in FFA and Doubles and now it works correctly.
> Tooltips: Fix hover for opponent's right slot

- src/battle-tooltips.ts
This has been around a while; no idea when it was introduced, but it only affects Hidden Power so far as I know. There's likely a "correct place" to fix this in the build or something but idk how to do that.
Before:
After:
> Tooltips: Fix undefined Hidden Power description

- src/battle-tooltips.ts
Minor regression from Multi Battles. Currently, when checking the ally's Ability, if it wasn't announced (i.e. an entrance ability like Fairy Aura or after Skill Swap or something), it falls back on the multi battle ally's ability. But this is null in doubles, so I readded logic to bring it back. Thanks to @pyuk-bot for her help!
> Tooltips: Fix Victory Star and Battery

- js/client-battle.js
- src/battle-tooltips.ts
The change in client-battle.js fixes an issue where a move like Weather Ball would display as its effective type but be called base name.
Before:
After:
The change in battle-tooltips.js removes the restriction on -ate Abilities displaying relative typing. _Technically_ the games don't display Pixilate Max Hyper Voice as Max Starfall, but that's what it becomes when used during the turn. The games don't display regular Pixilate Hyper Voice as Fairy-type either though, and I think it's better to be consistent and display the effective typing for convenience.
> Tooltips: Fix Max Move typing / name

- src/battle-tooltips.ts
Previously, effects like Normalize would override the typing of Hidden Power and incorrectly indicate it would receive a BP boost. It does not.
> Tooltips: Fix Hidden Power and -ate Abilities

- js/client-topbar.js
- js/client.js
Hopefully this is the correct place to remove the escape (sample replay: https://replay.pokemonshowdown.com/gen81v1-1148003675)
Before:
After:
> Fix double escape in battle and browser tab

- js/client-battle.js
As noted by @urkerab, my fix for Max Move name display in https://github.com/smogon/pokemon-showdown-client/pull/1754 broke G-Max move name display. This fixes it.
> Fix G-Max move name display

- src/battle-dex-data.ts
Certain moves like Gear Grind or Grass Knot have custom BP that doesn't follow the standard Z-move BP chart. This fixes it so their proper Z-move BP is used.
I think this solution is dumb though - I don't get why we'd have to do it this way for Z-moves and not for Max Moves. I'm surely missing something.
> Tooltips: Fix unique Z-move BP

- src/battle-tooltips.ts
This fix will add the adjacent pokemon (if active) to a check for multiple possible BP calculations in a Free-For-All battle.
> Fix missing all BPs in FFA tooltips

- style/battle-log.css
- style/client.css
Firefox removed support for `-moz-appearance: range;` last year. I've replaced it with `revert` but you could also make a case for `auto`.
While I was checking the console I noticed an illegal linear gradient so I fixed that while I was there.
> Make ranges appear again in Firefox

- js/client-battle.js
Simple check to see if gameType is FFA.
> Fix FFA battles referring to nearSide as 'your' Pokemon

- src/battle-animations.ts
- src/battle-dex-data.ts
- src/battle.ts
Corresponding server changes here: https://github.com/smogon/pokemon-showdown/pull/8261
More info on the mechanic is in this twitter thread: https://twitter.com/DaWoblefet/status/1353213137785380864
This does a couple things:
- Point Neutral Xerneas to the correct icon
- Makes Xerneas show its Neutral forme on Team Preview (only the icon for now as Neutral Xerneas currently uses Active forme sprites for everything else)
- Adds support for a new protocol `updatepokemon` to change the icons of Zacian/Zamazenta/Xerneas. Normally I would've used `findCorrespondingPokemon` to get the pokemon to update it, however `searchid` isn't resolved until the pokemon is sent into battle, so I couldn't use that to search for a pokemon and instead had to use only the details to search.
Let me know if the …
> Implement Zacian/Zamazenta/Xerneas forme leak

- src/battle.ts
While the use of `checkDetails` did allow for only the new details to be sent, I overlooked the fact that it didn't work if there is more than one zacian/zamazenta/xerneas (as shown [here](https://replay.pokemonshowdown.com/gen8anythinggoes-1337388488), where the battle log shows 2 `updatepoke` for 2 zacian-crowned but only 1 zacian gets updated). I've added an extra check to see if the details are already an exact match, which should fix the issue.
> Fix |updatepoke

- src/battle-animations.ts
- src/battle-sound.ts
Pokémon Showdown! Beta is absolutely unplayable without Roxie's JP gym theme playing in the background when I switch in a Koffing named Dogars. On a more serious note, it also does not trigger Miror B's theme when I use my extremely viable multi-Ludicolo team in AG.
This fixes the `setBgm` function to call `updateBgm` after changing the BGM. It also changes the `loadBgm` function to stop the current BGM from playing before removing it
> Fix D O G A R S

- js/client-teambuilder.js
- src/battle-dex-data.ts
https://www.smogon.com/forums/threads/automatically-filter-by-type-when-teambuilding-for-monotype.3657897/
It will only filter if the 1st pokemon is a single type or when there is only 1 shared type between the team. (so the part in the suggestion I linked above about filtering dark and steel types at the same time for bisharp would be unfulfilled, but I didn't feel like changing how filters worked). I am also somewhat unsure if where I put the functionality is the best place to put it, but it seems to work pretty well in my testing.
> Automatically filter types for monotype formats

- src/battle.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8845946
Removes an unnecessary removal of the yawn volatile during the `-status` event, as a pokemon can still be drowsy with a status condition if they received the status after they were drowsy, and the yawn volatile gets removed on its own after its duration is up anyway.
> Keep yawn volatile on -status

- js/client-teambuilder.js
- src/battle-tooltips.ts
This implements a number of suggestions for attacks being counted towards Atk IVs or EVs when they shouldn't.
- Flip Turn now recommends -Attack on sets which use Flip Turn as their only physical move ([suggestion](https://www.smogon.com/forums/threads/make-flip-turn-use-a-atk-nature-when-it-is-the-only-physical-move.3684010/))
- Rapid Spin now only recommends 31 Atk IVs before Gen 8 ([suggestion](https://www.smogon.com/forums/threads/dont-default-to-0-atk-iv-rapid-spin-in-gen-8-formats.3677574/))
- Photon Geyser and Shell Side Arm now no longer recommend 0 Atk IVs ([suggestion](https://www.smogon.com/forums/threads/dont-default-to-0-atk-ivs-on-photon-geyser-and-shell-side-arm.3680527/))
- Body Press now no longer recommends Attack EVs if it is the only physical attack on the set ([bug …
> Teambuilder: Improve Attack stat guesser

- js/client.js
- src/client-main.ts
Explanation from Zarel:
PS's client-to-server messages are in the format `ROOMID|MESSAGE`, but with a special exception: Lobby uses a blank roomid. This exception saves a small amount of bandwidth, but causes a few weird bugs, and the bandwidth savings are no longer worth it.
-----
Necessary before server changes to make `|MSG` send to a console, instead of lobby.
> Explicitly notate messages sent to lobby

- js/client-battle.js
| Before | After |
| --- | --- |
| ![play pokemonshowdown com_battle-gen8randombattle-1338161221 (2)](https://user-images.githubusercontent.com/35318437/117725741-7622bc80-b19a-11eb-91f8-1240d0c8fe59.png) | ![_Users_joseph_Documents_GitHub_pokemon-showdown-client_testclient html (1)](https://user-images.githubusercontent.com/35318437/117725818-905c9a80-b19a-11eb-955b-0723421bb87e.png) |
| ![play pokemonshowdown com_battle-gen8randombattle-1338161221 (1)](https://user-images.githubusercontent.com/35318437/117725675-555a6700-b19a-11eb-8349-7b5f6782d69b.png) | ![_Users_joseph_Documents_GitHub_pokemon-showdown-client_testclient html](https://user-images.githubusercontent.com/35318437/117725524-1af0ca00-b19a-11eb-8ef4-f48e98276088.png) |
> Fix some buttons shown after battle/replay not conforming to dark mode

- js/client-topbar.js
- js/client.js
- src/battle-log.ts
- src/panel-mainmenu.tsx
- src/panel-teamdropdown.tsx
This allows support for Rock Paper Scissors games without making the title `s`.
> Fix tab titles for non-battle games

- js/client-chat.js
- js/client-mainmenu.js
Previously, we'd get information for challenges in a single `|updatechallenges|` JSON blob.
That was designed for an even older UX, before challenges were integrated inside PM boxes.
The new format sends `/challenge` inside the PM, allowing the server to more directly control the challenge box inside the PM. This also makes it easier for things that aren't challenges to use the same UI, so e.g. FFA battles can ask for teams, or people can challenge each other to Rock Paper Scissors.
The new format looks like this: `|pm|SENDER|RECEIVER|/challenge GAME|TEAM|MESSAGE|ACCEPTBUTTON|REJECTBUTTON`.
Everything after `/challenge` is optional:
- `GAME` is the format name or game name - if left blank: the format/game name box won't show
- `TEAM` is the teambuilder format name - if left blank: the …
> Support new challenge protocol

- src/battle-animations.ts
If an attack deals more than 99.5% damage, the display will round up on the animation that shows up mid-screen above the Pokemon's sprite in red to indicate the Pokemon took "100%" damage even when it survived. Now, it only displays "99%" damage if the Pokemon were to take near-100% damage.
Note that this only affects player perspective mid-battle; you wouldn't have this issue as a spectator or from the opponent's perspective because it's truncated to 99% earlier.
I originally tried modifying this in getFormattedRange() but encountered problems getting it to return the more precise percentages in the battle log itself.
Replay: https://replay.pokemonshowdown.com/gen8ubers-1346819616
> Don't display 100% HP lost if HP still exists

- src/battle-tooltips.ts
https://www.smogon.com/forums/threads/consider-the-x-256-uncertainty-in-rby-move-accuracy.3668508/
> Gen 1: Account for 1/256 accuracy glitch in move tooltip

- js/client-teambuilder.js
Requested by Coconut.
Should this also be refactored to use `String#startsWith`/`String#endsWith`?
> Default Doubles LC sets to level 5

- src/battle-tooltips.ts
- src/battle.ts
- Makes sure neutralizing gas isn't active and that the target isn't affected by gastro acid
- Makes sure the pokemon with pressure isn't fainted
- Fixes pressure in FFA
- Adds a hardcode to singles for moves without a target (such as 2 turn moves and moves that fail).
> Tooltips: Fix various Pressure related bugs

- src/battle-tooltips.ts
Sound moves only bypass Substitute in Gen 6 and later. Same for Powder moves into Grass, etc.
> Tooltips: Display sound/powder only after Gen 5

- build-tools/build-indexes
- js/client-teambuilder.js
- src/battle-dex.ts
Rather than individually picking and choosing which data to override, I think it's best to just have one object containing all the data to override, at least for the Pokedex and Moves since those have a lot of data to override. The new way I implemented the override allows for more data to be overridden without having to manually add each attribute.
For example, the Arceus formes will now automatically get their plate in gen 6 and below. It also doesn't show unreleased hidden abilities from gen 5 (right now Zapdos, for example, shows static in gen 5 despite it not being valid).
As for moves, the target of a move can be overridden now, as well as its flags (one example of flags needing to be overridden is rock blast, which wasn't considered a bullet move in gen 6 but is gen 7, so right now …
> Override more Pokedex and Move data

- src/battle-tooltips.ts
This fixes a number of display issues with accuracy:
- Accuracy values are more precise in their display, while keeping relative values for multipliers for regular users to understand. For example, the difference between Victory Star Fire Blast and Wide Lens Fire Blast:
- Related to the above, accuracy values are now properly rounded. For example, Compound Eyes Sleep Powder:
Note that this chaining process is not _technically 100% correct_ because of the potential of multiple Victory Star. The order of Abilities being chained would depend on raw Speed (like LightningRod). However, in order to get it 100% correct, you'd have to start tracking host stuff, when a Pokemon last acquired an ability relative to other mons, etc. We don't even have a way to sort by Speed on client afaik, and I …
> Tooltips: Improve accuracy

- build-tools/build-indexes
- src/battle-dex.ts
~~I probably shouldn't have removed this in the first place~~
It turns out new gen moves make it on to the `overrideMoveData` for gen 3 because of me not using `getGen3Category`, which probably shouldn't be happening.
> Use getGen3Category to override move category for gen 3 and below

- src/battle.ts
Corresponding server change: smogon/pokemon-showdown#8287
Does 2 things:
- adds an optional `info` argument to `side.addSideCondition`, which will allow preexisting side condition info to be used when adding a side condition (similar to `replaceSlot` for `side.addPokemon`).
- adds a new `-swapsideconditions` action, which swaps side conditions between sides
> Add -swapsideconditions for court change

- src/battle-animations.ts
Currently it runs only when the forme change is permanent, which means changes like aegislash or minior don't get updated icons when they should unless you skip the turn.
> Update sidebar for all forme changes

- src/battle-animations.ts
(First client pull request) I agree to make this code available under the MIT license.
This behaviour is exposed in Bonus Type. Currently, if a Pokemon's bonus type is its second type, it is correctly displayed by the typechange in the main battle UI. However, if the bonus type is its third type, it is not displayed except in the tooltip, and if a Pokemon increases from having two to three typing due to an in-battle forme change, the bonus type will disappear. With this change, all of the types are displayed consistently.
> Show correct typechange content for Pokemon with 3+ types

- js/client-teambuilder.js
- Make the link redirect to the current tier for Gen 8 formats (was previously only doing it for Gen 7 and below)
- Fixes bh/ag getting appended to the species name without a forward slash (check this [bug report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8903859))
- Uses the proper link for National Dex AG (previously was just using `ag` when it should be `national-dex-ag`)
> Fix Smogon Analysis links in teambuilder

- src/battle-animations-moves.ts
- src/battle-animations.ts
- src/battle-log.ts
- src/battle-scene-stub.ts
- src/battle-sound.ts
- src/battle.ts
- src/globals.d.ts
- tslint.json
Progress is very incomplete, but this is mostly an experiment to establish this as possible at all.
What's going on here is that we're using `remove-import-export` so the `import` and `export` statements just disappear after compiling (everything's still a global).
This allows us to piecewise convert files to modules.
So we're just using TypeScript to keep track of dependencies, and also to make it easier to use these files in other projects later on.
I've tried to avoid circular dependencies, but there's one between `battle-animations` and `battle-animations-moves`.
> Start modularizing some battle files

- build-tools/build-indexes
- src/battle-dex-search.ts
https://www.smogon.com/forums/threads/stabmons.3656429/page-8#post-8931262
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8930934
- Implements new STABmons policy of accounting for past gen move and species typings
- Fixes Mega formes not showing all the moves they should have access to
- Fixes 'Past' moves showing up as illegal in Gen 7 (the way I did this is by adding `isNonstandard` to the list of properties to override for moves, which is why I removed the `dex.gen === 8` checks when checking for "Past" moves since they are unnecessary now)
> Teambuilder: Fix bugs and implement new policy for STABmons

- build-tools/build-indexes
- js/client-teambuilder.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8938391
The issue is that `ModdedDex` doesn't properly handle cosmetic forms. This happens because it checks for battle aliases (and cosmetic forms always redirect to the base species) before getting the base results from the main `Dex` class, which means cosmetic forms never are never returned from `ModdedDex`.
With that being said, I think it's fine to just use the base `Dex` for `setForm`, so it's not an urgent thing to fix. Also note that I didn't change `this.room.curTeam.dex` to `Dex` in the `initialize` function because that part is working fine and there's actually a reason to use the generation dex, since unown doesn't have its `!` and `?` formes in gen 2.
> Fix selecting cosmetic formes in old gens

- js/client-chat.js
On certain Android devices (at least mine and [this guy's](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8697490)), a hidden UTF-8 character (that I cannot identify) is sent alongside a command that causes it to completely skip the cases outlined in the switch statement that would let the command get processed. Here's a video of the strange behavior:
https://user-images.githubusercontent.com/23667022/133870646-1c8a6623-6847-4214-a70a-27568235be4e.mp4
The first time, I send my command through the desktop interface of Chrome devtools (the string is in fact being sent through my phone), which succeeds. The second time, I send it natively through my Android device. The third time is again natively through my Android device, after making …
> Fix client commands on certain Android devices

- build-tools/build-indexes
- src/battle-dex-search.ts
I just found it a bit weird that only gen 7 VGC/BS formats got the special filtering of Restricted Legendary/Regular mons.
Also I don't know what to do about the current Battle Stadium Singles format, since it's series 10 and should show restricteds, but it doesn't have 'Series 10' in the format name like VGC does, so I can't only show restricteds for s10 BSS but not s9 BSS.
> Teambuilder: Use Gen 7 VGC tier slices for all VGC/BS formats

- js/client-battle.js
In formats where you decide to bring more than just leads, currently it says you're sending out your 4-6 Pokemon "first". You can see this most clearly when choosing team slots for Zoroark or in VGC. This PR modifies the text to indicate more clearly which Pokemon are being led, and which Pokemon are in the back. It's a minor QOL improvement.
Before:
After:
> Improve Team Preview decision text

- js/client-teambuilder.js
Currently the only piece of information about the team which isn't visible in the export from clicking Export; thought this might as well be added
Even if the field is to be saved for the planned 'Notes' section in the teambuilder, there's nothing stopping _both_ of them from being there, ex:
```
Format: gen71v1
Blacephalon is bulked for Band Adamant Aegislash with Shadow Sneak
```
> Teambuilder: Add team format to Pokepaste export

- build-tools/build-indexes
- src/battle-dex-search.ts
- src/battle-dex.ts
- Fixes moves that were disabled in gen 8 from not showing pre gen 8
- Fixes doubles bdsp formats from showing nonstandard items
> Teambuilder: Fix bugs from #1889

- js/client.js
the `?act=uploadreplay` breaks when removing the /~~serverid/action.php magic.
It would be ideal if this could be merged and patched asap - rn replays aren't working for people on new clients.
> Fix uploading replays

- build-tools/build-indexes
- src/battle-dex-search.ts
This is fairly high priority, as a BDSP Monotype format will exist in the next 24 hours, and with the current client, trying to make a team in "gen8bdspmonotype" crashes the client (shows a blank teambuilder); this also fixes future instances.
> Add BDSP Monotype teambuilder support

- build-tools/build-indexes
- src/battle-dex.ts
Mainly doing this so that `isNonstandard` gets overridden for bdsp
> Refactor Ability data overriding

- js/client-battle.js
Client-side for https://github.com/smogon/pokemon-showdown/pull/8640
When the "Automatically start timer" box is ticked, now it will no longer send a start timer request if the game has ended.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Prevent setting timer after a game has ended

- js/client-topbar.js
- js/client.js
- js/storage.js
- src/client-main.ts
- src/panel-topbar.tsx
- src/panels.tsx
https://www.smogon.com/forums/threads/add-option-to-match-system-theme-for-light-dark-mode-in-client.3695930/
One question I have is do I have to check if `window.matchMedia` exists before using it? The support for it seems to go pretty far back but I check if it exists just to be safe. Please let me know if I don't need to do that.
> Add option to match system theme for light/dark mode

- src/battle-tooltips.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9187239. This bug extends beyond Custom Game; currently Eviolite Ursaring will show the boost in Gen 7 and National Dex formats as well which is definitely a bug.
Uses the server-side implementation for Eviolite from @pyuk-bot: https://github.com/smogon/pokemon-showdown/pull/8650
> Fix Eviolite with PLA evolutions

- build-tools/compiler.js
- package.json
Conversation: #1707
Issue: #1968
> Add source-map dependency

- src/battle-dex-search.ts
This implements some old suggestions from;
https://www.smogon.com/forums/threads/move-category-suggestions.3671530/page-3#post-8981161
https://www.smogon.com/forums/threads/move-category-suggestions.3671530/post-8653106
As well as a few others.
Moves like Growth and Headbutt are generally useful in RBY given the environment. Tangela uses Growth quite a bit in UU and, well, y'know, Special is good. Headbutt is frequently used in Tradebacks and has a few niche uses on UU Dewgong for paraflinching. 
Haze is terrible and should always be useless. In the Tradebacks teambuilder this clogs up stuff a lot. I cut Ice Punch from the useless area because it has legitimate freeze fishing uses due to having more PP than Ice Beam. In Tradebacks this is important on a few Snorlax sets, and I think Jynx …
> Gen 1: Update Useful/Useless Moves

- src/battle-dex-search.ts
So I had these updated in another pull request (#1972), but a few RBYers brought up some more candidates I probably missed.
Thunder has one use-case, and it's on Zapdos in Ubers specifically, and even there it's pretty niche. Unlike in later gens, it rarely has game-defining calcs (GSC) and doesn't have rain to support it (Drizzle gens), so it's just kind of awful. It doesn't even have a 30% paralysis chance, it's just 10.1%, so even that reason to run it doesn't exist. With less turn-by-turn average damage than Thunderbolt, it's at least worse than Toxic.
Waterfall doesn't flinch in this generation, which makes it a worse Surf in literally every scenario. It's Seaking's signature move, and it doesn't use it because, well, it has Surf. In Tradebacks, it's just teambuilder clutter a la …
> Gen 1: Add Thunder and Waterfall to usually useless

- src/battle-text-parser.ts
- src/battle-tooltips.ts
Fixed a "bug" (I think it wasn't just programmed just a feature not completely implemented).
For both of these fixes I just added conditions to take into account the "Ignore Nicknames" Option.
> TOOLTIPS/TEXT PARSER: Fix Nickname in tooltips and in Battle Log

- js/client-chat.js
Basically [this PR](https://github.com/smogon/pokemon-showdown-client/pull/1863) but for the command target; same bug basically. See [sample bug report of behavior with the /highlight command](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9330339).
> Fix more client commands on some Android devices

- js/client-rooms.js
I added a feature to allow the user count and active battle counts to automatically update themselves every 20 seconds.
Currently these values only update on refocusing the room window after 60 seconds have passed since last updated.
> User and active battle counts update on an interval

- src/battle-dex-search.ts
Prevents Pokemon who only learn moves in previous generations while searching, i.e. knock off shows bisharp right now
> Teambuilder: Don't show Pokemon that don't learn moves in Gen 9

- js/client.js
- lib/dispatcher.lib.php
Approved by US.
I specifically routed this through the loginserver in order to have it write to the usermodlog (requested by US).
This reads/writes to a `config/colors.json` file that clients request on startup, and then assign to the existing colors (I specifically chose a new JSON file because editing the config directly programatically would be a nightmare).
I'll be setting up the server-side command code shortly.
> Support changing namecolors through the loginserver

- src/battle.ts
Turns out that Costar actually does copy the crit volatiles, so I am fixing my mistake from #2020
> Allow Costar to copy crit volatiles

- src/battle-animations.ts
This mostly just makes undefined tags less... ugly? If something exists somewhere for them in the main data files. This is mainly only relevant for OMs, but it will make things like Salt Cure prior to its bad effect being implemented on the client look better than just `[[saltcure]]`.
> Add more support for undefined effect tags

- src/battle-log.ts
This is necessary for a custom identifier for the |scroll| message type. I originally wanted data-time to sort out timestamps, but I figured this would be a better all-use attribute that other server pages could use to identify divs for scrolling to / other selector stuff (Caja sanitizes out data-* attribs otherwise)
> Battle-log: Whitelist a data- attribute for server-side divs

- js/client-teambuilder.js
- js/storage.js
Now that Open Team Sheets are a more "official" thing, it would be greatly beneficial for there to be an option to upload your current team without anything related to stats, as currently you need to make a copy of your team and manually remove the stats before uploading. This button will only be displayed in VGC formats.
In addition, Tera Types will now always be shown when exporting a set/team, even if it is the primary type of the Pokemon.
> Add Open Team Sheet PokePaste button to VGC formats

- src/battle-animations.ts
While I was working on a custom theme, I noticed that it was not possible to tell which pokemon was positioned to the right or left during a double battle. This made it impossible to properly edit the "statbar" via css.
> Add CSS class based on field slot (left-center-right)

- src/battle-text-parser.ts
This should allow stuff like Electromorphosis/Wind Power or Shed Tail to have their own start text when using shared volatiles.
> Prefer [from] effect for -start template

- js/client.js
This fixes accessing localhost. Previously, browsers forced http to https, meaning the WebSocket connection was made to port 443 on https instead of the correct http connection to whatever port. This ensures localhost is always connecting to http and on the correct port, which is added to the querystring by the redirect in `ps/server/static/index.html`.
> Bypass https on localhost

- js/storage.js
I got a report about tera types being lost when using the "Backup and Restore all Teams" option in teambuilder. It occurs if you import teams with a valid importable (and save), and then go back to the same location and hit save again.
The issue can be seen here (video from the reporter): https://youtu.be/yXxBpPW9jaw 
The issue was that when importing via the backup option (many teams), the generation of the team was not saved. This is in comparison to editing a specific team which handles that. One the second save, the tera type information is not presented in the exportable backup (which is saved) because the generation for the team is not recorded in `Storage.teams` due to tera types being skipped if `team.gen` is not `9`. This results in data loss if the teams are saved again.
> Prevent data loss when importing backed up teams

- src/battle-animations.ts
- src/battle-scene-stub.ts
- src/battle.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9474682
> Fix Tera permanently replacing sprite

- src/battle-text-parser.ts
For smogon/pokemon-showdown#9473
This is needed because we only replace things like `[TARGET]` once but Commander uses `[TARGET]` twice.
> Support new Commander activation message

- js/client.js
Matches what was done recently server-side to prevent the validator process from crashing: https://github.com/smogon/pokemon-showdown/commit/840ad204e496e73c49ad164a3c9cba5652e0a933
> Update raw team length restriction to 25 KB

- lib/ntbb-ladder.lib.php
Truthfully I'm not sure what this code does: why does the client require the Elo decay rules? Regardless, rules have changed in the loginserver so they should probably change here too.
loginserver commit: https://github.com/smogon/pokemon-showdown-loginserver/commit/1186bcfb4ab5839fc0d3dcf6a92b3377665f0011
> Ladder: Set current gen to 9 for decay purposes

- js/client-topbar.js
- src/panel-topbar.tsx
- style/client.css
- style/client2.css
fix for #1943 
First PR here, so open to constructive feedback on how to better do this, if this is applicable.
> (fix): hide username on screens smaller than 500px

- src/battle-tooltips.ts
- src/battle.ts
This displays the "Tera Type: " reminder for pokemon which were previously terastallized.
> Denote once-terastallized Pokemon via teraType

- js/storage.js
- src/panel-teamdropdown.tsx
addresses my issue here: https://github.com/smogon/pokemon-showdown-client/issues/2091
Also addressing this issue here: https://www.smogon.com/forums/threads/default-to-31-ivs-on-pokemon-with-hidden-power-in-generations-with-hyper-training.3692969/
I wanted to see if I could make it depend on the format of the team it was being imported to but it doesn't appear that the areas of code responsible for this issue have access to that information. Only the storage import can use it so I went ahead and implemented it there. This is the best fix I could find.
Here are the reasons I made this PR:
1) The way this was implemented ended up being very insidious. Players are having their teams nerfed without their knowledge and have lost battles they would have one without it. Due to how sneaky this …
> Fixed IV defaults for generations with hypertraining

- src/battle.ts
Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9751369
Currently, if multiple Pokemon have the same nickname, Revival Blessing will always heal the first, even if it's not fainted.
Test replay: https://replay.pokemonshowdown.com/gen9purehackmons-1928803548
> Ensure Revival Blessing only heals fainted Pokemon

- src/battle-text-parser.ts
- src/battle.ts
I didn't want to hardcode this, but it seems like absorb abilities like volt absorb and dry skin depend on the client not using the pokemon from `[of]` to properly show their activation message. That feels like something that should be fixed server side (the source of healing for those abilities should be the same as the ability holder), but if I did fix that old replays would have incorrect activations unless I hardcoded removing `[of]` from said absorption abilities (which is what used to be done).
> Fix Hospitality activation message

- js/client-battle.js
When using the setting `Confirmation before leaving a room`, there's a bug that prevents you from leaving if you have this setting turned on. I haven't found any regression, let me know if you want me to test a specific use case
Example on how to replicate the bug:
- Toggle the setting `Confirmation before leaving a room` to true 
- Create groupchat with ``/mgc``
- Destroy it with ``/dgc``
- Try to leave
> Fix leaveroom confirm when the room no longer exists 

- js/client.js
- src/panel-mainmenu.tsx
Goes from this
To this
Originally we were going to include the format in the room title, but that leads to longer tab names than is probably necessary.
> Support best-of-n room titles

- js/client-mainmenu.js
Adds a best-of-three checkbox to VGC formats (note: depending on how this is received, we may want to generalize with a property server-side on the format itself so other formats can also use it). When this box is checked, it adds Best of = 3 to custom rules sent to the challenge partner. The challenged recipient cannot select to make the format bo3.
Unlike privacy, I don't want to store the current state of bo3 being checked, because I can imagine lots of cases where you'd want to regularly switch back and forth. I recommend whenever we add a bo3 ladder that we make ``challengeShow: false`` for that format.
Credit @Karthik99999 for helping to parallel program this change.
> Bo3: Add challenge checkbox for VGC formats

- js/client-chat-tournament.js
- js/client-mainmenu.js
- js/client-teambuilder.js
- js/client.js
- js/storage.js
Client-side integration for the teams database.
This PR: 
- Adds a button to upload a team next to the pokepaste button.
- Supports pulling teams from the external DB via the loginserver. This is split into two levels: on startup, the client requests a list of teams from the loginserver, which responds with a list of teamIDs, mon IDs from that team, format, and team name. This leaves out the majority of the data. When the user opens the team in teambuilder, or tries to do anything with it, the app loads it from loginserver, caches it, then uses it. 
I dislike having to add a callback parameter to sendTeam, but unfortunately we do not support async/await at the moment. Will take suggestions to improve that though.
> Support loading teams from server, add button to upload teams

- src/battle-log.ts
- src/battle.ts
- Moves the HTML generation to `BattleLog`
- Creates functions for `unpackTeam` and `exportTeam` under `Battle` as replays do not have access to the `Storage` functions.
> Fix `showteam` in replays

- js/client-mainmenu.js
This adds a search button to the format list, and collapses most of the section dropdowns by default (defaults were determined by US and hardcoded for now, since the panel will just cache which dropdowns users open/close).
> Overhaul the format selector to be more easily used

- js/client-mainmenu.js
> Format Selector: Hide categories with no matches from search

- js/client-mainmenu.js
- js/client.js
Right now, the checkbox used for team-locked best-of-3 play is limited to VGC formats. This change allows the server's format list to determine which formats have the checkbox by default. This was initially requested by side servers, but also fixes a very minor bug of team-locked bo3 challenges showing up for Gen 4 VGC, where you weren't team-locked (you could move around items in between a best-of-three and change team order). I'm sure we'll eventually have a non-VGC format that wants best-of-n support on main as well.
It also allows the challenger to select any of the supported best-of-n options, rather than exclusively being best-of-3.
I'm not super sure about the policy of inline CSS; it's needed for the number input. I can move it to a proper CSS file if desired.
> Support more variable best-of challenges

- js/client-battle.js
- js/client-chat.js
- js/client-mainmenu.js
- js/client-rooms.js
- js/client-teambuilder.js
- js/client-topbar.js
- js/client.js
- src/battle-tooltips.ts
- src/panel-topbar.tsx
- style/STYLING.html
- style/battle-log.css
- style/battle.css
- style/client.css
Felucia mentioned she had some custom CSS in dark mode to make it darker, so I figured I'd try my hand at a design refresh to make it not quite so bright. In the process, I've made the buttons look more 3D, matching light mode. Sorry, any dark mode users who prefer flat design.
This also updates all remaining OS-style buttons into PS-style buttons, so they'll be properly dark-mode.
This refresh focuses on dark mode, but light mode gets some improvements as well.
(top: old, bottom: new)
(left: old, right: new)
(left: old, right: new)
(left: old, right: new)
(left: old, right: new)
(left: old, right: new)
(left: old, right: new)
(left: old, right: new)
> Design refresh

- js/client-chat-tournament.js
- style/client.css
- style/client2.css
Mobile devices that don't have a mouse-attached can't pan the tournament bracket view.  This was because the listeners were registered for specifically _mouse_ instead of _pointer_
This presents a fix.
I tested this for mobile versions of chrome, firefox, and opera (dev tools).  The panel can now be panned with touch.
-Quazizata
> Fix Tourney Bracket panning for touch devices

- play.pokemonshowdown.com/src/battle-animations-moves.ts
I'm sure animations for all the new moves are being worked on, but I figured it would be best to get something in for Electro Shot rn so that the crash text for not having a prepareAnim doesn't appear every time it gets used.
> Add animation for Electro Shot

- play.pokemonshowdown.com/js/client-chat.js
- play.pokemonshowdown.com/src/battle-dex.ts
https://www.smogon.com/forums/threads/show-afd-sprites-in-teambuilder-if-the-mode-in-on.3731991/
- AFD sprites can now show up in the teambuilder
- Turning on AFD sprites now persists through reloads
> Improve April Fool's sprite support

- play.pokemonshowdown.com/src/battle-dex-data.ts
- play.pokemonshowdown.com/src/battle-tooltips.ts
- play.pokemonshowdown.com/src/battle.ts
- Fixed `getTypes` to account for Stellar tera not affecting normal types
- Added Stellar to the `TypeName` type
- Made Tera Starstorm change to Stellar type only when used by Terapagos-Stellar
> Tooltips: Fix issues with Stellar type

- play.pokemonshowdown.com/js/client.js
Copy replay link button functionality was previously not working. This might not be the best way to "fix" that, as there is an existing copyReplayLink function present in the same file. 
This is my quick-and-inelegant solution with the purpose of possibly providing a short term solution until a better one can be found.
Thanks!
> Fix copy replay button functionality

- play.pokemonshowdown.com/js/client-teambuilder.js
streamlines validation progress for the new Min-20/15 IV pokemon given to us in Indigo Disk DLC
> Teambuilder: Fix IV values for certain Indigo Disk Pokemon

- play.pokemonshowdown.com/style/battle-log.css
I noticed certain format names in the formats dropdown are too long and end up cutting off, this change removes no-wrap from .option to make sure they do.
I went through every usage of the `.option` class and most of them have static-length content that is not affected by this change, the only other place this matters is for long team names in the team dropdown, which seems like a neutral (maybe slightly positive?) outcome for usability
> Wrap long format names

- play.pokemonshowdown.com/src/battle-dex-search.ts
Thief is ubiquitous in gen 2 as it is the only way to remove an opponent's Leftovers.
fulfilling this suggestion: https://www.smogon.com/forums/threads/move-category-suggestions.3671530/page-3#post-9008076
> Gen 2 Thief: Not Useless

- play.pokemonshowdown.com/js/client-battle.js
- play.pokemonshowdown.com/js/client-teambuilder.js
- play.pokemonshowdown.com/src/battle-choices.ts
- play.pokemonshowdown.com/src/panel-battle.tsx
Server: smogon/pokemon-showdown#10212
Supersedes #1996
> Let's Go: Support itemless megas

- play.pokemonshowdown.com/js/client-battle.js
- play.pokemonshowdown.com/js/client-ladder.js
- play.pokemonshowdown.com/src/battle-animations.ts
- play.pokemonshowdown.com/src/battle.ts
Client end for https://github.com/smogon/pokemon-showdown/pull/10222.
> Add support for adding badges in battle

- .eslintrc.js
- play.pokemonshowdown.com/js/client-teambuilder.js
- play.pokemonshowdown.com/src/battle-dex-data.ts
- play.pokemonshowdown.com/src/battle-tooltips.ts
- test/ev-optimizer.test.js
https://www.smogon.com/forums/threads/smart-ev-management-in-the-builder.3736254/
> Teambuilder: Add EV optimization checker

- play.pokemonshowdown.com/js/client-teambuilder.js
This is an implementation of [a suggestion to display user sample sets from boxes](https://www.smogon.com/forums/threads/teambuilder-improvement-user-sets.3730629/).
The first time a user clicks "Import/Export" in a set view of the teambuilder, this addition will scan through the teambuilder for any boxes with the appropriate format, and cache all sets as user samples. These will then be displayed as buttons. User samples with duplicate names receive a number suffix. 
The cache for a given format is cleared if the user exits a box in said format. Caching reduces repetitive scans each time the user wants to import a set.
I did a quick "performance" test by creating 5000 teams, does not cause hiccups for me at least. Tested on Firefox. The bottleneck, if any, has been the smogon samples …
> Teambuilder: Generate user samples from boxes

- play.pokemonshowdown.com/js/client.js
This line looks for URLs without a port specified and sets the default port of 8000. However, in the case of IP subdomains (such as `127.0.0.1-12345.psim.us`), the port `12345` is overwritten because the `-` is ignored by the unescaped dot.
This PR escapes the dots forming the IP address and ensures the port is not being overwritten when specified.
Tested in the console's browser:
> client: escape dots in URL regex

- build-tools/build-indexes
- play.pokemonshowdown.com/src/battle-animations.ts
- play.pokemonshowdown.com/src/battle-tooltips.ts
- play.pokemonshowdown.com/src/battle.ts
https://www.smogon.com/forums/threads/bug-report-client.3742657/
The reason it broke is because the tooltips object is created before the client receives the `gen`/`tier` protocol that updates the battle dex, so the tooltips were always using the latest dex. I reverted the change that gave tooltips its own `dex` property, because it doesn't make much sense to double up on the logic to determine what dex to use.
> Fix past gen tooltips

- play.pokemonshowdown.com/src/battle.ts
https://www.smogon.com/forums/threads/reset-tooltips-on-pivot-move-faint-replacement.3733788/
> Fix tooltips getting cleared when using switch moves

- replay.pokemonshowdown.com/src/replays-battle.tsx
Currently, the `‹ More Replays` button that is shown on mobile always takes you back to the main replays page. This change should preserve the original search query.
> Replays: Fix More Replays button on mobile

- play.pokemonshowdown.com/js/client-rooms.js
PR for https://www.smogon.com/forums/threads/give-an-option-for-1000-minimum-elo-in-the-battles-tab-to-filter-out-challenge-battles.3743305/
> Add Elo filter 1000

- build-tools/build-indexes
- play.pokemonshowdown.com/src/battle-dex-search.ts
Screenshots that showcase changes:
Pokemon that are unavailable in BW2:
Pokemon that don't have access to their Dream World ability:
Pokemon that were Uber in BW1 that are OU in BW2:
Pokemon that were OU in BW1 that are Uber in BW2:
Pokemon without moves that they would gain in BW2:
Items that are unavailable in BW1:
Edit: Thank you @Karthik99999 for pointing me in the right direction!
> Add teambuilder support for gen5bw1 formats

- play.pokemonshowdown.com/src/battle-tooltips.ts
Based on the description laid out in this thread: https://www.smogon.com/forums/threads/add-the-1-2x-damage-calculation-of-ogerpon-wellspring-hearthflame-cornerstone-mask-to-move-ui.3746567/
Local testing LGTM!
Please send any feedback my way, more than willing to learn here!
> Fix issue where 1.2x damage calculation is not showing properly

- play.pokemonshowdown.com/js/client-teambuilder.js
Bug fix for this report: https://www.smogon.com/forums/threads/bug-report-team-selector-after-creating-teams.3733626/
Teams are stored as an array in `Storage.teams`. The team selection dropdown determines which team to send to the server when a player hits "Battle!" by using its `value` attribute as an index for the teams array. When a new team is created at the top of the team list, its placed at the front of this array becoming index 0 and shifting all other indexes up by 1. However, the team selection drop down's value was not updated resulting in the client sending the wrong team to the server. This fixes this by incrementing the value when a new team is added to the top of the list.
> Fix client sending the wrong team to the server in some cases

- play.pokemonshowdown.com/js/client-mainmenu.js
- play.pokemonshowdown.com/src/battle-log.ts
Currently, if you send an `/html` message with `&` as the identity, it treats `&` as a username and shows it before the message with a colon.
This change should allow the message to look like this instead
I would like this feature for the auctions plugin so that I can send messages with username colors without sacrificing the timestamp like I would be doing by sending `/raw`.
> Chat: Support nameless /html messages

- play.pokemonshowdown.com/src/battle-tooltips.ts
Currently, when the teambuilder supplies a guessed spread, it will consider moves with the empty string for its check. This prevents the teambuilder from guessing spreads after the user only puts in 3 moves.
I'm not sure if the correct fix is here or in some way deleting the empty string move from ``set.moves`` altogether at some other point.
> Don't guess spreads when there are empty moves

- replay.pokemonshowdown.com/src/replays.tsx
https://replay.pokemonshowdown.com/gen9randomdoublesbattle-2166911071-qf1du9ia5dcexqhbj1pzsjy4ioophu9pw
My name in replays shows up as the default color even though I have a custom color set here https://play.pokemonshowdown.com/config/colors.json to turn it blue.
> Replays: Load custom colors JSON file

- pokemonshowdown.com/ladder.php
Before:
After:
Is there a reason that the widths are even specified though? Getting rid of all the width values also makes the table keep everything on one line.
> Fix formatting of Glicko-1 on ladder page

- play.pokemonshowdown.com/js/client-mainmenu.js
- play.pokemonshowdown.com/js/client.js
Adds a checkbox to toggle tera preview for the gen 9 draft formats.
> Client-Side Tera Type Preview Checkbox

- play.pokemonshowdown.com/js/client-teambuilder.js
Wasn't fun having my browser frozen for half a minute every time I typed more than two letters in the teambuilder search; this PR introduces debounced calls to updateTeamList() instead of direct calls.
Tested locally on Chrome 127.0.6533.72
> Teambuilder: Debounce searching teams

- play.pokemonshowdown.com/js/client-chat.js
https://www.smogon.com/forums/threads/bug-report.3749269/
At this point, it's a bit more than a bug fix. It seems intuitive that attempting to perform a tab-complete on one line should search for commands on that line, but it doesn't because it's searching for commands using the entire text box, which was also causing the issue of sending lines into chat.
Besides that, I also reverted the behavior of both commands and usernames being able to be candidates of the same autocomplete, while retaining the ability to autocomplete usernames if placed after the command; I'm not sure how it was helpful to go between commands and usernames.
> Use only current line in tab-completing commands

- play.pokemonshowdown.com/js/storage.js
It was possible to freeze the tab by importing a team/set containing `]` with no `|` after.
(only if the whole import is 1 line or 2 lines with the 2nd one being blank - this leads to the importer using `Storage.unpackTeam()` which is intended functionality.)
I took care to not conflict with #2222 . hopefully we can discuss rewriting the packed team format after these prs are resolved ...
credit for finding this bug: https://github.com/smogon/pokemon-showdown-client/pull/2283#issuecomment-2370371178
> Fixed a case of endless loop

- play.pokemonshowdown.com/src/battle-dex-search.ts
Read here for more info:
https://www.smogon.com/forums/threads/move-category-suggestions.3671530/page-4#post-10301044
> gen 3 useful + useless moves update

- play.pokemonshowdown.com/src/battle-animations.ts
- play.pokemonshowdown.com/src/battle-tooltips.ts
- play.pokemonshowdown.com/src/battle.ts
Exact HP mod sends current HP and Max HP to both the user and the opponent via server protocol messages, but displays percent regardless unless the user turns on hardcore mode, making it information almost only accessible via the console. This pull request displays the current hp in the hp bar and the current and Max HP in the pokemon's tooltips for easier accessibility.
Before:
https://github.com/user-attachments/assets/606f60bc-a4ee-4666-9144-c5432f517855
After:
https://github.com/user-attachments/assets/d103e177-005f-4132-a425-0d14e49a2008
> Display exact HP when using Exact HP Mod

- play.pokemonshowdown.com/src/battle.ts
For Gen 4-5 Frisk. If no target is sent with an -item message, the client first checks if there is exactly 1 possible target, and updates its item.
> Support blank target in -item message

- play.pokemonshowdown.com/js/storage.js
- play.pokemonshowdown.com/src/client-core.ts
- pokemonshowdown.com/credits.php
replaced deadlink with updated link of one of the contributors
[Jessica Valencia [seiryuuden]](http://seiryuuden.deviantart.com/)
– Art (Charizards background)
> Update credits link for artist Seiryuuden

- play.pokemonshowdown.com/js/storage.js
- play.pokemonshowdown.com/src/client-core.ts
- pokemonshowdown.com/credits.php
Update credits link for artist Yilx
Samuel Teo [Yilx]
– Art (Waterfall background)
> Update credits link for artist Yilx

- play.pokemonshowdown.com/src/battle.ts
This fixes a pretty well known visual glitch in replays where spikes don't show up on second viewing (after restarting the replay). The issue is that on a second viewing, [this condition](https://github.com/smogon/pokemon-showdown-client/blob/dd392d9fa9216cb4e4d3d8ee75e053188e2f27bf/play.pokemonshowdown.com/src/battle-animations.ts#L1300) doesn't trigger because `sideConditions` (and `spikeArray`) still had the old values.
Reproduction Steps:
1. Load a replay and watch until spikes are set
2. Click "First turn"
3. Watch until spikes are set again. They don't show up.
[Example replay](https://replay.pokemonshowdown.com/gen3randombattle-2166967126)
json:
```
{"id":"gen3randombattle-2166967126","format":"[Gen 3] Random Battle","players":["SandyEggo","test92011"],"log":"|j|\u2606SandyEggo\n|j| …
```
> Fix missing spikes visual glitch in replays

- play.pokemonshowdown.com/js/client.js
- play.pokemonshowdown.com/src/client-main.ts
Regression from the transition back to ~ for admin symbol; see https://github.com/smogon/pokemon-showdown-client/pull/1618
> Move room owners above admins once again

- play.pokemonshowdown.com/js/client-teambuilder.js
Currently throws a console error when you click "Import/Export" on a pokemon set when building a team for a format that doesn't have sets on the smogdex (Example: Gen 4 1v1). Notably this prevents box sets from showing up for those formats
> Teambuilder: Fix error on set import for formats without dex sets

- play.pokemonshowdown.com/style/battle-log.css
implements the [suggestion to add a horizontal scrollbar for boxes on smaller resolution screens](https://www.smogon.com/forums/threads/add-a-horizontal-scrollbar-for-boxes-on-smaller-resolution-screens.3671644/)
This only affects boxes that have a set width that is already overflowing, and as such shouldn't have any implications for boxes that didn't already look horrid to begin with. This would put burden on writers of infoboxes to use width or min-width properties if they don't function below a certain width, but they should've been doing that anyway so I don't think it's within the scope of this change to do it for them.
> Add horizontal scroll bars to wide infoboxes on small screens

- replay.pokemonshowdown.com/index.template.php
- replay.pokemonshowdown.com/src/replays-battle.tsx
- replay.pokemonshowdown.com/testclient.html
Added a volume slider to the replay client, updated the `.optgroup` class to adjust the look.
> Add a volume slider to Replays

- play.pokemonshowdown.com/js/client-chat.js
- play.pokemonshowdown.com/js/client-mainmenu.js
Implements [Improve how !ds all displays](https://www.smogon.com/forums/threads/improve-how-ds-all-displays.3654308/)
Supports the server-side changes from [this PR ](https://github.com/smogon/pokemon-showdown/pull/10995)
Backing javascript for toggling the display of datasearch results. This would have been implemented using the existing readmore option which uses the `<details><summary>` tags with an inline display, but Chrome creates a linebreak after the summary results preventing them from properly joining together with the rest of the results.
> Collapsible Datasearches

- play.pokemonshowdown.com/src/panel-popups.tsx
- play.pokemonshowdown.com/src/panels.tsx
Everything is almost same as the regular client **except**:
When you open the forfeit popup and refresh the page, youre still at href='/forfeitbattle' so instead of opening and focusing the battle room it tries to add the forfeit popup as a chatroom (see attached screenshot). 
maybe we can fix this by manually adding the popup id to ``PS.routes`` 
OR
maybe whenever the page is reloaded we can skip loading semimodal popup rooms by adding a check in ``subscribeHash`` and ``subscribeHistory``.
or maybe i just missed something, please let me know what you think.
> Preact: Support forfeiting battles

- play.pokemonshowdown.com/src/battle-dex-data.ts
I'm not sure why the type of `type` in the server's code is `string`; it should probably just be `TypeName`.
Edit: it's because `TypeName` doesn't exist in the server.
> Properly type `Item.naturalGift`

- play.pokemonshowdown.com/src/battle-log.ts
- play.pokemonshowdown.com/src/panels.tsx
- tsconfig.json
Auto-show spoilers causing spoilers to always show isn't Preact-exclusive as far as I can tell, but collapsible datasearches haven't been implemented on Preact yet. I just copied the existing code from the old client.
Regarding collapsible datasearches, someone reported that it's [hard to copy and paste dexsearch results](https://www.smogon.com/forums/threads/bug-report-unsure.3763470/) as a result of this new feature. This PR doesn't address the bug report and mainly serves to add the functionality to Preact, but I figured it's worth noting for another fix.
> Preact: Fix auto-show spoilers

- .gitignore
- play.pokemonshowdown.com/src/panel-topbar.tsx
I have the `title` attribute set to `{hoverTitle || undefined}` so the title attribute is properly removed when there's no notifications instead of just being empty.
> Preact: Add support for hovering over roomtabs with notifications

- play.pokemonshowdown.com/style/teambuilder.css
> Preact Teambuilder: Fix the team textbox placeholder on Firefox

- play.pokemonshowdown.com/src/battle-team-editor.tsx
When searching for a non-existing Pokémon in the Preact teambuilder and pressing Enter, the Pokémon name field would display HTML entities like `&lt;em&gt;No exact match found. The closest matche...` instead of remaining empty or showing a proper error.
This happened because the search results include an 'html' type row with the error message when no exact match is found. The `getResultValue` method was returning this raw HTML string, which was then set as the Pokémon name.
**Changes:**
- Modified `getResultValue` in `battle-team-editor.tsx` to return an empty string for 'html' and 'header' type search results
- This prevents HTML content from being incorrectly used as a Pokémon name value
**To reproduce the bug (before this fix):**
1. Open the teambuilder
2. Search for a non-existing …
> Preact: Teambuilder fix HTML entities in Pokémon name on invalid search

- build-tools/build-indexes
Approved Forum Suggestion: https://www.smogon.com/forums/threads/gen-5-ou-gems.3706516/
I can't replicate this locally. Whatever script is used for build indexes code to be compiled into the teambuilder table isn't there in the client repo clone. and while making direct changes to the teambuilder table file does work locally, that's not how it's supposed to be edited. This is a pretty trivial change so I figured it's worth the PR anyways even if my clone can't replicate this.
The logic here is removing the if else statement for flying gem, will push it out of great items (popular items), and the line under that pushes all gem's to good items, will then include Flying Gem since it's specific if else statement will be removed.
> Remove Flying Gem from Popular Items

- play.pokemonshowdown.com/js/client-teambuilder.js
- play.pokemonshowdown.com/src/battle-team-editor.tsx
Since Gimmighoul-Roaming is only obtainable from Pokemon GO, Atk and Sp. Atk IVs must match.
Seems logical to default to being 31 for both.
> Do not Set Gimmighoul Atk IVs to 0 by default
